UVCD_TARGET=libusb_uvcd
UVCD_PATH=$(TARGET_APP_SRC_PATH)/diag/common/usb/device_classes/uvc
obj-y += $(UVCD_TARGET).a
$(UVCD_TARGET)-objs = $(UVCD_PATH)/ux_device_class_uvc_activate.o
$(UVCD_TARGET)-objs += $(UVCD_PATH)/ux_device_class_uvc_commit_control.o
$(UVCD_TARGET)-objs += $(UVCD_PATH)/ux_device_class_uvc_control_request.o
$(UVCD_TARGET)-objs += $(UVCD_PATH)/ux_device_class_uvc_entry.o
$(UVCD_TARGET)-objs += $(UVCD_PATH)/ux_device_class_uvc_initialize.o
$(UVCD_TARGET)-objs += $(UVCD_PATH)/ux_device_class_uvc_payload_send.o
$(UVCD_TARGET)-objs += $(UVCD_PATH)/ux_device_class_uvc_probe_control.o
$(UVCD_TARGET)-objs += $(UVCD_PATH)/ux_device_class_uvc_reset.o
$(UVCD_TARGET)-objs += $(UVCD_PATH)/ux_device_class_uvc_thread.o
$(UVCD_TARGET)-objs += $(UVCD_PATH)/ux_device_class_uvc_status_get.o
$(UVCD_TARGET)-objs += $(UVCD_PATH)/ux_device_class_uvc_status_set.o
$(UVCD_TARGET)-objs += $(UVCD_PATH)/ux_device_class_uvc_deactivate.o
$(UVCD_TARGET)-objs += $(UVCD_PATH)/ux_device_class_uvc_buffer.o
$(UVCD_TARGET)-objs += $(UVCD_PATH)/AmbaUSBD_Uvc.o

install-files += $(UVCD_TARGET).a