ccflags-y += -I$(srctree)/bsp/$(AMBA_CHIP_ID)/peripherals/lens/inc

LENSPATH=lens
libperif_$(AMBA_CHIP_ID)-objs += $(LENSPATH)/AmbaLens.o 
libperif_$(AMBA_CHIP_ID)-objs += $(LENSPATH)/AmbaLens_OV48C40_LC898249XH.o


