#ifndef __USER_SETTING_H__
#define __USER_SETTING_H__

#define USER_SETTING_PREF_DIR               "a:\\pref"
#define USER_SETTING_SAVE_PATH              USER_SETTING_PREF_DIR"\\settings.ini"
#define USER_SETTING_DUAL_RECORD_TEST       USER_SETTING_PREF_DIR"\\dual_record_test.txt"
#define USER_SETTING_UVC_MODE               USER_SETTING_PREF_DIR"\\uvc_mode.txt"
#define USER_SETTING_UVC_MODE2              USER_SETTING_PREF_DIR"\\uvc_mode2.txt"
#define USER_SETTING_DEVINFO_PATH           USER_SETTING_PREF_DIR"\\devinfo"

#define USER_SETTING_VER_NUM                (21)

enum {
    INI_SECTION_INTERNAL_CAMERA = 0,
    INI_SECTION_EXTERNAL_CAMERA,
    INI_SECTION_SYSTEM,
    INI_SECTION_WIFI,
    INI_SECTION_GNSS,
    INI_SECTION_IMU,
    INI_SECTION_LED,
    INI_SECTION_API,
    INI_SECTION_NUM
};

enum {
    INI_SECTION_ITEM_INTERNAL_CAMERA_ENABLE = 0,
    INI_SECTION_ITEM_INTERNAL_CAMERA_AUTO_RECORD,
    INI_SECTION_ITEM_INTERNAL_CAMERA_FPS,
    INI_SECTION_ITEM_INTERNAL_CAMERA_MAIN_STREAM_SIZE,
    INI_SECTION_ITEM_INTERNAL_CAMERA_SEC_STREAM_SIZE,
    INI_SECTION_ITEM_INTERNAL_CAMERA_MAIN_STREAM_BITRATE,
    INI_SECTION_ITEM_INTERNAL_CAMERA_SEC_STREAM_BITRATE,
    INI_SECTION_ITEM_INTERNAL_CAMERA_MAIN_STREAM_GOP,
    INI_SECTION_ITEM_INTERNAL_CAMERA_SEC_STREAM_GOP,
    INI_SECTION_ITEM_INTERNAL_CAMERA_IMAGE_ROTATION,
    INI_SECTION_ITEM_INTERNAL_CAMERA_NUM
};

enum {
    INI_SECTION_ITEM_EXTERNAL_CAMERA_ENABLE = 0,
    INI_SECTION_ITEM_EXTERNAL_CAMERA_AUTO_RECORD,
    INI_SECTION_ITEM_EXTERNAL_CAMERA_FPS,
    INI_SECTION_ITEM_EXTERNAL_CAMERA_MAIN_STREAM_SIZE,
    INI_SECTION_ITEM_EXTERNAL_CAMERA_SEC_STREAM_SIZE,
    INI_SECTION_ITEM_EXTERNAL_CAMERA_MAIN_STREAM_BITRATE,
    INI_SECTION_ITEM_EXTERNAL_CAMERA_SEC_STREAM_BITRATE,
    INI_SECTION_ITEM_EXTERNAL_CAMERA_MAIN_STREAM_GOP,
    INI_SECTION_ITEM_EXTERNAL_CAMERA_SEC_STREAM_GOP,
    INI_SECTION_ITEM_EXTERNAL_CAMERA_IMAGE_ROTATION,
    INI_SECTION_ITEM_EXTERNAL_CAMERA_NUM
};

enum {
    INI_SECTION_ITEM_SYSTEM_VER = 0,
    INI_SECTION_ITEM_SYSTEM_AUDIO_VOLUME,
    INI_SECTION_ITEM_SYSTEM_RECORD_SOUND,
    INI_SECTION_ITEM_SYSTEM_LED_ONOFF,
    INI_SECTION_ITEM_SYSTEM_SET_LED_BRIGHTNESS,
    INI_SECTION_ITEM_SYSTEM_IR_BRIGHTNESS,
    INI_SECTION_ITEM_SYSTEM_WATCHDOG_ONOFF,
    INI_SECTION_ITEM_SYSTEM_EVENT_BUFFER_LENGTH,
    INI_SECTION_ITEM_SYSTEM_DEBUG_MODE,
    INI_SECTION_ITEM_SYSTEM_TIME_ZONE,
    INI_SECTION_ITEM_SYSTEM_WATERMARK,
    INI_SECTION_ITEM_SYSTEM_WATERMARK_POS,
    INI_SECTION_ITEM_SYSTEM_SPEED_UNIT,
    INI_SECTION_ITEM_SYSTEM_RTSP_LIVE_CAMERA,
    INI_SECTION_ITEM_SYSTEM_IR_SAMPLING,
    INI_SECTION_ITEM_SYSTEM_IR_THRESHOLD,
    INI_SECTION_ITEM_SYSTEM_MOTION_DETECT,
    INI_SECTION_ITEM_SYSTEM_AWB_MODE,
    INI_SECTION_ITEM_SYSTEM_AE_BIAS,
    INI_SECTION_ITEM_SYSTEM_POWER_ONOFF_SOUND,
    INI_SECTION_ITEM_SYSTEM_NO_ACTIVE_SHUTDOWN_TIME,
    INI_SECTION_ITEM_SYSTEM_USE_24H_MODE,
    INI_SECTION_ITEM_SYSTEM_IMU_RECORD,
    INI_SECTION_ITEM_SYSTEM_GNSS_RECORD,
    INI_SECTION_ITEM_SYSTEM_LINUX_BOOT,
    INI_SECTION_ITEM_SYSTEM_LINUX_CONSOLE,
    INI_SECTION_ITEM_SYSTEM_RTOS_CONSOLE,
    INI_SECTION_ITEM_SYSTEM_USB_MASS_STORAGE,
    INI_SECTION_ITEM_SYSTEM_LED_RTOS_CONTROL,
    INI_SECTION_ITEM_SYSTEM_VIDEO_ENCRYPTION_KEY,    
    INI_SECTION_ITEM_SYSTEM_VIDEO_ENCRYPTION_ENABLE,
    INI_SECTION_ITEM_SYSTEM_VIDEO_ENCRYPTION_DEBUG,
    INI_SECTION_ITEM_SYSTEM_VIDEO_DECRYPTION_KEY,
    INI_SECTION_ITEM_SYSTEM_AUTHORIZATION_TOKEN,
    INI_SECTION_ITEM_SYSTEM_PARKING_LEVEL,
    INI_SECTION_ITEM_SYSTEM_LTE_WAKEUP_ENABLE,
    INI_SECTION_ITEM_SYSTEM_CV_RUN,
    INI_SECTION_ITEM_SYSTEM_PIV,
    INI_SECTION_ITEM_SYSTEM_H265_FORMAT,
    INI_SECTION_ITEM_SYSTEM_NUM
};

enum {
    INI_SECTION_ITEM_WIFI_BOOT_MODE = 0,
    INI_SECTION_ITEM_WIFI_CONNECT_MODE,
    INI_SECTION_ITEM_WIFI_CHANNEL,
    INI_SECTION_ITEM_WIFI_MODE,
    INI_SECTION_ITEM_WIFI_AP_SSID,
    INI_SECTION_ITEM_WIFI_AP_PASSWORD,
    INI_SECTION_ITEM_WIFI_AP_IP,
    INI_SECTION_ITEM_WIFI_STA_SSID,
    INI_SECTION_ITEM_WIFI_STA_PASSWORD,
    INI_SECTION_ITEM_WIFI_P2P_WAIT_TIME,
    INI_SECTION_ITEM_USB_WIFI_BOOT_MODE,
    INI_SECTION_ITEM_USB_WIFI_CHANNEL,
    INI_SECTION_ITEM_USB_WIFI_AP_SSID,
    INI_SECTION_ITEM_USB_WIFI_AP_PASSWORD,
    INI_SECTION_ITEM_USB_WIFI_AP_IP,
    INI_SECTION_ITEM_USB_WIFI_STA_SSID,
    INI_SECTION_ITEM_USB_WIFI_STA_PASSWORD,
    INI_SECTION_ITEM_WIFI_NUM
};

enum {
    INI_SECTION_ITEM_GNSS_UART_BITRATE = 0,
    INI_SECTION_ITEM_GNSS_UART_CHANNEL,
    INI_SECTION_ITEM_GNSS_ID,
    INI_SECTION_ITEM_GNSS_DATARATE,
    INI_SECTION_ITEM_GNSS_NUM
};

enum {
    INI_SECTION_ITEM_IMU_ACCEL_ODR = 0,
    INI_SECTION_ITEM_IMU_ACCEL_RANGE,
    INI_SECTION_ITEM_IMU_GYRO_ODR,
    INI_SECTION_ITEM_IMU_GYRO_RANGE,
    INI_SECTION_ITEM_IMU_AXIS_POLARITY,
    INI_SECTION_ITEM_IMU_NUM
};

enum {
    INI_SECTION_ITEM_LED_R = 0,
    INI_SECTION_ITEM_LED_G,
    INI_SECTION_ITEM_LED_B,
    INI_SECTION_ITEM_LED_NUM
};

enum {
    INI_SECTION_ITEM_API_FILES = 0,
    INI_SECTION_ITEM_API_NUM
};

int user_setting_init(void);
int user_setting_save(void);
int user_setting_to_default(void);
int user_setting_for_hard_reset(void);

#endif//__USER_SETTING_H__

