CVTASK_MODULES =                \
	HighLevelTask           \
	Sink                    \
	MesgPump                \
	Adder                   \
	LogWriter               \
	FileFeeder              \
	IdspFeeder              \
	Profiler                \
	HLLaneDetection         \
	HLObjectTracking        \
	HLVisualOdometry        \
	FastOdARM               \
	JointOdARM              \
	TsdARM                  \
	StereoCalibration       \
	HLMobilenet             \
	HLMobilenetSSD          \
	HLBarriersCurbsDetection
