#!/bin/sh

. /usr/local/share/script/sync_rtc.sh

mkdir -p /tmp/lib /tmp/run /tmp/disk /tmp/log /tmp/ppp
mkdir -p /tmp/fuse /tmp/FL0 /tmp/SD0

#for dnsmasq.leases
mkdir -p /var/lib/misc

#/dev/random does not work
ln -sf /dev/urandom /dev/random

ln -sf /etc/resolv.conf /etc/ppp/resolv.conf

# insmod amba vitual file system
# kernel_ver=$(uname -r)
# insmod lib/modules/$kernel_ver/kernel/fs/ambavfs/ambavfs.ko

mount -t ambafs a: /tmp/FL0
mount -t ambafs c: /tmp/SD0

#enable ipcbind and util_svc daemon
if [ -x /usr/bin/ipcbind ]; then
	/usr/bin/ipcbind -b
	if [ -x /usr/bin/util_svc ]; then
		/usr/bin/util_svc -b
	fi

	if [ -x /usr/bin/camctrlserver ]; then
		/usr/bin/camctrlserver
	fi
fi

#Enable Linux RPC Binder and Amba background Daemons.
if [ -x /usr/bin/rpcbind ]; then
	/usr/bin/rpcbind
	if [ -x /usr/bin/AmbaNetFifoDaemon ]; then
		/usr/bin/AmbaNetFifoDaemon
	fi
	if [ -x /usr/bin/AmbaEventNotifyDaemon ]; then
		/usr/bin/AmbaEventNotifyDaemon
	fi
fi

#for bootup speed, some modules are preloaded before hibernate
if [ -x /usr/local/share/script/preload.sh ]; then
	/usr/local/share/script/preload.sh
fi

if [ -x /usr/local/share/script/bt_preload.sh ]; then
	/usr/local/share/script/bt_preload.sh
fi

#for ar6004 WoWLAN
mount -t debugfs none /sys/kernel/debug/

#login telnet by 'default'
#buildroot will install S50telnet
#telnetd

#syslog
if [ "`grep \"console=ttyS1\" /proc/cmdline`" != "" ]; then
	if [ "`grep quiet /proc/cmdline`" != "" ]; then
		klogd
	fi
	syslogd -O /dev/ttyS1
fi

#install ambacv module
#modprobe ambacv

