obj-y += liblvgl.a


#lv_core
liblvgl-objs := 	 core/lv_group.o \
                     core/lv_indev.o \
                     core/lv_disp.o \
                     core/lv_obj.o \
					 core/lv_event.o \
					 core/lv_indev_scroll.o \
					 core/lv_obj_class.o \
					 core/lv_obj_draw.o \
					 core/lv_obj_pos.o \
					 core/lv_obj_scroll.o \
					 core/lv_obj_style.o \
					 core/lv_obj_style_gen.o \
					 core/lv_obj_tree.o \
					 core/lv_refr.o \
					 core/lv_theme.o

#lv_draw
liblvgl-objs += 	draw/lv_draw_arc.o \
					draw/lv_draw.o \
                    draw/lv_draw_img.o \
                    draw/lv_draw_label.o \
                    draw/lv_draw_line.o \
                    draw/lv_draw_mask.o \
                    draw/lv_draw_rect.o \
                    draw/lv_draw_triangle.o \
                    draw/lv_img_buf.o \
                    draw/lv_img_cache.o \
                    draw/lv_img_decoder.o \
					draw/lv_draw_layer.o \
					draw/lv_draw_transform.o \
					draw/sw/lv_draw_sw.o \
					draw/sw/lv_draw_sw_blend.o \
					draw/sw/lv_draw_sw_gradient.o \
					draw/sw/lv_draw_sw_letter.o \
					draw/sw/lv_draw_sw_polygon.o \
					draw/sw/lv_draw_sw_arc.o \
					draw/sw/lv_draw_sw_dither.o \
					draw/sw/lv_draw_sw_img.o \
					draw/sw/lv_draw_sw_line.o \
					draw/sw/lv_draw_sw_rect.o \
					draw/sw/lv_draw_sw_layer.o \
					draw/sw/lv_draw_sw_transform.o


# #lv_font
liblvgl-objs += 	font/lv_font.o \
                    font/lv_font_fmt_txt.o \
					font/lv_font_loader.o \
					font/lv_font_montserrat_14.o
                    # lv_font/lv_font_montserrat_12.o \
                    # lv_font/lv_font_montserrat_16.o \
                    # lv_font/lv_font_montserrat_18.o \
                    # lv_font/lv_font_montserrat_20.o \
                    # lv_font/lv_font_montserrat_22.o \
                    # lv_font/lv_font_montserrat_24.o \
                    # lv_font/lv_font_montserrat_26.o \
                    # lv_font/lv_font_montserrat_28.o \
                    # lv_font/lv_font_montserrat_30.o \
                    # lv_font/lv_font_montserrat_32.o \
                    # lv_font/lv_font_montserrat_34.o \
                    # lv_font/lv_font_montserrat_36.o \
                    # lv_font/lv_font_montserrat_38.o \
                    # lv_font/lv_font_montserrat_40.o \
                    # lv_font/lv_font_montserrat_42.o \
                    # lv_font/lv_font_montserrat_44.o \
                    # lv_font/lv_font_montserrat_46.o \
                    # lv_font/lv_font_montserrat_48.o \
                    # lv_font/lv_font_montserrat_12_subpx.o \
                    # lv_font/lv_font_montserrat_28_compressed.o \
                    # lv_font/lv_font_unscii_8.o \
                    # lv_font/lv_font_dejavu_16_persian_hebrew.o \
                    # lv_font/lv_font_Josefin_12_Amba.o

liblvgl-objs += font/lv_font_sans_14_Amba.o
liblvgl-objs += font/lv_font_sans_10_Amba.o
liblvgl-objs += font/lv_font_sans_30_Amba.o





#lv_hal
liblvgl-objs += 	hal/lv_hal_disp.o \
                    hal/lv_hal_indev.o \
                    hal/lv_hal_tick.o


#lv_misc
liblvgl-objs += 	misc/lv_anim.o \
                    misc/lv_anim_timeline.o \
                    misc/lv_area.o \
                    misc/lv_async.o \
                    misc/lv_bidi.o \
                    misc/lv_color.o \
                    misc/lv_fs.o \
                    misc/lv_gc.o \
                    misc/lv_ll.o \
                    misc/lv_log.o \
					misc/lv_lru.o \
                    misc/lv_math.o \
                    misc/lv_mem.o \
                    misc/lv_printf.o \
                    misc/lv_style.o \
                    misc/lv_style_gen.o \
                    misc/lv_timer.o \
					misc/lv_tlsf.o \
					misc/lv_txt.o \
					misc/lv_txt_ap.o \
					misc/lv_utils.o \
					misc/lv_templ.o


#lv_widgets
liblvgl-objs += 	widgets/lv_arc.o \
                    widgets/lv_bar.o \
                    widgets/lv_btn.o \
                    widgets/lv_btnmatrix.o \
                    widgets/lv_canvas.o \
                    widgets/lv_checkbox.o \
                    widgets/lv_dropdown.o \
                    widgets/lv_img.o \
                    widgets/lv_label.o \
                    widgets/lv_line.o \
                    widgets/lv_roller.o \
                    widgets/lv_slider.o \
                    widgets/lv_switch.o \
                    widgets/lv_table.o \
                    widgets/lv_textarea.o \
					widgets/lv_objx_templ.o

liblvgl-objs += 	extra/lv_extra.o \
					extra/themes/default/lv_theme_default.o \
					extra/layouts/flex/lv_flex.o \
					extra/layouts/grid/lv_grid.o \
					extra/themes/basic/lv_theme_basic.o \
					extra/themes/mono/lv_theme_mono.o \
					extra/widgets/animimg/lv_animimg.o \
					extra/widgets/calendar/lv_calendar.o \
					extra/widgets/calendar/lv_calendar_header_arrow.o \
					extra/widgets/calendar/lv_calendar_header_dropdown.o \
					extra/widgets/chart/lv_chart.o \
					extra/widgets/colorwheel/lv_colorwheel.o \
					extra/widgets/imgbtn/lv_imgbtn.o \
					extra/widgets/keyboard/lv_keyboard.o \
					extra/widgets/led/lv_led.o \
					extra/widgets/list/lv_list.o \
					extra/widgets/meter/lv_meter.o \
					extra/widgets/msgbox/lv_msgbox.o \
					extra/widgets/span/lv_span.o \
					extra/widgets/spinbox/lv_spinbox.o \
					extra/widgets/spinner/lv_spinner.o \
					extra/widgets/tabview/lv_tabview.o \
					extra/widgets/tileview/lv_tileview.o \
					extra/widgets/win/lv_win.o \
					extra/widgets/menu/lv_menu.o \
					extra/others/monkey/lv_monkey.o \
					extra/others/gridnav/lv_gridnav.o \
					extra/others/snapshot/lv_snapshot.o \
					extra/others/fragment/lv_fragment.o \
					extra/others/fragment/lv_fragment_manager.o \
					extra/others/ime/lv_ime_pinyin.o \
					extra/others/imgfont/lv_imgfont.o \
					extra/others/msg/lv_msg.o

liblvgl-objs += LvglWrap.o



ccflags-y += -I$(srctree)/vendors/foss/lvgl/

ccflags-y += -I$(srctree)/vendors/foss/lvgl/src/ambarella/inc
ccflags-y += -I$(srctree)/vendors/foss/lvgl/src/ambarella/inc/std
ccflags-y += -I$(srctree)/vendors/ambarella/inc


ccflags-y += -I$(srctree)/vendors
ccflags-y += -I$(srctree)/vendors/foss/lvgl/src/lvgl/src
ccflags-y += -I$(srctree)
ccflags-y += -I$(srctree)/svc/comsvc/misc
ccflags-y += -I$(srctree)/svc/comsvc/print


ccflags-y += -Wno-pointer-to-int-cast \
             -Wno-declaration-after-statement

install-files := liblvgl.a










