////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2020 Ambarella, Inc.
////////////////////////////////////////////////////////////////////////////////
// This file and its contents ("Software") are protected
// by intellectual property rights including, without limitation, U.S.
// and/or foreign copyrights.  This Software is also the confidential
// and proprietary information of Ambarella, Inc. and its licensors.
// You may not use, reproduce, disclose, distribute, modify, or
// otherwise prepare derivative works of this Software or any portion
// thereof except pursuant to a signed license agreement or
// nondisclosure agreement with Ambarella, Inc. or its authorized
// affiliates.  In the absence of such an agreement, you agree to
// promptly notify and return this Software to Ambarella, Inc.
//
// THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
// WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL AMBARELLA, INC. OR ITS
// AFFILIATES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; COMPUTER FAILURE OR MALFUNCTION; OR BUSINESS INTERRUPTION)
// HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
// OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////
#ifndef mnet_ssd_adas_flex_pic_prim_split_4_H
#define mnet_ssd_adas_flex_pic_prim_split_4_H

#define vas_gen_header_version                  	7

/* dag name */
#define mnet_ssd_adas_flex_pic_prim_split_4_DAG_NAME 	"mnet_ssd_adas_flex_pic_prim_split_4"

/* VDG file info */
#define mnet_ssd_adas_flex_pic_prim_split_4_vdg_name 	"mnet_ssd_adas_flex_pic_split_4.vdg"

/* VDG DAG memory info */
#define mnet_ssd_adas_flex_pic_prim_split_4_byte_offset 	4294967295	/* 0xffffffff */
#define mnet_ssd_adas_flex_pic_prim_split_4_byte_size 	848	/* 0x00000350 */
#define mnet_ssd_adas_flex_pic_prim_split_4_preferred_dram_xfer_size 	1

/* mnet_ssd_adas_flex_pic_prim_split_4 VMEM info */
#define mnet_ssd_adas_flex_pic_prim_split_4_use_ping_pong_vmem 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_VMEM_start 	4096	/* 0x00001000 */
#define mnet_ssd_adas_flex_pic_prim_split_4_VMEM_end 	1995668	/* 0x001e7394 */
#define mnet_ssd_adas_flex_pic_prim_split_4_image_start 	675024	/* 0x000a4cd0 */
#define mnet_ssd_adas_flex_pic_prim_split_4_image_size 	1321492	/* 0x00142a14 */
#define mnet_ssd_adas_flex_pic_prim_split_4_dagbin_start 	1995668	/* 0x001e7394 */

/* mnet_ssd_adas_flex_pic_prim_split_4 DAG info */
#define mnet_ssd_adas_flex_pic_prim_split_4_estimated_cycles 	2492033

/*******************************************************************************
 * DAG byte offset info for HMB/SMB/VCB and their fields
 * in DAG 'mnet_ssd_adas_flex_pic_prim_split_4' in source file 'mnet_ssd_adas_flex_pic_split_4.vas'
 ******************************************************************************/
/* mnet_ssd_adas_flex_pic_prim_split_4 HMB_input conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_cnngen_demangled_name 	"conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw"
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_is_main_input_output 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_is_constant 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_has_init_data 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_is_variable_scalar 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_ddi_byte_size 	0	/* 0x00000000 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_is_twelve_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_byte_offset 	0	/* 0x00000000 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_vbase_byte_offset 	4	/* 0x00000004 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_dbase_byte_offset 	28	/* 0x0000001c */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_dpitchm1_byte_offset 	32	/* 0x00000020 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_dpitchm1_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_vwidth_minus_one_byte_offset 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_vheight_minus_one_byte_offset 	18	/* 0x00000012 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_drotate_bit_offset 	198	/* 0x000000c6 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_hflip_bit_offset 	199	/* 0x000000c7 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_vflip_bit_offset 	200	/* 0x000000c8 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_dflip_bit_offset 	201	/* 0x000000c9 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_pflip_bit_offset 	202	/* 0x000000ca */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_W 	10
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_H 	10
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_D 	1024
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_P 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_data_num_bytes 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_denable 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_dpitch_num_bytes 	32
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_dram_format 	3
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_vp_interleave_mode 	2
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_tile_width 	4
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_vmem_buffer_num_bytes 	163840
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_dram_size_num_bytes 	163840
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_sign 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_datasize 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_expoffset 	8
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_expbits 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_drotate 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_hflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_vflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_dflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__dw_____bn___muli___110_____bn_____scale_mul_____scale___relu6__dw_pflip 	0

/* mnet_ssd_adas_flex_pic_prim_split_4 HMB_input conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_cnngen_demangled_name 	"conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep"
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_is_main_input_output 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_is_constant 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_has_init_data 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_is_variable_scalar 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_ddi_byte_size 	0	/* 0x00000000 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_is_twelve_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_byte_offset 	40	/* 0x00000028 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_vbase_byte_offset 	44	/* 0x0000002c */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_dbase_byte_offset 	68	/* 0x00000044 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_dpitchm1_byte_offset 	72	/* 0x00000048 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_dpitchm1_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_vwidth_minus_one_byte_offset 	56	/* 0x00000038 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_vheight_minus_one_byte_offset 	58	/* 0x0000003a */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_drotate_bit_offset 	518	/* 0x00000206 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_hflip_bit_offset 	519	/* 0x00000207 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_vflip_bit_offset 	520	/* 0x00000208 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_dflip_bit_offset 	521	/* 0x00000209 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_pflip_bit_offset 	522	/* 0x0000020a */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_W 	19
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_H 	19
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_D 	512
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_P 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_data_num_bytes 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_denable 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_dpitch_num_bytes 	32
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_dram_format 	3
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_vp_interleave_mode 	2
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_tile_width 	4
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_vmem_buffer_num_bytes 	294912
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_dram_size_num_bytes 	311296
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_sign 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_datasize 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_expoffset 	7
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_expbits 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_drotate 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_hflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_vflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_dflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5__sep_____bn___muli___96_____bn_____scale_mul_____scale___relu5_5__sep_pflip 	0

/* mnet_ssd_adas_flex_pic_prim_split_4 SMB_input __pvcn_140004_ */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__cnngen_demangled_name 	"__pvcn_140004_"
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__is_constant 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__has_init_data 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__is_variable_scalar 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__is_twelve_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__byte_offset 	80	/* 0x00000050 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__vbase_byte_offset 	84	/* 0x00000054 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__dbase_byte_offset 	108	/* 0x0000006c */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__dpitchm1_byte_offset 	112	/* 0x00000070 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__dpitchm1_bsize 	32	/* 0x00000020 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__W 	489796
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__H 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__D 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__P 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__data_num_bytes 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__denable 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__dpitch_num_bytes 	489824
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__dram_format 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__vp_interleave_mode 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__tile_width 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__vmem_buffer_num_bytes 	489796
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140004__dram_size_num_bytes 	489824

/* mnet_ssd_adas_flex_pic_prim_split_4 SMB_input __pvcn_140007_ */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__cnngen_demangled_name 	"__pvcn_140007_"
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__is_constant 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__has_init_data 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__is_variable_scalar 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__is_twelve_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__byte_offset 	116	/* 0x00000074 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__vbase_byte_offset 	120	/* 0x00000078 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__dbase_byte_offset 	144	/* 0x00000090 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__dpitchm1_byte_offset 	148	/* 0x00000094 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__dpitchm1_bsize 	32	/* 0x00000020 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__W 	488960
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__H 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__D 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__P 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__data_num_bytes 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__denable 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__dpitch_num_bytes 	488960
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__dram_format 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__vp_interleave_mode 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__tile_width 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__vmem_buffer_num_bytes 	488960
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140007__dram_size_num_bytes 	488960

/* mnet_ssd_adas_flex_pic_prim_split_4 SMB_input __pvcn_140005_ */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__cnngen_demangled_name 	"__pvcn_140005_"
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__is_constant 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__has_init_data 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__is_variable_scalar 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__is_twelve_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__byte_offset 	156	/* 0x0000009c */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__vbase_byte_offset 	160	/* 0x000000a0 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__dbase_byte_offset 	184	/* 0x000000b8 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__dpitchm1_byte_offset 	188	/* 0x000000bc */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__dpitchm1_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__W 	4332
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__H 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__D 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__P 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__data_num_bytes 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__denable 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__dpitch_num_bytes 	4352
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__dram_format 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__vp_interleave_mode 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__tile_width 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__vmem_buffer_num_bytes 	4332
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140005__dram_size_num_bytes 	4352

/* mnet_ssd_adas_flex_pic_prim_split_4 SMB_input __pvcn_140008_ */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__cnngen_demangled_name 	"__pvcn_140008_"
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__is_constant 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__has_init_data 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__is_variable_scalar 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__is_twelve_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__byte_offset 	196	/* 0x000000c4 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__vbase_byte_offset 	200	/* 0x000000c8 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__dbase_byte_offset 	224	/* 0x000000e0 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__dpitchm1_byte_offset 	228	/* 0x000000e4 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__dpitchm1_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__W 	4328
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__H 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__D 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__P 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__data_num_bytes 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__denable 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__dpitch_num_bytes 	4352
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__dram_format 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__vp_interleave_mode 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__tile_width 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__vmem_buffer_num_bytes 	4328
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_140008__dram_size_num_bytes 	4352

/* mnet_ssd_adas_flex_pic_prim_split_4 SMB_input __pvcn_2549_ */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__cnngen_demangled_name 	"__pvcn_2549_"
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__is_constant 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__has_init_data 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__is_variable_scalar 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__is_twelve_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__byte_offset 	236	/* 0x000000ec */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__vbase_byte_offset 	240	/* 0x000000f0 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__dbase_byte_offset 	264	/* 0x00000108 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__dpitchm1_byte_offset 	268	/* 0x0000010c */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__dpitchm1_bsize 	32	/* 0x00000020 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__W 	313184
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__H 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__D 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__P 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__data_num_bytes 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__denable 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__dpitch_num_bytes 	313184
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__dram_format 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__vp_interleave_mode 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__tile_width 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__vmem_buffer_num_bytes 	313184
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2549__dram_size_num_bytes 	313184

/* mnet_ssd_adas_flex_pic_prim_split_4 SMB_input __pvcn_2550_ */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__cnngen_demangled_name 	"__pvcn_2550_"
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__is_constant 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__has_init_data 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__is_variable_scalar 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__is_twelve_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__byte_offset 	276	/* 0x00000114 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__vbase_byte_offset 	280	/* 0x00000118 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__dbase_byte_offset 	304	/* 0x00000130 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__dpitchm1_byte_offset 	308	/* 0x00000134 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__dpitchm1_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__W 	2800
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__H 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__D 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__P 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__data_num_bytes 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__denable 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__dpitch_num_bytes 	2816
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__dram_format 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__vp_interleave_mode 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__tile_width 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__vmem_buffer_num_bytes 	2800
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2550__dram_size_num_bytes 	2816

/* mnet_ssd_adas_flex_pic_prim_split_4 SMB_input __pvcn_2553_ */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__cnngen_demangled_name 	"__pvcn_2553_"
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__is_constant 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__has_init_data 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__is_variable_scalar 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__is_twelve_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__byte_offset 	316	/* 0x0000013c */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__vbase_byte_offset 	320	/* 0x00000140 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__dbase_byte_offset 	344	/* 0x00000158 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__dpitchm1_byte_offset 	348	/* 0x0000015c */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__dpitchm1_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__W 	16896
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__H 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__D 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__P 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__data_num_bytes 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__denable 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__dpitch_num_bytes 	16896
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__dram_format 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__vp_interleave_mode 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__tile_width 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__vmem_buffer_num_bytes 	16896
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2553__dram_size_num_bytes 	16896

/* mnet_ssd_adas_flex_pic_prim_split_4 SMB_input __pvcn_2554_ */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__cnngen_demangled_name 	"__pvcn_2554_"
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__is_constant 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__has_init_data 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__is_variable_scalar 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__is_twelve_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__byte_offset 	356	/* 0x00000164 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__vbase_byte_offset 	360	/* 0x00000168 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__dbase_byte_offset 	384	/* 0x00000180 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__dpitchm1_byte_offset 	388	/* 0x00000184 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__dpitchm1_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__W 	348
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__H 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__D 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__P 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__data_num_bytes 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__denable 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__dpitch_num_bytes 	352
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__dram_format 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__vp_interleave_mode 	0
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__tile_width 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__vmem_buffer_num_bytes 	348
#define mnet_ssd_adas_flex_pic_prim_split_4___pvcn_2554__dram_size_num_bytes 	352

/* mnet_ssd_adas_flex_pic_prim_split_4 VCB conv6__sep_____bn___muli___114_____bn_____scale_mul_____scale___relu6__sep */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__sep_____bn___muli___114_____bn_____scale_mul_____scale___relu6__sep_cnngen_demangled_name 	"conv6__sep_____bn___muli___114_____bn_____scale_mul_____scale___relu6__sep"
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__sep_____bn___muli___114_____bn_____scale_mul_____scale___relu6__sep_is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__sep_____bn___muli___114_____bn_____scale_mul_____scale___relu6__sep_is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__sep_____bn___muli___114_____bn_____scale_mul_____scale___relu6__sep_is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__sep_____bn___muli___114_____bn_____scale_mul_____scale___relu6__sep_is_twelve_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__sep_____bn___muli___114_____bn_____scale_mul_____scale___relu6__sep_byte_offset 	396	/* 0x0000018c */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__sep_____bn___muli___114_____bn_____scale_mul_____scale___relu6__sep_vbase_byte_offset 	404	/* 0x00000194 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6__sep_____bn___muli___114_____bn_____scale_mul_____scale___relu6__sep_vmem_buffer_num_bytes 	121560

/* mnet_ssd_adas_flex_pic_prim_split_4 HMB_output conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173___ */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____cnngen_demangled_name 	"conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173___"
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____is_main_input_output 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____is_twelve_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____byte_offset 	496	/* 0x000001f0 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____vbase_byte_offset 	500	/* 0x000001f4 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____dbase_byte_offset 	524	/* 0x0000020c */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____dpitchm1_byte_offset 	528	/* 0x00000210 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____dpitchm1_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____vwidth_minus_one_byte_offset 	512	/* 0x00000200 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____vheight_minus_one_byte_offset 	514	/* 0x00000202 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____vheight_minus_one_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____drotate_bit_offset 	4166	/* 0x00001046 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____hflip_bit_offset 	4167	/* 0x00001047 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____vflip_bit_offset 	4168	/* 0x00001048 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____dflip_bit_offset 	4169	/* 0x00001049 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____pflip_bit_offset 	4170	/* 0x0000104a */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____W 	10
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____H 	10
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____D 	322
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____P 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____data_num_bytes 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____denable 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____dpitch_num_bytes 	32
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____dram_format 	3
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____vp_interleave_mode 	2
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____tile_width 	4
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____vmem_buffer_num_bytes 	39928
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____dram_size_num_bytes 	51520
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____sign 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____datasize 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____expoffset 	3
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____expbits 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____drotate 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____hflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____vflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____dflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_conf___conv2i___117______7_1_____bn___muli___120_____bn_____scale_mul_____scale___loc___conv2i___173____pflip 	0

/* mnet_ssd_adas_flex_pic_prim_split_4 HMB_output conv6_mbox_loc_flat */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_cnngen_demangled_name 	"conv6_mbox_loc_flat"
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_is_main_input_output 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_is_twelve_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_byte_offset 	568	/* 0x00000238 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_vbase_byte_offset 	572	/* 0x0000023c */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_dbase_byte_offset 	592	/* 0x00000250 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_dpitchm1_byte_offset 	596	/* 0x00000254 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_dpitchm1_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_vwidth_minus_one_byte_offset 	584	/* 0x00000248 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_drotate_bit_offset 	4710	/* 0x00001266 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_hflip_bit_offset 	4711	/* 0x00001267 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_vflip_bit_offset 	4712	/* 0x00001268 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_dflip_bit_offset 	4713	/* 0x00001269 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_pflip_bit_offset 	4714	/* 0x0000126a */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_W 	2400
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_H 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_D 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_P 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_data_num_bytes 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_denable 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_dpitch_num_bytes 	32
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_dram_format 	3
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_vp_interleave_mode 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_tile_width 	4
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_vmem_buffer_num_bytes 	2400
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_dram_size_num_bytes 	2400
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_sign 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_datasize 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_expoffset 	3
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_expbits 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_drotate 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_hflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_vflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_dflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv6_mbox_loc_flat_pflip 	0

/* mnet_ssd_adas_flex_pic_prim_split_4 HMB_output conv5_5_mbox_conf___conv2i___99______loc___conv2i___171___ */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____cnngen_demangled_name 	"conv5_5_mbox_conf___conv2i___99______loc___conv2i___171___"
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____is_main_input_output 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____is_twelve_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____byte_offset 	616	/* 0x00000268 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____vbase_byte_offset 	620	/* 0x0000026c */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____dbase_byte_offset 	644	/* 0x00000284 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____dpitchm1_byte_offset 	648	/* 0x00000288 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____dpitchm1_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____vwidth_minus_one_byte_offset 	632	/* 0x00000278 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____vheight_minus_one_byte_offset 	634	/* 0x0000027a */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____vheight_minus_one_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____drotate_bit_offset 	5126	/* 0x00001406 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____hflip_bit_offset 	5127	/* 0x00001407 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____vflip_bit_offset 	5128	/* 0x00001408 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____dflip_bit_offset 	5129	/* 0x00001409 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____pflip_bit_offset 	5130	/* 0x0000140a */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____W 	19
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____H 	19
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____D 	33
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____P 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____data_num_bytes 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____denable 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____dpitch_num_bytes 	32
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____dram_format 	3
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____vp_interleave_mode 	2
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____tile_width 	4
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____vmem_buffer_num_bytes 	11088
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____dram_size_num_bytes 	20064
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____sign 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____datasize 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____expoffset 	3
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____expbits 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____drotate 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____hflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____vflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____dflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_conf___conv2i___99______loc___conv2i___171____pflip 	0

/* mnet_ssd_adas_flex_pic_prim_split_4 HMB_output conv5_5_mbox_loc_flat */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_cnngen_demangled_name 	"conv5_5_mbox_loc_flat"
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_is_main_input_output 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_is_twelve_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_byte_offset 	684	/* 0x000002ac */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_vbase_byte_offset 	688	/* 0x000002b0 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_dbase_byte_offset 	708	/* 0x000002c4 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_dpitchm1_byte_offset 	712	/* 0x000002c8 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_dpitchm1_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_vwidth_minus_one_byte_offset 	700	/* 0x000002bc */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_drotate_bit_offset 	5638	/* 0x00001606 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_hflip_bit_offset 	5639	/* 0x00001607 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_vflip_bit_offset 	5640	/* 0x00001608 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_dflip_bit_offset 	5641	/* 0x00001609 */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_pflip_bit_offset 	5642	/* 0x0000160a */
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_W 	4332
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_H 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_D 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_P 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_data_num_bytes 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_denable 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_dpitch_num_bytes 	32
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_dram_format 	3
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_vp_interleave_mode 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_tile_width 	4
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_vmem_buffer_num_bytes 	4336
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_dram_size_num_bytes 	4352
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_sign 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_datasize 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_expoffset 	3
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_expbits 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_drotate 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_hflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_vflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_dflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_conv5_5_mbox_loc_flat_pflip 	0

/* mnet_ssd_adas_flex_pic_prim_split_4 HMB_output relu7_1 */
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_cnngen_demangled_name 	"relu7_1"
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_is_main_input_output 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_is_twelve_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_byte_offset 	732	/* 0x000002dc */
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_vbase_byte_offset 	736	/* 0x000002e0 */
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_dbase_byte_offset 	760	/* 0x000002f8 */
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_dpitchm1_byte_offset 	764	/* 0x000002fc */
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_dpitchm1_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_vwidth_minus_one_byte_offset 	748	/* 0x000002ec */
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_vheight_minus_one_byte_offset 	750	/* 0x000002ee */
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_drotate_bit_offset 	6054	/* 0x000017a6 */
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_hflip_bit_offset 	6055	/* 0x000017a7 */
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_vflip_bit_offset 	6056	/* 0x000017a8 */
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_dflip_bit_offset 	6057	/* 0x000017a9 */
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_pflip_bit_offset 	6058	/* 0x000017aa */
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_W 	10
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_H 	10
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_D 	256
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_P 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_data_num_bytes 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_denable 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_dpitch_num_bytes 	32
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_dram_format 	3
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_vp_interleave_mode 	2
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_tile_width 	4
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_vmem_buffer_num_bytes 	32768
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_dram_size_num_bytes 	40960
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_sign 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_datasize 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_expoffset 	6
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_expbits 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_drotate 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_hflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_vflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_dflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_relu7_1_pflip 	0

/* mnet_ssd_adas_flex_pic_prim_split_4 SMB_output split_4__vas_created_terminate__v0 */
#define mnet_ssd_adas_flex_pic_prim_split_4_split_4__vas_created_terminate__v0_cnngen_demangled_name 	"split_4__vas_created_terminate__v0"
#define mnet_ssd_adas_flex_pic_prim_split_4_split_4__vas_created_terminate__v0_is_main_input_output 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_split_4__vas_created_terminate__v0_is_bitvector 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_split_4__vas_created_terminate__v0_is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_split_4__vas_created_terminate__v0_is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_split_4__vas_created_terminate__v0_is_twelve_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_split_4__vas_created_terminate__v0_byte_offset 	772	/* 0x00000304 */
#define mnet_ssd_adas_flex_pic_prim_split_4_split_4__vas_created_terminate__v0_vbase_byte_offset 	776	/* 0x00000308 */
#define mnet_ssd_adas_flex_pic_prim_split_4_split_4__vas_created_terminate__v0_W 	256
#define mnet_ssd_adas_flex_pic_prim_split_4_split_4__vas_created_terminate__v0_H 	3
#define mnet_ssd_adas_flex_pic_prim_split_4_split_4__vas_created_terminate__v0_D 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_split_4__vas_created_terminate__v0_P 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_split_4__vas_created_terminate__v0_data_num_bytes 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_split_4__vas_created_terminate__v0_denable 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_split_4__vas_created_terminate__v0_dram_format 	0
#define mnet_ssd_adas_flex_pic_prim_split_4_split_4__vas_created_terminate__v0_vp_interleave_mode 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_split_4__vas_created_terminate__v0_tile_width 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_split_4__vas_created_terminate__v0_tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_4_split_4__vas_created_terminate__v0_vmem_buffer_num_bytes 	96


#endif /* mnet_ssd_adas_flex_pic_prim_split_4_H */
