#!/bin/sh

case "$1" in
  start)
        /usr/local/share/script/bt_start.sh &
        ;;
  stop)
        /usr/local/share/script/bt_stop.sh &
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
esac

exit $?
