# For bootstrap
libbsp_$(AMBA_BSP_NAME)-objs += $(BSP_PATH)/AmbaBST_UserConfig.o \
                                $(BSP_PATH)/AmbaBST_NAND_Generic.o

ifdef CONFIG_CV25_LPDDR4_MT53D512M32D2DS_840MHZ
libbsp_$(AMBA_BSP_NAME)-objs += $(BSP_PATH)/AmbaLPDDR4_MT53D512M32D2DS_840Mhz.o
else
ifdef CONFIG_CV25_LPDDR4_MT53D512M32D2DS_1392MHZ
libbsp_$(AMBA_BSP_NAME)-objs += $(BSP_PATH)/AmbaLPDDR4_MT53D512M32D2DS_1392Mhz.o
else
ifdef CONFIG_CV25_LPDDR4_MT53D512M32D2DS_1596MHZ
libbsp_$(AMBA_BSP_NAME)-objs += $(BSP_PATH)/AmbaLPDDR4_MT53D512M32D2DS_1596Mhz.o
else
ifdef CONFIG_CV25_LPDDR4_MT53D512M32D2DS_1200MHZ
libbsp_$(AMBA_BSP_NAME)-objs += $(BSP_PATH)/AmbaLPDDR4_MT53D512M32D2DS_1200Mhz.o
else
ifdef CONFIG_CV25_LPDDR4_MT53D512M32D2DS_1800MHZ
libbsp_$(AMBA_BSP_NAME)-objs += $(BSP_PATH)/AmbaLPDDR4_MT53D512M32D2DS_1800Mhz.o
endif
endif
endif
endif
endif

# For bootloader
libbsp_$(AMBA_BSP_NAME)-objs += $(BSP_PATH)/AmbaUserGpioConfig.o             \
                                $(BSP_PATH)/AmbaUserDefinedPreBoot.o         \
                                $(BSP_PATH)/AmbaNAND_MT29F4G08ABADAH4.o

ifeq ($(CONFIG_SVC_APPS_ICAM),)
libbsp_$(AMBA_BSP_NAME)-objs += $(BSP_PATH)/AmbaUserNandPartition.o
endif
