FLEXIBIN_LIST = Accelerator/resizeY_u8_420_640x360_1280x720.bin
FLEXIBIN_LIST += Accelerator/resizeY_u8_420_1280x720_640x360.bin
FLEXIBIN_LIST += Accelerator/resizeUV_u8_420_640x360_1280x720.bin
FLEXIBIN_LIST += Accelerator/resizeUV_u8_420_1280x720_640x360.bin

FLEXIBIN_LIST += Accelerator/divide_u8_2pow14.bin
FLEXIBIN_LIST += Accelerator/divide_u8_2pow16.bin
FLEXIBIN_LIST += Accelerator/divide_u8_2pow18.bin
FLEXIBIN_LIST += Accelerator/divide_s16_2pow13.bin
FLEXIBIN_LIST += Accelerator/divide_s16_2pow15.bin
FLEXIBIN_LIST += Accelerator/divide_s16_2pow17.bin
FLEXIBIN_LIST += Accelerator/divide_u16_2pow13.bin
FLEXIBIN_LIST += Accelerator/divide_u16_2pow15.bin
FLEXIBIN_LIST += Accelerator/divide_u16_2pow17.bin

FLEXIBIN_LIST += Accelerator/and_u8_2pow15.bin
FLEXIBIN_LIST += Accelerator/and_u8_2pow17.bin
FLEXIBIN_LIST += Accelerator/and_u8_2pow19.bin

FLEXIBIN_LIST += Accelerator/cmp_grt_s8_2pow15.bin
FLEXIBIN_LIST += Accelerator/cmp_grt_s8_2pow17.bin
FLEXIBIN_LIST += Accelerator/cmp_grt_s8_2pow19.bin

FLEXIBIN_LIST += Accelerator/cmp_neq_u8_2pow15.bin
FLEXIBIN_LIST += Accelerator/cmp_neq_u8_2pow17.bin
FLEXIBIN_LIST += Accelerator/cmp_neq_u8_2pow19.bin
FLEXIBIN_LIST += Accelerator/cmp_neq_u16_2pow14.bin
FLEXIBIN_LIST += Accelerator/cmp_neq_u16_2pow16.bin
FLEXIBIN_LIST += Accelerator/cmp_neq_u16_2pow18.bin
FLEXIBIN_LIST += Accelerator/cmp_neq_u32_2pow13.bin
FLEXIBIN_LIST += Accelerator/cmp_neq_u32_2pow15.bin
FLEXIBIN_LIST += Accelerator/cmp_neq_u32_2pow17.bin

FLEXIBIN_LIST += Accelerator/minmaxloc_u8_1280x720.bin
FLEXIBIN_LIST += Accelerator/minmaxloc_u16_1280x720.bin

FLEXIBIN_LIST += Accelerator/thres_binary_f32_2pow13.bin
FLEXIBIN_LIST += Accelerator/thres_binary_f32_2pow17.bin
FLEXIBIN_LIST += Accelerator/thres_binary_u8_2pow14.bin
FLEXIBIN_LIST += Accelerator/thres_binary_u8_2pow18.bin
FLEXIBIN_LIST += Accelerator/thres_tozero_f32_2pow13.bin
FLEXIBIN_LIST += Accelerator/thres_tozero_f32_2pow17.bin

FLEXIBIN_LIST += Accelerator/erode_u8_640x480.bin

FLEXIBIN_LIST += Accelerator/reduce_avg_h_u8_1280x720.bin
FLEXIBIN_LIST += Accelerator/reduce_sum_h_u8_1280x720.bin
FLEXIBIN_LIST += Accelerator/reduce_min_w_u8_1280x720.bin
FLEXIBIN_LIST += Accelerator/reduce_max_w_u8_1280x720.bin
FLEXIBIN_LIST += Accelerator/split_u8_1280x720x3.bin

FLEXIBIN_LIST += Accelerator/transform_u8_640x480.bin

FLEXIBIN_LIST += Accelerator/dilate_u8_640x480.bin
FLEXIBIN_LIST += Accelerator/mix_channels_u8_640x480.bin
FLEXIBIN_LIST += Accelerator/merge_u8_1280x720x3.bin

FLEXIBIN_LIST += Accelerator/divide_f32_pad32_46x54.bin

FLEXIBIN_LIST += Accelerator/log8u_2paw19.bin
FLEXIBIN_LIST += Accelerator/log8u_2paw17.bin
FLEXIBIN_LIST += Accelerator/log8u_2paw15.bin

FLEXIBIN_LIST += Accelerator/conv8u_640x480_k9x9.bin
FLEXIBIN_LIST += Accelerator/conv8u_1280x720_k9x9.bin

FLEXIBIN_LIST += Accelerator/find_nz_u8_320x180.bin
FLEXIBIN_LIST += Accelerator/yuv2rgb_u8_1280x720.bin

FLEXIBIN_LIST += Accelerator/warp_rotate_uv_640x480.bin
FLEXIBIN_LIST += Accelerator/warp_rotate_y_640x480.bin
FLEXIBIN_LIST += Accelerator/scale_OSD.bin