// SPDX-License-Identifier: BSD-2-Clause
/*
 * Copyright (c) 2019, Ambarella Inc. All rights reserved.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef __SMC_DEFINE_H__
#define __SMC_DEFINE_H__

/*
 * SiP Service Calls for OTP access
 * should keep sync with ambarella_smc.h
 *
 */

#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_GET_UNIQUE_ID		0x0501
#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_GET_PUKEY			0x0503
#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_SET_PUKEY			0x0504
#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_GET_CUSTOMER_ID		0x0505
#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_SET_CUSTOMER_ID		0x0506
#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_GET_COUNTER			0x0507
#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_ADD_COUNTER		0x0508
#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_PERMANENTLY_ENABLE_SECURE_BOOT	0x0509

#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_GET_HUK				0x520
#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_SET_HUK_NONCE		0x521
#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_GET_AES_KEY			0x523
#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_SET_AES_KEY			0x524
#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_GET_ECC_KEY			0x525
#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_SET_ECC_KEY			0x526
#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_GET_USR_SLOT_G0		0x527
#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_SET_USR_SLOT_G0		0x528
#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_GET_USR_SLOT_G1		0x529
#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_SET_USR_SLOT_G1		0x52a
#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_REVOKE_KEY				0x52b

#define OPTEE_SMC_FUNCID_AMBA_SIP_GET_TEST_REGION				0x52d
#define OPTEE_SMC_FUNCID_AMBA_SIP_SET_TEST_REGION				0x52e
#define OPTEE_SMC_FUNCID_AMBA_SIP_EN_ANTI_ROLLBACK			0x52f

#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_QUERY_OTP_SETTING		0x530
#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_SET_JTAG_EFUSE			0x531
#define OPTEE_SMC_FUNCID_AMBA_SIP_OTP_LOCK_ZONA_A			0x532
#define OPTEE_SMC_FUNCID_AMBA_SIP_LOCK_PUKEY					0x533
#define OPTEE_SMC_FUNCID_AMBA_SIP_GET_USR_DATA_G0				0x534
#define OPTEE_SMC_FUNCID_AMBA_SIP_SET_USR_DATA_G0				0x535

#define OPTEE_SMC_FUNCID_AMBA_SIP_GET_SYSCONFIG				0x538
#define OPTEE_SMC_FUNCID_AMBA_SIP_SET_SYSCONFIG				0x539
#define OPTEE_SMC_FUNCID_AMBA_SIP_GET_CST_SEED					0x53a
#define OPTEE_SMC_FUNCID_AMBA_SIP_GET_CST_CUK					0x53b
#define OPTEE_SMC_FUNCID_AMBA_SIP_SET_CST_SEED_CUK			0x53c
#define OPTEE_SMC_FUNCID_AMBA_SIP_GET_USR_CUK					0x53d
#define OPTEE_SMC_FUNCID_AMBA_SIP_SET_USR_CUK					0x53e
#define OPTEE_SMC_FUNCID_AMBA_SIP_DIS_SECURE_USB_BOOT		0x53f

#define OPTEE_SMC_FUNCID_AMBA_SIP_GET_BST_VER					0x540
#define OPTEE_SMC_FUNCID_AMBA_SIP_INCREASE_BST_VER			0x541

#define OPTEE_SMC_FUNCID_AMBA_SIP_GET_MISC_CONFIG			0x542
#define OPTEE_SMC_FUNCID_AMBA_SIP_SET_MISC_CONFIG			0x543


#define OPTEE_AMBA_SIP_OTP_GET_UNIQUE_ID \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_GET_UNIQUE_ID)

#define OPTEE_AMBA_SIP_OTP_GET_PUKEY \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_GET_PUKEY)

#define OPTEE_AMBA_SIP_OTP_SET_PUKEY \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_SET_PUKEY)

#define OPTEE_AMBA_SIP_OTP_GET_CUSTOMER_ID \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_GET_CUSTOMER_ID)

#define OPTEE_AMBA_SIP_OTP_SET_CUSTOMER_ID \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_SET_CUSTOMER_ID)

#define OPTEE_AMBA_SIP_OTP_GET_COUNTER \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_GET_COUNTER)

#define OPTEE_AMBA_SIP_OTP_ADD_COUNTER \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_ADD_COUNTER)

#define OPTEE_AMBA_SIP_OTP_PERMANENTLY_ENABLE_SECURE_BOOT \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_PERMANENTLY_ENABLE_SECURE_BOOT)

#define OPTEE_AMBA_SIP_OTP_GET_HUK \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_GET_HUK)

#define OPTEE_AMBA_SIP_OTP_SET_HUK_NONCE \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_SET_HUK_NONCE)

#define OPTEE_AMBA_SIP_OTP_GET_AES_KEY \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_GET_AES_KEY)

#define OPTEE_AMBA_SIP_OTP_SET_AES_KEY \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_SET_AES_KEY)

#define OPTEE_AMBA_SIP_OTP_GET_ECC_KEY \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_GET_ECC_KEY)

#define OPTEE_AMBA_SIP_OTP_SET_ECC_KEY \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_SET_ECC_KEY)

#define OPTEE_AMBA_SIP_OTP_GET_USR_SLOT_G0 \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_GET_USR_SLOT_G0)

#define OPTEE_AMBA_SIP_OTP_SET_USR_SLOT_G0 \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_SET_USR_SLOT_G0)

#define OPTEE_AMBA_SIP_OTP_GET_USR_SLOT_G1 \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_GET_USR_SLOT_G1)

#define OPTEE_AMBA_SIP_OTP_SET_USR_SLOT_G1 \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_SET_USR_SLOT_G1)

#define OPTEE_AMBA_SIP_OTP_REVOKE_KEY \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_REVOKE_KEY)

#define OPTEE_AMBA_SIP_GET_TEST_REGION \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_GET_TEST_REGION)

#define OPTEE_AMBA_SIP_SET_TEST_REGION \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_SET_TEST_REGION)

#define OPTEE_AMBA_SIP_EN_ANTI_ROLLBACK \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_EN_ANTI_ROLLBACK)


#define OPTEE_AMBA_SIP_OTP_QUERY_OTP_SETTING \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_QUERY_OTP_SETTING)

#define OPTEE_AMBA_SIP_OTP_SET_JTAG_EFUSE \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_SET_JTAG_EFUSE)

#define OPTEE_AMBA_SIP_OTP_LOCK_ZONA_A \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_OTP_LOCK_ZONA_A)

#define OPTEE_AMBA_SIP_OTP_LOCK_PUKEY \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_LOCK_PUKEY)

#define OPTEE_AMBA_SIP_OTP_GET_USR_DATA_G0 \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_GET_USR_DATA_G0)

#define OPTEE_AMBA_SIP_OTP_SET_USR_DATA_G0 \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_SET_USR_DATA_G0)

#define OPTEE_AMBA_SIP_OTP_GET_SYSCONFIG \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_GET_SYSCONFIG)

#define OPTEE_AMBA_SIP_OTP_SET_SYSCONFIG \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_SET_SYSCONFIG)

#define OPTEE_AMBA_SIP_OTP_GET_CST_SEED \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_GET_CST_SEED)

#define OPTEE_AMBA_SIP_OTP_GET_CST_CUK \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_GET_CST_CUK)

#define OPTEE_AMBA_SIP_OTP_SET_CST_SEED_CUK \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_SET_CST_SEED_CUK)

#define OPTEE_AMBA_SIP_OTP_GET_USR_CUK \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_GET_USR_CUK)

#define OPTEE_AMBA_SIP_OTP_SET_USR_CUK \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_SET_USR_CUK)

#define OPTEE_AMBA_SIP_OTP_DIS_SECURE_USB_BOOT \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_DIS_SECURE_USB_BOOT)

#define OPTEE_AMBA_SIP_OTP_GET_BST_VER \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_GET_BST_VER)

#define OPTEE_AMBA_SIP_OTP_INCREASE_BST_VER \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_INCREASE_BST_VER)

#define OPTEE_AMBA_SIP_OTP_GET_MISC_CONFIG \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_GET_MISC_CONFIG)

#define OPTEE_AMBA_SIP_OTP_SET_MISC_CONFIG \
	OPTEE_SMC_CALL_VAL(OPTEE_SMC_64, OPTEE_SMC_FAST_CALL, \
			   OPTEE_SMC_OWNER_SIP, \
			   OPTEE_SMC_FUNCID_AMBA_SIP_SET_MISC_CONFIG)

#endif /* __SMC_DEFINE_H__ */

