#!/bin/sh
#
# Init Strawberry ...
#

if [ -f /etc/ambarella.conf ]; then
	. /etc/ambarella.conf
fi

install_drivers()
{
	kernel_ver=$(uname -r)

	#Install I2C module
	modprobe i2c-dev

	#Install SPI module
	modprobe spi_ambarella
	modprobe spidev

	#Install PWM module
	modprobe pwm-ambarella
	modprobe pwm_bl

	#Install ADC module
	modprobe ambarella_adc

	#Install ambad
	modprobe ambad
}

start()
{
	install_drivers

}

stop()
{
	kernel_ver=$(uname -r)
}

restart()
{
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?

