////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2020 Ambarella International LP
////////////////////////////////////////////////////////////////////////////////
// This file and its contents ("Software") are protected by intellectual
// property rights including, without limitation, U.S. and/or foreign
// copyrights. This Software is also the confidential and proprietary
// information of Ambarella International LP and its licensors. You may not use,
// reproduce, disclose, distribute, modify, or otherwise prepare derivative
// works of this Software or any portion thereof except pursuant to a signed
// license agreement or nondisclosure agreement with Ambarella International LP
// or its authorized affiliates. In the absence of such an agreement, you agree
// to promptly notify and return this Software to Ambarella International LP.
//
// THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL AMBARELLA INTERNATIONAL LP OR ITS AFFILIATES BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR MALFUNCTION;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
// OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
// ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////
#ifndef mnet_ssd_adas_flex_pic_prim_split_23_H
#define mnet_ssd_adas_flex_pic_prim_split_23_H

#define vas_gen_header_version                  	7

/* dag name */
#define mnet_ssd_adas_flex_pic_prim_split_23_DAG_NAME 	"mnet_ssd_adas_flex_pic_prim_split_23"

/* VDG file info */
#define mnet_ssd_adas_flex_pic_prim_split_23_vdg_name 	"mnet_ssd_adas_flex_pic_split_23.vdg"

/* VDG DAG memory info */
#define mnet_ssd_adas_flex_pic_prim_split_23_byte_offset 	4294967295	/* 0xffffffff */
#define mnet_ssd_adas_flex_pic_prim_split_23_byte_size 	308	/* 0x00000134 */
#define mnet_ssd_adas_flex_pic_prim_split_23_preferred_dram_xfer_size 	1

/* mnet_ssd_adas_flex_pic_prim_split_23 VMEM info */
#define mnet_ssd_adas_flex_pic_prim_split_23_use_ping_pong_vmem 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_VMEM_start 	4096	/* 0x00001000 */
#define mnet_ssd_adas_flex_pic_prim_split_23_VMEM_end 	478084	/* 0x00074b84 */
#define mnet_ssd_adas_flex_pic_prim_split_23_image_start 	262240	/* 0x00040060 */
#define mnet_ssd_adas_flex_pic_prim_split_23_image_size 	216152	/* 0x00034c58 */
#define mnet_ssd_adas_flex_pic_prim_split_23_dagbin_start 	478084	/* 0x00074b84 */

/* mnet_ssd_adas_flex_pic_prim_split_23 DAG info */
#define mnet_ssd_adas_flex_pic_prim_split_23_estimated_cycles 	21969
#define mnet_ssd_adas_flex_pic_prim_split_23_ddi_byte_size 	0	/* 0x00000000 */

/*******************************************************************************
 * DAG byte offset info for HMB/SMB/VCB and their fields
 * in DAG 'mnet_ssd_adas_flex_pic_prim_split_23' in source file 'pre_split23_mnet_ssd_adas_flex_pic_split_0.vas'
 ******************************************************************************/
/* mnet_ssd_adas_flex_pic_prim_split_23 HMB_input conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_cnngen_demangled_name 	"conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw"
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_is_main_input_output 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_is_constant 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_has_init_data 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_is_variable_scalar 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_ddi_byte_size 	0	/* 0x00000000 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_byte_offset 	0	/* 0x00000000 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_vbase_byte_offset 	4	/* 0x00000004 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_dbase_byte_offset 	28	/* 0x0000001c */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_dpitchm1_byte_offset 	32	/* 0x00000020 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_dpitchm1_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_vwidth_minus_one_byte_offset 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_vheight_minus_one_byte_offset 	18	/* 0x00000012 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_drotate_bit_offset 	198	/* 0x000000c6 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_hflip_bit_offset 	199	/* 0x000000c7 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_vflip_bit_offset 	200	/* 0x000000c8 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_dflip_bit_offset 	201	/* 0x000000c9 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_pflip_bit_offset 	202	/* 0x000000ca */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_W 	10
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_H 	10
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_D 	512
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_P 	1
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_data_num_bytes 	2
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_denable 	1
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_dpitch_num_bytes 	64
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_dram_format 	3
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_vp_interleave_mode 	2
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_tile_width 	2
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_vmem_buffer_num_bytes 	102400
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_dram_size_num_bytes 	122880
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_sign 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_datasize 	1
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_expoffset 	14
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_expbits 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_drotate 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_hflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_vflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_dflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_pflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___relu5_6__dw_trailing_extra_elements 	0

/* mnet_ssd_adas_flex_pic_prim_split_23 SMB_input __pvcn_2279_ */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__cnngen_demangled_name 	"__pvcn_2279_"
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__is_constant 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__has_init_data 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__is_variable_scalar 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__byte_offset 	48	/* 0x00000030 */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__vbase_byte_offset 	52	/* 0x00000034 */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__dbase_byte_offset 	76	/* 0x0000004c */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__dpitchm1_byte_offset 	80	/* 0x00000050 */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__dpitchm1_bsize 	32	/* 0x00000020 */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__W 	211420
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__H 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__D 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__P 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__data_num_bytes 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__denable 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__dpitch_num_bytes 	211456
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__dram_format 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__vp_interleave_mode 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__tile_width 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__vmem_buffer_num_bytes 	211420
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2279__dram_size_num_bytes 	211456

/* mnet_ssd_adas_flex_pic_prim_split_23 SMB_input __pvcn_2280_ */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__cnngen_demangled_name 	"__pvcn_2280_"
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__is_constant 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__has_init_data 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__is_variable_scalar 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__byte_offset 	88	/* 0x00000058 */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__vbase_byte_offset 	92	/* 0x0000005c */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__dbase_byte_offset 	116	/* 0x00000074 */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__dpitchm1_byte_offset 	120	/* 0x00000078 */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__dpitchm1_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__W 	4424
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__H 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__D 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__P 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__data_num_bytes 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__denable 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__dpitch_num_bytes 	4480
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__dram_format 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__vp_interleave_mode 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__tile_width 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__vmem_buffer_num_bytes 	4424
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2280__dram_size_num_bytes 	4480

/* mnet_ssd_adas_flex_pic_prim_split_23 HMB_output conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_cnngen_demangled_name 	"conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358"
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_is_main_input_output 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_byte_offset 	140	/* 0x0000008c */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_vbase_byte_offset 	144	/* 0x00000090 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_dbase_byte_offset 	168	/* 0x000000a8 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_dpitchm1_byte_offset 	172	/* 0x000000ac */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_dpitchm1_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_vwidth_minus_one_byte_offset 	156	/* 0x0000009c */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_vheight_minus_one_byte_offset 	158	/* 0x0000009e */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_drotate_bit_offset 	1318	/* 0x00000526 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_hflip_bit_offset 	1319	/* 0x00000527 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_vflip_bit_offset 	1320	/* 0x00000528 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_dflip_bit_offset 	1321	/* 0x00000529 */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_pflip_bit_offset 	1322	/* 0x0000052a */
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_W 	10
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_H 	10
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_D 	512
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_P 	1
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_data_num_bytes 	1
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_denable 	1
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_dpitch_num_bytes 	64
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_dram_format 	3
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_vp_interleave_mode 	2
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_tile_width 	1
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_vmem_buffer_num_bytes 	53248
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_dram_size_num_bytes 	61440
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_sign 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_datasize 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_expoffset 	7
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_expbits 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_drotate 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_hflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_vflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_dflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_pflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_23_conv5_6__dw_____bn_conv5_6__dw__scale_mul___muli___79_____bn_conv5_6__dw__scale_mul_____scale___muli___358_trailing_extra_elements 	0

/* mnet_ssd_adas_flex_pic_prim_split_23 HMB_output __pvcn_2281_ */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__cnngen_demangled_name 	"__pvcn_2281_"
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__is_main_input_output 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__is_bitvector 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__byte_offset 	192	/* 0x000000c0 */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__vbase_byte_offset 	196	/* 0x000000c4 */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__dbase_byte_offset 	220	/* 0x000000dc */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__dpitchm1_byte_offset 	224	/* 0x000000e0 */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__dpitchm1_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__vwidth_minus_one_byte_offset 	208	/* 0x000000d0 */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__vheight_minus_one_byte_offset 	210	/* 0x000000d2 */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__vheight_minus_one_bsize 	16	/* 0x00000010 */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__drotate_bit_offset 	1734	/* 0x000006c6 */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__hflip_bit_offset 	1735	/* 0x000006c7 */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__vflip_bit_offset 	1736	/* 0x000006c8 */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__dflip_bit_offset 	1737	/* 0x000006c9 */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__pflip_bit_offset 	1738	/* 0x000006ca */
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__W 	10
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__H 	10
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__D 	512
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__P 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__data_num_bytes 	2
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__denable 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__dpitch_num_bytes 	64
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__dram_format 	3
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__vp_interleave_mode 	2
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__tile_width 	2
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__vmem_buffer_num_bytes 	102400
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__dram_size_num_bytes 	122880
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__sign 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__datasize 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__expoffset 	14
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__expbits 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__drotate 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__hflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__vflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__dflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__pflip 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___pvcn_2281__trailing_extra_elements 	0

/* mnet_ssd_adas_flex_pic_prim_split_23 SMB_output __vas_created_terminate__v0 */
#define mnet_ssd_adas_flex_pic_prim_split_23___vas_created_terminate__v0_cnngen_demangled_name 	"__vas_created_terminate__v0"
#define mnet_ssd_adas_flex_pic_prim_split_23___vas_created_terminate__v0_is_main_input_output 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___vas_created_terminate__v0_is_bitvector 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___vas_created_terminate__v0_is_rlz 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___vas_created_terminate__v0_is_ten_bit_packed 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___vas_created_terminate__v0_byte_offset 	232	/* 0x000000e8 */
#define mnet_ssd_adas_flex_pic_prim_split_23___vas_created_terminate__v0_vbase_byte_offset 	236	/* 0x000000ec */
#define mnet_ssd_adas_flex_pic_prim_split_23___vas_created_terminate__v0_W 	256
#define mnet_ssd_adas_flex_pic_prim_split_23___vas_created_terminate__v0_H 	3
#define mnet_ssd_adas_flex_pic_prim_split_23___vas_created_terminate__v0_D 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___vas_created_terminate__v0_P 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___vas_created_terminate__v0_data_num_bytes 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___vas_created_terminate__v0_denable 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___vas_created_terminate__v0_dram_format 	0
#define mnet_ssd_adas_flex_pic_prim_split_23___vas_created_terminate__v0_vp_interleave_mode 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___vas_created_terminate__v0_tile_width 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___vas_created_terminate__v0_tile_height 	1
#define mnet_ssd_adas_flex_pic_prim_split_23___vas_created_terminate__v0_vmem_buffer_num_bytes 	96


#endif /* mnet_ssd_adas_flex_pic_prim_split_23_H */
