pkg			= HTTP_CONTROL_SERVER

$(pkg)_VERSION		= 1.0
$(pkg)_SITE_METHOD	= local
$(pkg)_SITE		= $(AMBARELLA_PKG_DIR)/http_control_server
$(pkg)_DEPENDENCIES	= ambaipc amba_examples sqlite
$(pkg)_INSTALL_STAGING	= NO
$(pkg)_INSTALL_IMAGES	= NO
$(pkg)_INSTALL_TARGET	= YES
$(pkg)_LICENSE		= MIT
$(pkg)_LICENSE_FILES	= License_MIT.txt

ifeq ($(BR2_arm),y)
ARMBADFLAGS = -DUSE_ARM
endif

#Prepre command line for sub packages
ifeq ($(BR2_PACKAGE_HTTP_CONTROL_SERVER),y)
  INSTALL_HTTP_CONTROL_SERVER = ARMBADFLAGS="$(ARMBADFLAGS)" $(TARGET_CONFIGURE_OPTS) $(TARGET_MAKE_ENV) $(MAKE) -C $(@D) -f br.mk DESTDIR=$(TARGET_DIR) install
  BUILD_HTTP_CONTROL_SERVER =  ARMBADFLAGS="$(ARMBADFLAGS)" $(TARGET_CONFIGURE_OPTS) $(TARGET_MAKE_ENV) $(MAKE) -C $(@D) -f br.mk
  CLEAN_HTTP_CONTROL_SERVER = ARMBADFLAGS="$(ARMBADFLAGS)" $(TARGET_CONFIGURE_OPTS) $(TARGET_MAKE_ENV) $(MAKE) -C $(@D) -f br.mk clean
else
  INSTALL_HTTP_CONTROL_SERVER =
  BUILD_HTTP_CONTROL_SERVER =
  CLEAN_HTTP_CONTROL_SERVER =
endif

#BuildRoot macro
define HTTP_CONTROL_SERVER_INSTALL_TARGET_CMDS
  $(INSTALL_HTTP_CONTROL_SERVER)
endef

define HTTP_CONTROL_SERVER_BUILD_CMDS
  $(BUILD_HTTP_CONTROL_SERVER)
endef

define HTTP_CONTROL_SERVER_CLEAN_CMDS
  $(CLEAN_HTTP_CONTROL_SERVER)
endef

$(eval $(generic-package))
