################################################################
#                    ThreadX / Linux                           #
################################################################
ifdef CONFIG_LINUX
obj-y += IMX390SHDR3_24/
obj-y += IMX390SHDR3RCCB/
obj-y += AR0233SHDR2_12bTo20b/
obj-y += AR0233SHDR2/
obj-y += AR0233/
obj-y += IMX290/
obj-y += IMX577/
obj-y += IMX577HDR2/
obj-y += IMX586/
obj-y += IMX490SHDR4_CAR53_ADAS/
obj-y += IMX424SHDR3_CAR53_ADAS/
obj-y += VG1762DOUTPUT_SHDR2/
obj-y += VG1762DOUTPUT_IR/
obj-y += OV2312/
obj-y += OV2312_HJ6074L_IR_ONLY/
obj-y += OV2312_TIMEDIVISION_FRONT_IR_HJ6074L/
obj-y += OV2312_TIMEDIVISION_FRONT_RGBIR_HJ6074L/
obj-y += OV2312_TIMEDIVISION_IR_HJ6074L/
obj-y += OV2312_TIMEDIVISION_RGBIR_HJ6074L/
obj-y += OX03CSHDR4/
obj-y += AR0239/
obj-y += AR0239HDR2/
else
obj-y += iqparams/$(AMBA_CHIP_ID)/IMX390SHDR3_24/
obj-y += iqparams/$(AMBA_CHIP_ID)/IMX390SHDR3RCCB/
obj-y += iqparams/$(AMBA_CHIP_ID)/AR0233SHDR2_12bTo20b/
obj-y += iqparams/$(AMBA_CHIP_ID)/AR0233SHDR2/
obj-y += iqparams/$(AMBA_CHIP_ID)/AR0233/
obj-y += iqparams/$(AMBA_CHIP_ID)/IMX290/
obj-y += iqparams/$(AMBA_CHIP_ID)/IMX577/
obj-y += iqparams/$(AMBA_CHIP_ID)/IMX577HDR2/
obj-y += iqparams/$(AMBA_CHIP_ID)/IMX586/
obj-y += iqparams/$(AMBA_CHIP_ID)/IMX490SHDR4_CAR53_ADAS/
obj-y += iqparams/$(AMBA_CHIP_ID)/IMX424SHDR3_CAR53_ADAS/
obj-y += iqparams/$(AMBA_CHIP_ID)/VG1762DOUTPUT_SHDR2/
obj-y += iqparams/$(AMBA_CHIP_ID)/VG1762DOUTPUT_IR/
obj-y += iqparams/$(AMBA_CHIP_ID)/OV2312/
obj-y += iqparams/$(AMBA_CHIP_ID)/OV2312_HJ6074L_IR_ONLY/
obj-y += iqparams/$(AMBA_CHIP_ID)/OV2312_TIMEDIVISION_FRONT_IR_HJ6074L/
obj-y += iqparams/$(AMBA_CHIP_ID)/OV2312_TIMEDIVISION_FRONT_RGBIR_HJ6074L/
obj-y += iqparams/$(AMBA_CHIP_ID)/OV2312_TIMEDIVISION_IR_HJ6074L/
obj-y += iqparams/$(AMBA_CHIP_ID)/OV2312_TIMEDIVISION_RGBIR_HJ6074L/
obj-y += iqparams/$(AMBA_CHIP_ID)/OV48C40/
obj-y += iqparams/$(AMBA_CHIP_ID)/OV48C40SHDR2/
obj-y += iqparams/$(AMBA_CHIP_ID)/OV48C40HDR2/
obj-y += iqparams/$(AMBA_CHIP_ID)/OX03CSHDR4/
obj-y += iqparams/$(AMBA_CHIP_ID)/AR0239/
obj-y += iqparams/$(AMBA_CHIP_ID)/AR0239HDR2/
endif
