ifeq ($(CONFIG_BUILD_COMSVC_FIFO),y)
include $(srctree)/$(src)/lib/src/common/dataflow/fifo/Makefile
endif

ifeq ($(CONFIG_BUILD_COMSVC_CONTAINER),y)
include $(srctree)/$(src)/lib/src/common/dataflow/container/Makefile
include $(srctree)/$(src)/lib/src/common/dataflow/wrapper/Makefile
endif
