////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2020 Ambarella International LP
////////////////////////////////////////////////////////////////////////////////
// This file and its contents ("Software") are protected by intellectual
// property rights including, without limitation, U.S. and/or foreign
// copyrights. This Software is also the confidential and proprietary
// information of Ambarella International LP and its licensors. You may not use,
// reproduce, disclose, distribute, modify, or otherwise prepare derivative
// works of this Software or any portion thereof except pursuant to a signed
// license agreement or nondisclosure agreement with Ambarella International LP
// or its authorized affiliates. In the absence of such an agreement, you agree
// to promptly notify and return this Software to Ambarella International LP.
//
// THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL AMBARELLA INTERNATIONAL LP OR ITS AFFILIATES BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR MALFUNCTION;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
// OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
// ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////
#ifndef flexidag_openseg_prim_split_10_H
#define flexidag_openseg_prim_split_10_H

#define vas_gen_header_version                  	7

/* dag name */
#define flexidag_openseg_prim_split_10_DAG_NAME 	"flexidag_openseg_prim_split_10"

/* VDG file info */
#define flexidag_openseg_prim_split_10_vdg_name 	"flexidag_openseg_split_10.vdg"

/* VDG DAG memory info */
#define flexidag_openseg_prim_split_10_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_10_byte_size 	804	/* 0x00000324 */
#define flexidag_openseg_prim_split_10_preferred_dram_xfer_size 	1

/* flexidag_openseg_prim_split_10 VMEM info */
#define flexidag_openseg_prim_split_10_use_ping_pong_vmem 	0
#define flexidag_openseg_prim_split_10_VMEM_start 	4096	/* 0x00001000 */
#define flexidag_openseg_prim_split_10_VMEM_end 	503916	/* 0x0007b06c */
#define flexidag_openseg_prim_split_10_image_start 	489440	/* 0x000777e0 */
#define flexidag_openseg_prim_split_10_image_size 	15280	/* 0x00003bb0 */
#define flexidag_openseg_prim_split_10_dagbin_start 	503916	/* 0x0007b06c */

/* flexidag_openseg_prim_split_10 DAG info */
#define flexidag_openseg_prim_split_10_estimated_cycles 	297232
#define flexidag_openseg_prim_split_10_ddi_byte_size 	0	/* 0x00000000 */

/*******************************************************************************
 * DAG byte offset info for HMB/SMB/VCB and their fields
 * in DAG 'flexidag_openseg_prim_split_10' in source file 'pre_split9_flexidag_openseg_split_0.vas'
 ******************************************************************************/
/* flexidag_openseg_prim_split_10 SMB_input __pvcn_707_ */
#define flexidag_openseg_prim_split_10___pvcn_707__cnngen_demangled_name 	"__pvcn_707_"
#define flexidag_openseg_prim_split_10___pvcn_707__is_constant 	1
#define flexidag_openseg_prim_split_10___pvcn_707__has_init_data 	1
#define flexidag_openseg_prim_split_10___pvcn_707__is_variable_scalar 	0
#define flexidag_openseg_prim_split_10___pvcn_707__is_bitvector 	0
#define flexidag_openseg_prim_split_10___pvcn_707__is_rlz 	0
#define flexidag_openseg_prim_split_10___pvcn_707__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_10___pvcn_707__byte_offset 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_10___pvcn_707__vbase_byte_offset 	4	/* 0x00000004 */
#define flexidag_openseg_prim_split_10___pvcn_707__dbase_byte_offset 	28	/* 0x0000001c */
#define flexidag_openseg_prim_split_10___pvcn_707__dpitchm1_byte_offset 	32	/* 0x00000020 */
#define flexidag_openseg_prim_split_10___pvcn_707__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_10___pvcn_707__W 	5752
#define flexidag_openseg_prim_split_10___pvcn_707__H 	1
#define flexidag_openseg_prim_split_10___pvcn_707__D 	1
#define flexidag_openseg_prim_split_10___pvcn_707__P 	1
#define flexidag_openseg_prim_split_10___pvcn_707__data_num_bytes 	1
#define flexidag_openseg_prim_split_10___pvcn_707__denable 	1
#define flexidag_openseg_prim_split_10___pvcn_707__dpitch_num_bytes 	5760
#define flexidag_openseg_prim_split_10___pvcn_707__dram_format 	0
#define flexidag_openseg_prim_split_10___pvcn_707__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_10___pvcn_707__tile_width 	1
#define flexidag_openseg_prim_split_10___pvcn_707__tile_height 	1
#define flexidag_openseg_prim_split_10___pvcn_707__vmem_buffer_num_bytes 	5752
#define flexidag_openseg_prim_split_10___pvcn_707__dram_size_num_bytes 	5760

/* flexidag_openseg_prim_split_10 SMB_input __pvcn_708_ */
#define flexidag_openseg_prim_split_10___pvcn_708__cnngen_demangled_name 	"__pvcn_708_"
#define flexidag_openseg_prim_split_10___pvcn_708__is_constant 	1
#define flexidag_openseg_prim_split_10___pvcn_708__has_init_data 	1
#define flexidag_openseg_prim_split_10___pvcn_708__is_variable_scalar 	0
#define flexidag_openseg_prim_split_10___pvcn_708__is_bitvector 	0
#define flexidag_openseg_prim_split_10___pvcn_708__is_rlz 	0
#define flexidag_openseg_prim_split_10___pvcn_708__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_10___pvcn_708__byte_offset 	40	/* 0x00000028 */
#define flexidag_openseg_prim_split_10___pvcn_708__vbase_byte_offset 	44	/* 0x0000002c */
#define flexidag_openseg_prim_split_10___pvcn_708__dbase_byte_offset 	68	/* 0x00000044 */
#define flexidag_openseg_prim_split_10___pvcn_708__dpitchm1_byte_offset 	72	/* 0x00000048 */
#define flexidag_openseg_prim_split_10___pvcn_708__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_10___pvcn_708__W 	320
#define flexidag_openseg_prim_split_10___pvcn_708__H 	1
#define flexidag_openseg_prim_split_10___pvcn_708__D 	1
#define flexidag_openseg_prim_split_10___pvcn_708__P 	1
#define flexidag_openseg_prim_split_10___pvcn_708__data_num_bytes 	1
#define flexidag_openseg_prim_split_10___pvcn_708__denable 	1
#define flexidag_openseg_prim_split_10___pvcn_708__dpitch_num_bytes 	320
#define flexidag_openseg_prim_split_10___pvcn_708__dram_format 	0
#define flexidag_openseg_prim_split_10___pvcn_708__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_10___pvcn_708__tile_width 	1
#define flexidag_openseg_prim_split_10___pvcn_708__tile_height 	1
#define flexidag_openseg_prim_split_10___pvcn_708__vmem_buffer_num_bytes 	320
#define flexidag_openseg_prim_split_10___pvcn_708__dram_size_num_bytes 	320

/* flexidag_openseg_prim_split_10 SMB_input __pvcn_711_ */
#define flexidag_openseg_prim_split_10___pvcn_711__cnngen_demangled_name 	"__pvcn_711_"
#define flexidag_openseg_prim_split_10___pvcn_711__is_constant 	1
#define flexidag_openseg_prim_split_10___pvcn_711__has_init_data 	1
#define flexidag_openseg_prim_split_10___pvcn_711__is_variable_scalar 	0
#define flexidag_openseg_prim_split_10___pvcn_711__is_bitvector 	0
#define flexidag_openseg_prim_split_10___pvcn_711__is_rlz 	0
#define flexidag_openseg_prim_split_10___pvcn_711__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_10___pvcn_711__byte_offset 	80	/* 0x00000050 */
#define flexidag_openseg_prim_split_10___pvcn_711__vbase_byte_offset 	84	/* 0x00000054 */
#define flexidag_openseg_prim_split_10___pvcn_711__dbase_byte_offset 	108	/* 0x0000006c */
#define flexidag_openseg_prim_split_10___pvcn_711__dpitchm1_byte_offset 	112	/* 0x00000070 */
#define flexidag_openseg_prim_split_10___pvcn_711__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_10___pvcn_711__W 	3228
#define flexidag_openseg_prim_split_10___pvcn_711__H 	1
#define flexidag_openseg_prim_split_10___pvcn_711__D 	1
#define flexidag_openseg_prim_split_10___pvcn_711__P 	1
#define flexidag_openseg_prim_split_10___pvcn_711__data_num_bytes 	1
#define flexidag_openseg_prim_split_10___pvcn_711__denable 	1
#define flexidag_openseg_prim_split_10___pvcn_711__dpitch_num_bytes 	3264
#define flexidag_openseg_prim_split_10___pvcn_711__dram_format 	0
#define flexidag_openseg_prim_split_10___pvcn_711__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_10___pvcn_711__tile_width 	1
#define flexidag_openseg_prim_split_10___pvcn_711__tile_height 	1
#define flexidag_openseg_prim_split_10___pvcn_711__vmem_buffer_num_bytes 	3228
#define flexidag_openseg_prim_split_10___pvcn_711__dram_size_num_bytes 	3264

/* flexidag_openseg_prim_split_10 SMB_input __pvcn_712_ */
#define flexidag_openseg_prim_split_10___pvcn_712__cnngen_demangled_name 	"__pvcn_712_"
#define flexidag_openseg_prim_split_10___pvcn_712__is_constant 	1
#define flexidag_openseg_prim_split_10___pvcn_712__has_init_data 	1
#define flexidag_openseg_prim_split_10___pvcn_712__is_variable_scalar 	0
#define flexidag_openseg_prim_split_10___pvcn_712__is_bitvector 	0
#define flexidag_openseg_prim_split_10___pvcn_712__is_rlz 	0
#define flexidag_openseg_prim_split_10___pvcn_712__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_10___pvcn_712__byte_offset 	120	/* 0x00000078 */
#define flexidag_openseg_prim_split_10___pvcn_712__vbase_byte_offset 	124	/* 0x0000007c */
#define flexidag_openseg_prim_split_10___pvcn_712__dbase_byte_offset 	148	/* 0x00000094 */
#define flexidag_openseg_prim_split_10___pvcn_712__dpitchm1_byte_offset 	152	/* 0x00000098 */
#define flexidag_openseg_prim_split_10___pvcn_712__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_10___pvcn_712__W 	96
#define flexidag_openseg_prim_split_10___pvcn_712__H 	1
#define flexidag_openseg_prim_split_10___pvcn_712__D 	1
#define flexidag_openseg_prim_split_10___pvcn_712__P 	1
#define flexidag_openseg_prim_split_10___pvcn_712__data_num_bytes 	1
#define flexidag_openseg_prim_split_10___pvcn_712__denable 	1
#define flexidag_openseg_prim_split_10___pvcn_712__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_10___pvcn_712__dram_format 	0
#define flexidag_openseg_prim_split_10___pvcn_712__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_10___pvcn_712__tile_width 	1
#define flexidag_openseg_prim_split_10___pvcn_712__tile_height 	1
#define flexidag_openseg_prim_split_10___pvcn_712__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_10___pvcn_712__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_10 SMB_input __pvcn_714_ */
#define flexidag_openseg_prim_split_10___pvcn_714__cnngen_demangled_name 	"__pvcn_714_"
#define flexidag_openseg_prim_split_10___pvcn_714__is_constant 	1
#define flexidag_openseg_prim_split_10___pvcn_714__has_init_data 	1
#define flexidag_openseg_prim_split_10___pvcn_714__is_variable_scalar 	0
#define flexidag_openseg_prim_split_10___pvcn_714__is_bitvector 	0
#define flexidag_openseg_prim_split_10___pvcn_714__is_rlz 	0
#define flexidag_openseg_prim_split_10___pvcn_714__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_10___pvcn_714__byte_offset 	160	/* 0x000000a0 */
#define flexidag_openseg_prim_split_10___pvcn_714__vbase_byte_offset 	164	/* 0x000000a4 */
#define flexidag_openseg_prim_split_10___pvcn_714__dbase_byte_offset 	188	/* 0x000000bc */
#define flexidag_openseg_prim_split_10___pvcn_714__dpitchm1_byte_offset 	192	/* 0x000000c0 */
#define flexidag_openseg_prim_split_10___pvcn_714__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_10___pvcn_714__W 	1656
#define flexidag_openseg_prim_split_10___pvcn_714__H 	1
#define flexidag_openseg_prim_split_10___pvcn_714__D 	1
#define flexidag_openseg_prim_split_10___pvcn_714__P 	1
#define flexidag_openseg_prim_split_10___pvcn_714__data_num_bytes 	1
#define flexidag_openseg_prim_split_10___pvcn_714__denable 	1
#define flexidag_openseg_prim_split_10___pvcn_714__dpitch_num_bytes 	1664
#define flexidag_openseg_prim_split_10___pvcn_714__dram_format 	0
#define flexidag_openseg_prim_split_10___pvcn_714__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_10___pvcn_714__tile_width 	1
#define flexidag_openseg_prim_split_10___pvcn_714__tile_height 	1
#define flexidag_openseg_prim_split_10___pvcn_714__vmem_buffer_num_bytes 	1656
#define flexidag_openseg_prim_split_10___pvcn_714__dram_size_num_bytes 	1664

/* flexidag_openseg_prim_split_10 SMB_input __pvcn_715_ */
#define flexidag_openseg_prim_split_10___pvcn_715__cnngen_demangled_name 	"__pvcn_715_"
#define flexidag_openseg_prim_split_10___pvcn_715__is_constant 	1
#define flexidag_openseg_prim_split_10___pvcn_715__has_init_data 	1
#define flexidag_openseg_prim_split_10___pvcn_715__is_variable_scalar 	0
#define flexidag_openseg_prim_split_10___pvcn_715__is_bitvector 	0
#define flexidag_openseg_prim_split_10___pvcn_715__is_rlz 	0
#define flexidag_openseg_prim_split_10___pvcn_715__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_10___pvcn_715__byte_offset 	200	/* 0x000000c8 */
#define flexidag_openseg_prim_split_10___pvcn_715__vbase_byte_offset 	204	/* 0x000000cc */
#define flexidag_openseg_prim_split_10___pvcn_715__dbase_byte_offset 	228	/* 0x000000e4 */
#define flexidag_openseg_prim_split_10___pvcn_715__dpitchm1_byte_offset 	232	/* 0x000000e8 */
#define flexidag_openseg_prim_split_10___pvcn_715__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_10___pvcn_715__W 	96
#define flexidag_openseg_prim_split_10___pvcn_715__H 	1
#define flexidag_openseg_prim_split_10___pvcn_715__D 	1
#define flexidag_openseg_prim_split_10___pvcn_715__P 	1
#define flexidag_openseg_prim_split_10___pvcn_715__data_num_bytes 	1
#define flexidag_openseg_prim_split_10___pvcn_715__denable 	1
#define flexidag_openseg_prim_split_10___pvcn_715__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_10___pvcn_715__dram_format 	0
#define flexidag_openseg_prim_split_10___pvcn_715__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_10___pvcn_715__tile_width 	1
#define flexidag_openseg_prim_split_10___pvcn_715__tile_height 	1
#define flexidag_openseg_prim_split_10___pvcn_715__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_10___pvcn_715__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_10 SMB_input __pvcn_718_ */
#define flexidag_openseg_prim_split_10___pvcn_718__cnngen_demangled_name 	"__pvcn_718_"
#define flexidag_openseg_prim_split_10___pvcn_718__is_constant 	1
#define flexidag_openseg_prim_split_10___pvcn_718__has_init_data 	1
#define flexidag_openseg_prim_split_10___pvcn_718__is_variable_scalar 	0
#define flexidag_openseg_prim_split_10___pvcn_718__is_bitvector 	0
#define flexidag_openseg_prim_split_10___pvcn_718__is_rlz 	0
#define flexidag_openseg_prim_split_10___pvcn_718__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_10___pvcn_718__byte_offset 	240	/* 0x000000f0 */
#define flexidag_openseg_prim_split_10___pvcn_718__vbase_byte_offset 	244	/* 0x000000f4 */
#define flexidag_openseg_prim_split_10___pvcn_718__dbase_byte_offset 	268	/* 0x0000010c */
#define flexidag_openseg_prim_split_10___pvcn_718__dpitchm1_byte_offset 	272	/* 0x00000110 */
#define flexidag_openseg_prim_split_10___pvcn_718__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_10___pvcn_718__W 	3232
#define flexidag_openseg_prim_split_10___pvcn_718__H 	1
#define flexidag_openseg_prim_split_10___pvcn_718__D 	1
#define flexidag_openseg_prim_split_10___pvcn_718__P 	1
#define flexidag_openseg_prim_split_10___pvcn_718__data_num_bytes 	1
#define flexidag_openseg_prim_split_10___pvcn_718__denable 	1
#define flexidag_openseg_prim_split_10___pvcn_718__dpitch_num_bytes 	3264
#define flexidag_openseg_prim_split_10___pvcn_718__dram_format 	0
#define flexidag_openseg_prim_split_10___pvcn_718__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_10___pvcn_718__tile_width 	1
#define flexidag_openseg_prim_split_10___pvcn_718__tile_height 	1
#define flexidag_openseg_prim_split_10___pvcn_718__vmem_buffer_num_bytes 	3232
#define flexidag_openseg_prim_split_10___pvcn_718__dram_size_num_bytes 	3264

/* flexidag_openseg_prim_split_10 SMB_input __pvcn_719_ */
#define flexidag_openseg_prim_split_10___pvcn_719__cnngen_demangled_name 	"__pvcn_719_"
#define flexidag_openseg_prim_split_10___pvcn_719__is_constant 	1
#define flexidag_openseg_prim_split_10___pvcn_719__has_init_data 	1
#define flexidag_openseg_prim_split_10___pvcn_719__is_variable_scalar 	0
#define flexidag_openseg_prim_split_10___pvcn_719__is_bitvector 	0
#define flexidag_openseg_prim_split_10___pvcn_719__is_rlz 	0
#define flexidag_openseg_prim_split_10___pvcn_719__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_10___pvcn_719__byte_offset 	280	/* 0x00000118 */
#define flexidag_openseg_prim_split_10___pvcn_719__vbase_byte_offset 	284	/* 0x0000011c */
#define flexidag_openseg_prim_split_10___pvcn_719__dbase_byte_offset 	308	/* 0x00000134 */
#define flexidag_openseg_prim_split_10___pvcn_719__dpitchm1_byte_offset 	312	/* 0x00000138 */
#define flexidag_openseg_prim_split_10___pvcn_719__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_10___pvcn_719__W 	96
#define flexidag_openseg_prim_split_10___pvcn_719__H 	1
#define flexidag_openseg_prim_split_10___pvcn_719__D 	1
#define flexidag_openseg_prim_split_10___pvcn_719__P 	1
#define flexidag_openseg_prim_split_10___pvcn_719__data_num_bytes 	1
#define flexidag_openseg_prim_split_10___pvcn_719__denable 	1
#define flexidag_openseg_prim_split_10___pvcn_719__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_10___pvcn_719__dram_format 	0
#define flexidag_openseg_prim_split_10___pvcn_719__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_10___pvcn_719__tile_width 	1
#define flexidag_openseg_prim_split_10___pvcn_719__tile_height 	1
#define flexidag_openseg_prim_split_10___pvcn_719__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_10___pvcn_719__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_10 HMB_input PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_cnngen_demangled_name 	"PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453"
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_is_main_input_output 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_is_constant 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_has_init_data 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_is_variable_scalar 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_ddi_byte_size 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_is_bitvector 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_is_rlz 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_byte_offset 	320	/* 0x00000140 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_vbase_byte_offset 	324	/* 0x00000144 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_dbase_byte_offset 	348	/* 0x0000015c */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_dpitchm1_byte_offset 	352	/* 0x00000160 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_vwidth_minus_one_byte_offset 	336	/* 0x00000150 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_vheight_minus_one_byte_offset 	338	/* 0x00000152 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_drotate_bit_offset 	2758	/* 0x00000ac6 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_hflip_bit_offset 	2759	/* 0x00000ac7 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_vflip_bit_offset 	2760	/* 0x00000ac8 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_dflip_bit_offset 	2761	/* 0x00000ac9 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_pflip_bit_offset 	2762	/* 0x00000aca */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_W 	160
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_H 	64
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_D 	128
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_P 	1
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_data_num_bytes 	1
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_denable 	1
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_dram_format 	3
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_tile_width 	4
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_tile_height 	1
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_vmem_buffer_num_bytes 	247808
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_dram_size_num_bytes 	1310720
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_sign 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_datasize 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_expoffset 	5
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_expbits 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_drotate 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_hflip 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_vflip 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_dflip 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_pflip 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_10 HMB_output PeleeNet__stage_2_dense_block_0__concat______muli___456 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_0__concat______muli___456"
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_is_main_input_output 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_is_bitvector 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_is_rlz 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_byte_offset 	360	/* 0x00000168 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_vbase_byte_offset 	364	/* 0x0000016c */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_dbase_byte_offset 	388	/* 0x00000184 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_dpitchm1_byte_offset 	392	/* 0x00000188 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_vwidth_minus_one_byte_offset 	376	/* 0x00000178 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_vheight_minus_one_byte_offset 	378	/* 0x0000017a */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_drotate_bit_offset 	3078	/* 0x00000c06 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_hflip_bit_offset 	3079	/* 0x00000c07 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_vflip_bit_offset 	3080	/* 0x00000c08 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_dflip_bit_offset 	3081	/* 0x00000c09 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_pflip_bit_offset 	3082	/* 0x00000c0a */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_W 	160
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_H 	64
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_D 	160
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_P 	1
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_data_num_bytes 	1
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_denable 	1
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_dram_format 	3
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_tile_width 	4
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_tile_height 	1
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_vmem_buffer_num_bytes 	102400
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_dram_size_num_bytes 	1638400
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_sign 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_datasize 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_expoffset 	5
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_expbits 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_drotate 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_hflip 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_vflip 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_dflip 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_pflip 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__concat______muli___456_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_10 VCB PeleeNet__stage_2_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___454___5 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___454___5_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___454___5"
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___454___5_is_bitvector 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___454___5_is_rlz 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___454___5_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___454___5_byte_offset 	432	/* 0x000001b0 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___454___5_vbase_byte_offset 	440	/* 0x000001b8 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___454___5_vmem_buffer_num_bytes 	40960

/* flexidag_openseg_prim_split_10 VCB PeleeNet__stage_2_dense_block_0__conv_right_0__Relu */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_right_0__Relu_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_0__conv_right_0__Relu"
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_right_0__Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_right_0__Relu_is_rlz 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_right_0__Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_right_0__Relu_byte_offset 	516	/* 0x00000204 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_right_0__Relu_vbase_byte_offset 	524	/* 0x0000020c */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_right_0__Relu_vmem_buffer_num_bytes 	53760

/* flexidag_openseg_prim_split_10 VCB PeleeNet__stage_2_dense_block_0__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_0__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	564	/* 0x00000234 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	572	/* 0x0000023c */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	13440

/* flexidag_openseg_prim_split_10 VCB PeleeNet__stage_2_dense_block_0__conv_left_0__Relu */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_left_0__Relu_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_0__conv_left_0__Relu"
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_left_0__Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_left_0__Relu_is_rlz 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_left_0__Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_left_0__Relu_byte_offset 	668	/* 0x0000029c */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_left_0__Relu_vbase_byte_offset 	676	/* 0x000002a4 */
#define flexidag_openseg_prim_split_10_PeleeNet__stage_2_dense_block_0__conv_left_0__Relu_vmem_buffer_num_bytes 	26880

/* flexidag_openseg_prim_split_10 SMB_output __vas_created_terminate__v0 */
#define flexidag_openseg_prim_split_10___vas_created_terminate__v0_cnngen_demangled_name 	"__vas_created_terminate__v0"
#define flexidag_openseg_prim_split_10___vas_created_terminate__v0_is_main_input_output 	0
#define flexidag_openseg_prim_split_10___vas_created_terminate__v0_is_bitvector 	1
#define flexidag_openseg_prim_split_10___vas_created_terminate__v0_is_rlz 	0
#define flexidag_openseg_prim_split_10___vas_created_terminate__v0_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_10___vas_created_terminate__v0_byte_offset 	728	/* 0x000002d8 */
#define flexidag_openseg_prim_split_10___vas_created_terminate__v0_vbase_byte_offset 	732	/* 0x000002dc */
#define flexidag_openseg_prim_split_10___vas_created_terminate__v0_W 	256
#define flexidag_openseg_prim_split_10___vas_created_terminate__v0_H 	3
#define flexidag_openseg_prim_split_10___vas_created_terminate__v0_D 	1
#define flexidag_openseg_prim_split_10___vas_created_terminate__v0_P 	1
#define flexidag_openseg_prim_split_10___vas_created_terminate__v0_data_num_bytes 	1
#define flexidag_openseg_prim_split_10___vas_created_terminate__v0_denable 	0
#define flexidag_openseg_prim_split_10___vas_created_terminate__v0_dram_format 	0
#define flexidag_openseg_prim_split_10___vas_created_terminate__v0_vp_interleave_mode 	1
#define flexidag_openseg_prim_split_10___vas_created_terminate__v0_tile_width 	1
#define flexidag_openseg_prim_split_10___vas_created_terminate__v0_tile_height 	1
#define flexidag_openseg_prim_split_10___vas_created_terminate__v0_vmem_buffer_num_bytes 	96


#endif /* flexidag_openseg_prim_split_10_H */
