////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2020 Ambarella International LP
////////////////////////////////////////////////////////////////////////////////
// This file and its contents ("Software") are protected by intellectual
// property rights including, without limitation, U.S. and/or foreign
// copyrights. This Software is also the confidential and proprietary
// information of Ambarella International LP and its licensors. You may not use,
// reproduce, disclose, distribute, modify, or otherwise prepare derivative
// works of this Software or any portion thereof except pursuant to a signed
// license agreement or nondisclosure agreement with Ambarella International LP
// or its authorized affiliates. In the absence of such an agreement, you agree
// to promptly notify and return this Software to Ambarella International LP.
//
// THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL AMBARELLA INTERNATIONAL LP OR ITS AFFILIATES BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR MALFUNCTION;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
// OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
// ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////
#ifndef flexidag_openseg_prim_split_18_H
#define flexidag_openseg_prim_split_18_H

#define vas_gen_header_version                  	7

/* dag name */
#define flexidag_openseg_prim_split_18_DAG_NAME 	"flexidag_openseg_prim_split_18"

/* VDG file info */
#define flexidag_openseg_prim_split_18_vdg_name 	"flexidag_openseg_split_18.vdg"

/* VDG DAG memory info */
#define flexidag_openseg_prim_split_18_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_18_byte_size 	1264	/* 0x000004f0 */
#define flexidag_openseg_prim_split_18_preferred_dram_xfer_size 	1

/* flexidag_openseg_prim_split_18 VMEM info */
#define flexidag_openseg_prim_split_18_use_ping_pong_vmem 	0
#define flexidag_openseg_prim_split_18_VMEM_start 	4096	/* 0x00001000 */
#define flexidag_openseg_prim_split_18_VMEM_end 	509436	/* 0x0007c5fc */
#define flexidag_openseg_prim_split_18_image_start 	465120	/* 0x000718e0 */
#define flexidag_openseg_prim_split_18_image_size 	45580	/* 0x0000b20c */
#define flexidag_openseg_prim_split_18_dagbin_start 	509436	/* 0x0007c5fc */

/* flexidag_openseg_prim_split_18 DAG info */
#define flexidag_openseg_prim_split_18_estimated_cycles 	223455
#define flexidag_openseg_prim_split_18_ddi_byte_size 	0	/* 0x00000000 */

/*******************************************************************************
 * DAG byte offset info for HMB/SMB/VCB and their fields
 * in DAG 'flexidag_openseg_prim_split_18' in source file 'pre_split15_flexidag_openseg_split_2.vas'
 ******************************************************************************/
/* flexidag_openseg_prim_split_18 HMB_input PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_cnngen_demangled_name 	"PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466"
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_is_main_input_output 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_is_constant 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_has_init_data 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_is_variable_scalar 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_ddi_byte_size 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_is_bitvector 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_is_rlz 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_byte_offset 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_vbase_byte_offset 	4	/* 0x00000004 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_dbase_byte_offset 	28	/* 0x0000001c */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_dpitchm1_byte_offset 	32	/* 0x00000020 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_vwidth_minus_one_byte_offset 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_vheight_minus_one_byte_offset 	18	/* 0x00000012 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_drotate_bit_offset 	198	/* 0x000000c6 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_hflip_bit_offset 	199	/* 0x000000c7 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_vflip_bit_offset 	200	/* 0x000000c8 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_dflip_bit_offset 	201	/* 0x000000c9 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_pflip_bit_offset 	202	/* 0x000000ca */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_W 	80
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_H 	32
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_D 	256
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_P 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_data_num_bytes 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_denable 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_dram_format 	3
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_tile_width 	4
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_tile_height 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_vmem_buffer_num_bytes 	16384
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_dram_size_num_bytes 	655360
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_sign 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_datasize 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_expoffset 	5
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_expbits 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_drotate 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_hflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_vflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_dflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_pflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_18 HMB_input PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8"
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_is_main_input_output 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_is_constant 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_has_init_data 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_is_variable_scalar 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_ddi_byte_size 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_is_bitvector 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_is_rlz 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_byte_offset 	40	/* 0x00000028 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_vbase_byte_offset 	44	/* 0x0000002c */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_dbase_byte_offset 	68	/* 0x00000044 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_dpitchm1_byte_offset 	72	/* 0x00000048 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_vwidth_minus_one_byte_offset 	56	/* 0x00000038 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_vheight_minus_one_byte_offset 	58	/* 0x0000003a */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_drotate_bit_offset 	518	/* 0x00000206 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_hflip_bit_offset 	519	/* 0x00000207 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_vflip_bit_offset 	520	/* 0x00000208 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_dflip_bit_offset 	521	/* 0x00000209 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_pflip_bit_offset 	522	/* 0x0000020a */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_W 	80
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_H 	32
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_D 	128
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_P 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_data_num_bytes 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_denable 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_dram_format 	3
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_tile_width 	4
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_tile_height 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_vmem_buffer_num_bytes 	40960
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_dram_size_num_bytes 	327680
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_sign 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_datasize 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_expoffset 	4
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_expbits 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_drotate 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_hflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_vflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_dflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_pflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_18 HMB_input PeleeNet__stage_3_dense_block_0__conv_right_0__Relu */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_0__conv_right_0__Relu"
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_is_main_input_output 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_is_constant 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_has_init_data 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_is_variable_scalar 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_ddi_byte_size 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_is_rlz 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_byte_offset 	80	/* 0x00000050 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_vbase_byte_offset 	84	/* 0x00000054 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_dbase_byte_offset 	108	/* 0x0000006c */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_dpitchm1_byte_offset 	112	/* 0x00000070 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_vwidth_minus_one_byte_offset 	96	/* 0x00000060 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_vheight_minus_one_byte_offset 	98	/* 0x00000062 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_drotate_bit_offset 	838	/* 0x00000346 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_hflip_bit_offset 	839	/* 0x00000347 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_vflip_bit_offset 	840	/* 0x00000348 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_dflip_bit_offset 	841	/* 0x00000349 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_pflip_bit_offset 	842	/* 0x0000034a */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_W 	80
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_H 	32
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_D 	64
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_P 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_data_num_bytes 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_denable 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_dram_format 	3
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_tile_width 	4
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_tile_height 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_vmem_buffer_num_bytes 	68608
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_dram_size_num_bytes 	163840
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_sign 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_datasize 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_expoffset 	4
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_expbits 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_drotate 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_hflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_vflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_dflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_pflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_18 SMB_input __pvcn_876_ */
#define flexidag_openseg_prim_split_18___pvcn_876__cnngen_demangled_name 	"__pvcn_876_"
#define flexidag_openseg_prim_split_18___pvcn_876__is_constant 	1
#define flexidag_openseg_prim_split_18___pvcn_876__has_init_data 	1
#define flexidag_openseg_prim_split_18___pvcn_876__is_variable_scalar 	0
#define flexidag_openseg_prim_split_18___pvcn_876__is_bitvector 	0
#define flexidag_openseg_prim_split_18___pvcn_876__is_rlz 	0
#define flexidag_openseg_prim_split_18___pvcn_876__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18___pvcn_876__byte_offset 	116	/* 0x00000074 */
#define flexidag_openseg_prim_split_18___pvcn_876__vbase_byte_offset 	120	/* 0x00000078 */
#define flexidag_openseg_prim_split_18___pvcn_876__dbase_byte_offset 	144	/* 0x00000090 */
#define flexidag_openseg_prim_split_18___pvcn_876__dpitchm1_byte_offset 	148	/* 0x00000094 */
#define flexidag_openseg_prim_split_18___pvcn_876__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18___pvcn_876__W 	5724
#define flexidag_openseg_prim_split_18___pvcn_876__H 	1
#define flexidag_openseg_prim_split_18___pvcn_876__D 	1
#define flexidag_openseg_prim_split_18___pvcn_876__P 	1
#define flexidag_openseg_prim_split_18___pvcn_876__data_num_bytes 	1
#define flexidag_openseg_prim_split_18___pvcn_876__denable 	1
#define flexidag_openseg_prim_split_18___pvcn_876__dpitch_num_bytes 	5760
#define flexidag_openseg_prim_split_18___pvcn_876__dram_format 	0
#define flexidag_openseg_prim_split_18___pvcn_876__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_18___pvcn_876__tile_width 	1
#define flexidag_openseg_prim_split_18___pvcn_876__tile_height 	1
#define flexidag_openseg_prim_split_18___pvcn_876__vmem_buffer_num_bytes 	5724
#define flexidag_openseg_prim_split_18___pvcn_876__dram_size_num_bytes 	5760

/* flexidag_openseg_prim_split_18 SMB_input __pvcn_877_ */
#define flexidag_openseg_prim_split_18___pvcn_877__cnngen_demangled_name 	"__pvcn_877_"
#define flexidag_openseg_prim_split_18___pvcn_877__is_constant 	1
#define flexidag_openseg_prim_split_18___pvcn_877__has_init_data 	1
#define flexidag_openseg_prim_split_18___pvcn_877__is_variable_scalar 	0
#define flexidag_openseg_prim_split_18___pvcn_877__is_bitvector 	0
#define flexidag_openseg_prim_split_18___pvcn_877__is_rlz 	0
#define flexidag_openseg_prim_split_18___pvcn_877__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18___pvcn_877__byte_offset 	152	/* 0x00000098 */
#define flexidag_openseg_prim_split_18___pvcn_877__vbase_byte_offset 	156	/* 0x0000009c */
#define flexidag_openseg_prim_split_18___pvcn_877__dbase_byte_offset 	180	/* 0x000000b4 */
#define flexidag_openseg_prim_split_18___pvcn_877__dpitchm1_byte_offset 	184	/* 0x000000b8 */
#define flexidag_openseg_prim_split_18___pvcn_877__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18___pvcn_877__W 	96
#define flexidag_openseg_prim_split_18___pvcn_877__H 	1
#define flexidag_openseg_prim_split_18___pvcn_877__D 	1
#define flexidag_openseg_prim_split_18___pvcn_877__P 	1
#define flexidag_openseg_prim_split_18___pvcn_877__data_num_bytes 	1
#define flexidag_openseg_prim_split_18___pvcn_877__denable 	1
#define flexidag_openseg_prim_split_18___pvcn_877__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_18___pvcn_877__dram_format 	0
#define flexidag_openseg_prim_split_18___pvcn_877__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_18___pvcn_877__tile_width 	1
#define flexidag_openseg_prim_split_18___pvcn_877__tile_height 	1
#define flexidag_openseg_prim_split_18___pvcn_877__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_18___pvcn_877__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_18 SMB_input __pvcn_879_ */
#define flexidag_openseg_prim_split_18___pvcn_879__cnngen_demangled_name 	"__pvcn_879_"
#define flexidag_openseg_prim_split_18___pvcn_879__is_constant 	1
#define flexidag_openseg_prim_split_18___pvcn_879__has_init_data 	1
#define flexidag_openseg_prim_split_18___pvcn_879__is_variable_scalar 	0
#define flexidag_openseg_prim_split_18___pvcn_879__is_bitvector 	0
#define flexidag_openseg_prim_split_18___pvcn_879__is_rlz 	0
#define flexidag_openseg_prim_split_18___pvcn_879__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18___pvcn_879__byte_offset 	192	/* 0x000000c0 */
#define flexidag_openseg_prim_split_18___pvcn_879__vbase_byte_offset 	196	/* 0x000000c4 */
#define flexidag_openseg_prim_split_18___pvcn_879__dbase_byte_offset 	220	/* 0x000000dc */
#define flexidag_openseg_prim_split_18___pvcn_879__dpitchm1_byte_offset 	224	/* 0x000000e0 */
#define flexidag_openseg_prim_split_18___pvcn_879__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18___pvcn_879__W 	1448
#define flexidag_openseg_prim_split_18___pvcn_879__H 	1
#define flexidag_openseg_prim_split_18___pvcn_879__D 	1
#define flexidag_openseg_prim_split_18___pvcn_879__P 	1
#define flexidag_openseg_prim_split_18___pvcn_879__data_num_bytes 	1
#define flexidag_openseg_prim_split_18___pvcn_879__denable 	1
#define flexidag_openseg_prim_split_18___pvcn_879__dpitch_num_bytes 	1472
#define flexidag_openseg_prim_split_18___pvcn_879__dram_format 	0
#define flexidag_openseg_prim_split_18___pvcn_879__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_18___pvcn_879__tile_width 	1
#define flexidag_openseg_prim_split_18___pvcn_879__tile_height 	1
#define flexidag_openseg_prim_split_18___pvcn_879__vmem_buffer_num_bytes 	1448
#define flexidag_openseg_prim_split_18___pvcn_879__dram_size_num_bytes 	1472

/* flexidag_openseg_prim_split_18 SMB_input __pvcn_880_ */
#define flexidag_openseg_prim_split_18___pvcn_880__cnngen_demangled_name 	"__pvcn_880_"
#define flexidag_openseg_prim_split_18___pvcn_880__is_constant 	1
#define flexidag_openseg_prim_split_18___pvcn_880__has_init_data 	1
#define flexidag_openseg_prim_split_18___pvcn_880__is_variable_scalar 	0
#define flexidag_openseg_prim_split_18___pvcn_880__is_bitvector 	0
#define flexidag_openseg_prim_split_18___pvcn_880__is_rlz 	0
#define flexidag_openseg_prim_split_18___pvcn_880__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18___pvcn_880__byte_offset 	232	/* 0x000000e8 */
#define flexidag_openseg_prim_split_18___pvcn_880__vbase_byte_offset 	236	/* 0x000000ec */
#define flexidag_openseg_prim_split_18___pvcn_880__dbase_byte_offset 	260	/* 0x00000104 */
#define flexidag_openseg_prim_split_18___pvcn_880__dpitchm1_byte_offset 	264	/* 0x00000108 */
#define flexidag_openseg_prim_split_18___pvcn_880__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18___pvcn_880__W 	96
#define flexidag_openseg_prim_split_18___pvcn_880__H 	1
#define flexidag_openseg_prim_split_18___pvcn_880__D 	1
#define flexidag_openseg_prim_split_18___pvcn_880__P 	1
#define flexidag_openseg_prim_split_18___pvcn_880__data_num_bytes 	1
#define flexidag_openseg_prim_split_18___pvcn_880__denable 	1
#define flexidag_openseg_prim_split_18___pvcn_880__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_18___pvcn_880__dram_format 	0
#define flexidag_openseg_prim_split_18___pvcn_880__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_18___pvcn_880__tile_width 	1
#define flexidag_openseg_prim_split_18___pvcn_880__tile_height 	1
#define flexidag_openseg_prim_split_18___pvcn_880__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_18___pvcn_880__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_18 SMB_input __pvcn_883_ */
#define flexidag_openseg_prim_split_18___pvcn_883__cnngen_demangled_name 	"__pvcn_883_"
#define flexidag_openseg_prim_split_18___pvcn_883__is_constant 	1
#define flexidag_openseg_prim_split_18___pvcn_883__has_init_data 	1
#define flexidag_openseg_prim_split_18___pvcn_883__is_variable_scalar 	0
#define flexidag_openseg_prim_split_18___pvcn_883__is_bitvector 	0
#define flexidag_openseg_prim_split_18___pvcn_883__is_rlz 	0
#define flexidag_openseg_prim_split_18___pvcn_883__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18___pvcn_883__byte_offset 	272	/* 0x00000110 */
#define flexidag_openseg_prim_split_18___pvcn_883__vbase_byte_offset 	276	/* 0x00000114 */
#define flexidag_openseg_prim_split_18___pvcn_883__dbase_byte_offset 	300	/* 0x0000012c */
#define flexidag_openseg_prim_split_18___pvcn_883__dpitchm1_byte_offset 	304	/* 0x00000130 */
#define flexidag_openseg_prim_split_18___pvcn_883__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18___pvcn_883__W 	5780
#define flexidag_openseg_prim_split_18___pvcn_883__H 	1
#define flexidag_openseg_prim_split_18___pvcn_883__D 	1
#define flexidag_openseg_prim_split_18___pvcn_883__P 	1
#define flexidag_openseg_prim_split_18___pvcn_883__data_num_bytes 	1
#define flexidag_openseg_prim_split_18___pvcn_883__denable 	1
#define flexidag_openseg_prim_split_18___pvcn_883__dpitch_num_bytes 	5824
#define flexidag_openseg_prim_split_18___pvcn_883__dram_format 	0
#define flexidag_openseg_prim_split_18___pvcn_883__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_18___pvcn_883__tile_width 	1
#define flexidag_openseg_prim_split_18___pvcn_883__tile_height 	1
#define flexidag_openseg_prim_split_18___pvcn_883__vmem_buffer_num_bytes 	5780
#define flexidag_openseg_prim_split_18___pvcn_883__dram_size_num_bytes 	5824

/* flexidag_openseg_prim_split_18 SMB_input __pvcn_884_ */
#define flexidag_openseg_prim_split_18___pvcn_884__cnngen_demangled_name 	"__pvcn_884_"
#define flexidag_openseg_prim_split_18___pvcn_884__is_constant 	1
#define flexidag_openseg_prim_split_18___pvcn_884__has_init_data 	1
#define flexidag_openseg_prim_split_18___pvcn_884__is_variable_scalar 	0
#define flexidag_openseg_prim_split_18___pvcn_884__is_bitvector 	0
#define flexidag_openseg_prim_split_18___pvcn_884__is_rlz 	0
#define flexidag_openseg_prim_split_18___pvcn_884__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18___pvcn_884__byte_offset 	312	/* 0x00000138 */
#define flexidag_openseg_prim_split_18___pvcn_884__vbase_byte_offset 	316	/* 0x0000013c */
#define flexidag_openseg_prim_split_18___pvcn_884__dbase_byte_offset 	340	/* 0x00000154 */
#define flexidag_openseg_prim_split_18___pvcn_884__dpitchm1_byte_offset 	344	/* 0x00000158 */
#define flexidag_openseg_prim_split_18___pvcn_884__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18___pvcn_884__W 	96
#define flexidag_openseg_prim_split_18___pvcn_884__H 	1
#define flexidag_openseg_prim_split_18___pvcn_884__D 	1
#define flexidag_openseg_prim_split_18___pvcn_884__P 	1
#define flexidag_openseg_prim_split_18___pvcn_884__data_num_bytes 	1
#define flexidag_openseg_prim_split_18___pvcn_884__denable 	1
#define flexidag_openseg_prim_split_18___pvcn_884__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_18___pvcn_884__dram_format 	0
#define flexidag_openseg_prim_split_18___pvcn_884__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_18___pvcn_884__tile_width 	1
#define flexidag_openseg_prim_split_18___pvcn_884__tile_height 	1
#define flexidag_openseg_prim_split_18___pvcn_884__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_18___pvcn_884__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_18 SMB_input __pvcn_890_ */
#define flexidag_openseg_prim_split_18___pvcn_890__cnngen_demangled_name 	"__pvcn_890_"
#define flexidag_openseg_prim_split_18___pvcn_890__is_constant 	1
#define flexidag_openseg_prim_split_18___pvcn_890__has_init_data 	1
#define flexidag_openseg_prim_split_18___pvcn_890__is_variable_scalar 	0
#define flexidag_openseg_prim_split_18___pvcn_890__is_bitvector 	0
#define flexidag_openseg_prim_split_18___pvcn_890__is_rlz 	0
#define flexidag_openseg_prim_split_18___pvcn_890__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18___pvcn_890__byte_offset 	352	/* 0x00000160 */
#define flexidag_openseg_prim_split_18___pvcn_890__vbase_byte_offset 	356	/* 0x00000164 */
#define flexidag_openseg_prim_split_18___pvcn_890__dbase_byte_offset 	380	/* 0x0000017c */
#define flexidag_openseg_prim_split_18___pvcn_890__dpitchm1_byte_offset 	384	/* 0x00000180 */
#define flexidag_openseg_prim_split_18___pvcn_890__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18___pvcn_890__W 	23124
#define flexidag_openseg_prim_split_18___pvcn_890__H 	1
#define flexidag_openseg_prim_split_18___pvcn_890__D 	1
#define flexidag_openseg_prim_split_18___pvcn_890__P 	1
#define flexidag_openseg_prim_split_18___pvcn_890__data_num_bytes 	1
#define flexidag_openseg_prim_split_18___pvcn_890__denable 	1
#define flexidag_openseg_prim_split_18___pvcn_890__dpitch_num_bytes 	23168
#define flexidag_openseg_prim_split_18___pvcn_890__dram_format 	0
#define flexidag_openseg_prim_split_18___pvcn_890__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_18___pvcn_890__tile_width 	1
#define flexidag_openseg_prim_split_18___pvcn_890__tile_height 	1
#define flexidag_openseg_prim_split_18___pvcn_890__vmem_buffer_num_bytes 	23124
#define flexidag_openseg_prim_split_18___pvcn_890__dram_size_num_bytes 	23168

/* flexidag_openseg_prim_split_18 SMB_input __pvcn_891_ */
#define flexidag_openseg_prim_split_18___pvcn_891__cnngen_demangled_name 	"__pvcn_891_"
#define flexidag_openseg_prim_split_18___pvcn_891__is_constant 	1
#define flexidag_openseg_prim_split_18___pvcn_891__has_init_data 	1
#define flexidag_openseg_prim_split_18___pvcn_891__is_variable_scalar 	0
#define flexidag_openseg_prim_split_18___pvcn_891__is_bitvector 	0
#define flexidag_openseg_prim_split_18___pvcn_891__is_rlz 	0
#define flexidag_openseg_prim_split_18___pvcn_891__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18___pvcn_891__byte_offset 	392	/* 0x00000188 */
#define flexidag_openseg_prim_split_18___pvcn_891__vbase_byte_offset 	396	/* 0x0000018c */
#define flexidag_openseg_prim_split_18___pvcn_891__dbase_byte_offset 	420	/* 0x000001a4 */
#define flexidag_openseg_prim_split_18___pvcn_891__dpitchm1_byte_offset 	424	/* 0x000001a8 */
#define flexidag_openseg_prim_split_18___pvcn_891__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18___pvcn_891__W 	640
#define flexidag_openseg_prim_split_18___pvcn_891__H 	1
#define flexidag_openseg_prim_split_18___pvcn_891__D 	1
#define flexidag_openseg_prim_split_18___pvcn_891__P 	1
#define flexidag_openseg_prim_split_18___pvcn_891__data_num_bytes 	1
#define flexidag_openseg_prim_split_18___pvcn_891__denable 	1
#define flexidag_openseg_prim_split_18___pvcn_891__dpitch_num_bytes 	640
#define flexidag_openseg_prim_split_18___pvcn_891__dram_format 	0
#define flexidag_openseg_prim_split_18___pvcn_891__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_18___pvcn_891__tile_width 	1
#define flexidag_openseg_prim_split_18___pvcn_891__tile_height 	1
#define flexidag_openseg_prim_split_18___pvcn_891__vmem_buffer_num_bytes 	640
#define flexidag_openseg_prim_split_18___pvcn_891__dram_size_num_bytes 	640

/* flexidag_openseg_prim_split_18 SMB_input __pvcn_894_ */
#define flexidag_openseg_prim_split_18___pvcn_894__cnngen_demangled_name 	"__pvcn_894_"
#define flexidag_openseg_prim_split_18___pvcn_894__is_constant 	1
#define flexidag_openseg_prim_split_18___pvcn_894__has_init_data 	1
#define flexidag_openseg_prim_split_18___pvcn_894__is_variable_scalar 	0
#define flexidag_openseg_prim_split_18___pvcn_894__is_bitvector 	0
#define flexidag_openseg_prim_split_18___pvcn_894__is_rlz 	0
#define flexidag_openseg_prim_split_18___pvcn_894__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18___pvcn_894__byte_offset 	432	/* 0x000001b0 */
#define flexidag_openseg_prim_split_18___pvcn_894__vbase_byte_offset 	436	/* 0x000001b4 */
#define flexidag_openseg_prim_split_18___pvcn_894__dbase_byte_offset 	460	/* 0x000001cc */
#define flexidag_openseg_prim_split_18___pvcn_894__dpitchm1_byte_offset 	464	/* 0x000001d0 */
#define flexidag_openseg_prim_split_18___pvcn_894__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18___pvcn_894__W 	5720
#define flexidag_openseg_prim_split_18___pvcn_894__H 	1
#define flexidag_openseg_prim_split_18___pvcn_894__D 	1
#define flexidag_openseg_prim_split_18___pvcn_894__P 	1
#define flexidag_openseg_prim_split_18___pvcn_894__data_num_bytes 	1
#define flexidag_openseg_prim_split_18___pvcn_894__denable 	1
#define flexidag_openseg_prim_split_18___pvcn_894__dpitch_num_bytes 	5760
#define flexidag_openseg_prim_split_18___pvcn_894__dram_format 	0
#define flexidag_openseg_prim_split_18___pvcn_894__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_18___pvcn_894__tile_width 	1
#define flexidag_openseg_prim_split_18___pvcn_894__tile_height 	1
#define flexidag_openseg_prim_split_18___pvcn_894__vmem_buffer_num_bytes 	5720
#define flexidag_openseg_prim_split_18___pvcn_894__dram_size_num_bytes 	5760

/* flexidag_openseg_prim_split_18 SMB_input __pvcn_895_ */
#define flexidag_openseg_prim_split_18___pvcn_895__cnngen_demangled_name 	"__pvcn_895_"
#define flexidag_openseg_prim_split_18___pvcn_895__is_constant 	1
#define flexidag_openseg_prim_split_18___pvcn_895__has_init_data 	1
#define flexidag_openseg_prim_split_18___pvcn_895__is_variable_scalar 	0
#define flexidag_openseg_prim_split_18___pvcn_895__is_bitvector 	0
#define flexidag_openseg_prim_split_18___pvcn_895__is_rlz 	0
#define flexidag_openseg_prim_split_18___pvcn_895__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18___pvcn_895__byte_offset 	472	/* 0x000001d8 */
#define flexidag_openseg_prim_split_18___pvcn_895__vbase_byte_offset 	476	/* 0x000001dc */
#define flexidag_openseg_prim_split_18___pvcn_895__dbase_byte_offset 	500	/* 0x000001f4 */
#define flexidag_openseg_prim_split_18___pvcn_895__dpitchm1_byte_offset 	504	/* 0x000001f8 */
#define flexidag_openseg_prim_split_18___pvcn_895__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18___pvcn_895__W 	96
#define flexidag_openseg_prim_split_18___pvcn_895__H 	1
#define flexidag_openseg_prim_split_18___pvcn_895__D 	1
#define flexidag_openseg_prim_split_18___pvcn_895__P 	1
#define flexidag_openseg_prim_split_18___pvcn_895__data_num_bytes 	1
#define flexidag_openseg_prim_split_18___pvcn_895__denable 	1
#define flexidag_openseg_prim_split_18___pvcn_895__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_18___pvcn_895__dram_format 	0
#define flexidag_openseg_prim_split_18___pvcn_895__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_18___pvcn_895__tile_width 	1
#define flexidag_openseg_prim_split_18___pvcn_895__tile_height 	1
#define flexidag_openseg_prim_split_18___pvcn_895__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_18___pvcn_895__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_18 SMB_input __pvcn_897_ */
#define flexidag_openseg_prim_split_18___pvcn_897__cnngen_demangled_name 	"__pvcn_897_"
#define flexidag_openseg_prim_split_18___pvcn_897__is_constant 	1
#define flexidag_openseg_prim_split_18___pvcn_897__has_init_data 	1
#define flexidag_openseg_prim_split_18___pvcn_897__is_variable_scalar 	0
#define flexidag_openseg_prim_split_18___pvcn_897__is_bitvector 	0
#define flexidag_openseg_prim_split_18___pvcn_897__is_rlz 	0
#define flexidag_openseg_prim_split_18___pvcn_897__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18___pvcn_897__byte_offset 	512	/* 0x00000200 */
#define flexidag_openseg_prim_split_18___pvcn_897__vbase_byte_offset 	516	/* 0x00000204 */
#define flexidag_openseg_prim_split_18___pvcn_897__dbase_byte_offset 	540	/* 0x0000021c */
#define flexidag_openseg_prim_split_18___pvcn_897__dpitchm1_byte_offset 	544	/* 0x00000220 */
#define flexidag_openseg_prim_split_18___pvcn_897__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18___pvcn_897__W 	1400
#define flexidag_openseg_prim_split_18___pvcn_897__H 	1
#define flexidag_openseg_prim_split_18___pvcn_897__D 	1
#define flexidag_openseg_prim_split_18___pvcn_897__P 	1
#define flexidag_openseg_prim_split_18___pvcn_897__data_num_bytes 	1
#define flexidag_openseg_prim_split_18___pvcn_897__denable 	1
#define flexidag_openseg_prim_split_18___pvcn_897__dpitch_num_bytes 	1408
#define flexidag_openseg_prim_split_18___pvcn_897__dram_format 	0
#define flexidag_openseg_prim_split_18___pvcn_897__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_18___pvcn_897__tile_width 	1
#define flexidag_openseg_prim_split_18___pvcn_897__tile_height 	1
#define flexidag_openseg_prim_split_18___pvcn_897__vmem_buffer_num_bytes 	1400
#define flexidag_openseg_prim_split_18___pvcn_897__dram_size_num_bytes 	1408

/* flexidag_openseg_prim_split_18 SMB_input __pvcn_898_ */
#define flexidag_openseg_prim_split_18___pvcn_898__cnngen_demangled_name 	"__pvcn_898_"
#define flexidag_openseg_prim_split_18___pvcn_898__is_constant 	1
#define flexidag_openseg_prim_split_18___pvcn_898__has_init_data 	1
#define flexidag_openseg_prim_split_18___pvcn_898__is_variable_scalar 	0
#define flexidag_openseg_prim_split_18___pvcn_898__is_bitvector 	0
#define flexidag_openseg_prim_split_18___pvcn_898__is_rlz 	0
#define flexidag_openseg_prim_split_18___pvcn_898__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18___pvcn_898__byte_offset 	552	/* 0x00000228 */
#define flexidag_openseg_prim_split_18___pvcn_898__vbase_byte_offset 	556	/* 0x0000022c */
#define flexidag_openseg_prim_split_18___pvcn_898__dbase_byte_offset 	580	/* 0x00000244 */
#define flexidag_openseg_prim_split_18___pvcn_898__dpitchm1_byte_offset 	584	/* 0x00000248 */
#define flexidag_openseg_prim_split_18___pvcn_898__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18___pvcn_898__W 	96
#define flexidag_openseg_prim_split_18___pvcn_898__H 	1
#define flexidag_openseg_prim_split_18___pvcn_898__D 	1
#define flexidag_openseg_prim_split_18___pvcn_898__P 	1
#define flexidag_openseg_prim_split_18___pvcn_898__data_num_bytes 	1
#define flexidag_openseg_prim_split_18___pvcn_898__denable 	1
#define flexidag_openseg_prim_split_18___pvcn_898__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_18___pvcn_898__dram_format 	0
#define flexidag_openseg_prim_split_18___pvcn_898__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_18___pvcn_898__tile_width 	1
#define flexidag_openseg_prim_split_18___pvcn_898__tile_height 	1
#define flexidag_openseg_prim_split_18___pvcn_898__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_18___pvcn_898__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_18 VCB PeleeNet__stage_3_dense_block_0__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_0__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	608	/* 0x00000260 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	616	/* 0x00000268 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	25344

/* flexidag_openseg_prim_split_18 VCB PeleeNet__stage_3_dense_block_0__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_0__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	656	/* 0x00000290 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	664	/* 0x00000298 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	12800

/* flexidag_openseg_prim_split_18 VCB PeleeNet__stage_3_dense_block_0__conv_left_0__Relu */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_0__conv_left_0__Relu"
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Relu_is_rlz 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Relu_byte_offset 	740	/* 0x000002e4 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Relu_vbase_byte_offset 	748	/* 0x000002ec */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_0__Relu_vmem_buffer_num_bytes 	78848

/* flexidag_openseg_prim_split_18 VCB PeleeNet__stage_3_dense_block_0__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_0__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	788	/* 0x00000314 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	796	/* 0x0000031c */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	12800

/* flexidag_openseg_prim_split_18 HMB_output PeleeNet__stage_3_dense_block_0__concat______muli___469 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_0__concat______muli___469"
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_is_main_input_output 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_is_bitvector 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_is_rlz 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_byte_offset 	864	/* 0x00000360 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_vbase_byte_offset 	868	/* 0x00000364 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_dbase_byte_offset 	892	/* 0x0000037c */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_dpitchm1_byte_offset 	896	/* 0x00000380 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_vwidth_minus_one_byte_offset 	880	/* 0x00000370 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_vheight_minus_one_byte_offset 	882	/* 0x00000372 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_drotate_bit_offset 	7110	/* 0x00001bc6 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_hflip_bit_offset 	7111	/* 0x00001bc7 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_vflip_bit_offset 	7112	/* 0x00001bc8 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_dflip_bit_offset 	7113	/* 0x00001bc9 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_pflip_bit_offset 	7114	/* 0x00001bca */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_W 	80
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_H 	32
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_D 	288
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_P 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_data_num_bytes 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_denable 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_dram_format 	3
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_tile_width 	4
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_tile_height 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_vmem_buffer_num_bytes 	96768
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_dram_size_num_bytes 	737280
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_sign 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_datasize 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_expoffset 	5
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_expbits 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_drotate 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_hflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_vflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_dflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_pflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_0__concat______muli___469_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_18 VCB PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___470___1 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___470___1_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___470___1"
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___470___1_is_bitvector 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___470___1_is_rlz 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___470___1_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___470___1_byte_offset 	916	/* 0x00000394 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___470___1_vbase_byte_offset 	924	/* 0x0000039c */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___470___1_vmem_buffer_num_bytes 	40960

/* flexidag_openseg_prim_split_18 VCB PeleeNet__stage_3_dense_block_1__conv_right_0__Relu */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_0__Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_1__conv_right_0__Relu"
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_0__Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_0__Relu_is_rlz 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_0__Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_0__Relu_byte_offset 	1000	/* 0x000003e8 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_0__Relu_vbase_byte_offset 	1008	/* 0x000003f0 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_0__Relu_vmem_buffer_num_bytes 	39424

/* flexidag_openseg_prim_split_18 VCB PeleeNet__stage_3_dense_block_1__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_1__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	1048	/* 0x00000418 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	1056	/* 0x00000420 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	12672

/* flexidag_openseg_prim_split_18 HMB_output PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_main_input_output 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	1096	/* 0x00000448 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	1100	/* 0x0000044c */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dbase_byte_offset 	1124	/* 0x00000464 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_byte_offset 	1128	/* 0x00000468 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_byte_offset 	1112	/* 0x00000458 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_byte_offset 	1114	/* 0x0000045a */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate_bit_offset 	8966	/* 0x00002306 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip_bit_offset 	8967	/* 0x00002307 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip_bit_offset 	8968	/* 0x00002308 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip_bit_offset 	8969	/* 0x00002309 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip_bit_offset 	8970	/* 0x0000230a */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_W 	80
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_H 	32
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_D 	16
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_P 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_data_num_bytes 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_denable 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_format 	3
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_width 	4
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_height 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	5120
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_size_num_bytes 	40960
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_sign 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_datasize 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_expoffset 	5
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_expbits 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_18 HMB_output PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400"
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_is_main_input_output 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_is_bitvector 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_is_rlz 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_byte_offset 	1148	/* 0x0000047c */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_vbase_byte_offset 	1152	/* 0x00000480 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_dbase_byte_offset 	1176	/* 0x00000498 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_dpitchm1_byte_offset 	1180	/* 0x0000049c */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_vwidth_minus_one_byte_offset 	1164	/* 0x0000048c */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_vheight_minus_one_byte_offset 	1166	/* 0x0000048e */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_drotate_bit_offset 	9382	/* 0x000024a6 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_hflip_bit_offset 	9383	/* 0x000024a7 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_vflip_bit_offset 	9384	/* 0x000024a8 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_dflip_bit_offset 	9385	/* 0x000024a9 */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_pflip_bit_offset 	9386	/* 0x000024aa */
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_W 	80
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_H 	32
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_D 	64
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_P 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_data_num_bytes 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_denable 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_dram_format 	3
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_tile_width 	4
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_tile_height 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_vmem_buffer_num_bytes 	10240
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_dram_size_num_bytes 	163840
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_sign 	1
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_datasize 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_expoffset 	4
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_expbits 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_drotate 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_hflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_vflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_dflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_pflip 	0
#define flexidag_openseg_prim_split_18_PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_18 SMB_output __vas_created_terminate__v0 */
#define flexidag_openseg_prim_split_18___vas_created_terminate__v0_cnngen_demangled_name 	"__vas_created_terminate__v0"
#define flexidag_openseg_prim_split_18___vas_created_terminate__v0_is_main_input_output 	0
#define flexidag_openseg_prim_split_18___vas_created_terminate__v0_is_bitvector 	1
#define flexidag_openseg_prim_split_18___vas_created_terminate__v0_is_rlz 	0
#define flexidag_openseg_prim_split_18___vas_created_terminate__v0_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_18___vas_created_terminate__v0_byte_offset 	1188	/* 0x000004a4 */
#define flexidag_openseg_prim_split_18___vas_created_terminate__v0_vbase_byte_offset 	1192	/* 0x000004a8 */
#define flexidag_openseg_prim_split_18___vas_created_terminate__v0_W 	256
#define flexidag_openseg_prim_split_18___vas_created_terminate__v0_H 	3
#define flexidag_openseg_prim_split_18___vas_created_terminate__v0_D 	1
#define flexidag_openseg_prim_split_18___vas_created_terminate__v0_P 	1
#define flexidag_openseg_prim_split_18___vas_created_terminate__v0_data_num_bytes 	1
#define flexidag_openseg_prim_split_18___vas_created_terminate__v0_denable 	0
#define flexidag_openseg_prim_split_18___vas_created_terminate__v0_dram_format 	0
#define flexidag_openseg_prim_split_18___vas_created_terminate__v0_vp_interleave_mode 	1
#define flexidag_openseg_prim_split_18___vas_created_terminate__v0_tile_width 	1
#define flexidag_openseg_prim_split_18___vas_created_terminate__v0_tile_height 	1
#define flexidag_openseg_prim_split_18___vas_created_terminate__v0_vmem_buffer_num_bytes 	96


#endif /* flexidag_openseg_prim_split_18_H */
