////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2020 Ambarella International LP
////////////////////////////////////////////////////////////////////////////////
// This file and its contents ("Software") are protected by intellectual
// property rights including, without limitation, U.S. and/or foreign
// copyrights. This Software is also the confidential and proprietary
// information of Ambarella International LP and its licensors. You may not use,
// reproduce, disclose, distribute, modify, or otherwise prepare derivative
// works of this Software or any portion thereof except pursuant to a signed
// license agreement or nondisclosure agreement with Ambarella International LP
// or its authorized affiliates. In the absence of such an agreement, you agree
// to promptly notify and return this Software to Ambarella International LP.
//
// THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL AMBARELLA INTERNATIONAL LP OR ITS AFFILIATES BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR MALFUNCTION;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
// OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
// ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////
#ifndef flexidag_openseg_prim_split_14_H
#define flexidag_openseg_prim_split_14_H

#define vas_gen_header_version                  	7

/* dag name */
#define flexidag_openseg_prim_split_14_DAG_NAME 	"flexidag_openseg_prim_split_14"

/* VDG file info */
#define flexidag_openseg_prim_split_14_vdg_name 	"flexidag_openseg_split_14.vdg"

/* VDG DAG memory info */
#define flexidag_openseg_prim_split_14_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_14_byte_size 	532	/* 0x00000214 */
#define flexidag_openseg_prim_split_14_preferred_dram_xfer_size 	1

/* flexidag_openseg_prim_split_14 VMEM info */
#define flexidag_openseg_prim_split_14_use_ping_pong_vmem 	0
#define flexidag_openseg_prim_split_14_VMEM_start 	4096	/* 0x00001000 */
#define flexidag_openseg_prim_split_14_VMEM_end 	508192	/* 0x0007c120 */
#define flexidag_openseg_prim_split_14_image_start 	458848	/* 0x00070060 */
#define flexidag_openseg_prim_split_14_image_size 	49876	/* 0x0000c2d4 */
#define flexidag_openseg_prim_split_14_dagbin_start 	508192	/* 0x0007c120 */

/* flexidag_openseg_prim_split_14 DAG info */
#define flexidag_openseg_prim_split_14_estimated_cycles 	492337
#define flexidag_openseg_prim_split_14_ddi_byte_size 	0	/* 0x00000000 */

/*******************************************************************************
 * DAG byte offset info for HMB/SMB/VCB and their fields
 * in DAG 'flexidag_openseg_prim_split_14' in source file 'pre_split13_flexidag_openseg_split_0.vas'
 ******************************************************************************/
/* flexidag_openseg_prim_split_14 HMB_input PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_main_input_output 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_constant 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_has_init_data 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_variable_scalar 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_ddi_byte_size 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	4	/* 0x00000004 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dbase_byte_offset 	28	/* 0x0000001c */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_byte_offset 	32	/* 0x00000020 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_byte_offset 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_byte_offset 	18	/* 0x00000012 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate_bit_offset 	198	/* 0x000000c6 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip_bit_offset 	199	/* 0x000000c7 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip_bit_offset 	200	/* 0x000000c8 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip_bit_offset 	201	/* 0x000000c9 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip_bit_offset 	202	/* 0x000000ca */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_W 	160
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_H 	64
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_D 	16
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_P 	1
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_data_num_bytes 	1
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_denable 	1
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_format 	3
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_width 	4
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_height 	1
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	43008
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_size_num_bytes 	163840
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_sign 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_datasize 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_expoffset 	5
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_expbits 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_14 HMB_input PeleeNet__stage_2_dense_block_2__concat___muli___462 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_2__concat___muli___462"
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_is_main_input_output 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_is_constant 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_has_init_data 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_is_variable_scalar 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_ddi_byte_size 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_is_bitvector 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_is_rlz 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_byte_offset 	36	/* 0x00000024 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_vbase_byte_offset 	40	/* 0x00000028 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_dbase_byte_offset 	64	/* 0x00000040 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_dpitchm1_byte_offset 	68	/* 0x00000044 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_vwidth_minus_one_byte_offset 	52	/* 0x00000034 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_vheight_minus_one_byte_offset 	54	/* 0x00000036 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_drotate_bit_offset 	486	/* 0x000001e6 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_hflip_bit_offset 	487	/* 0x000001e7 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_vflip_bit_offset 	488	/* 0x000001e8 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_dflip_bit_offset 	489	/* 0x000001e9 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_pflip_bit_offset 	490	/* 0x000001ea */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_W 	160
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_H 	64
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_D 	224
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_P 	1
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_data_num_bytes 	1
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_denable 	1
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_dram_format 	3
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_tile_width 	4
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_tile_height 	1
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_vmem_buffer_num_bytes 	28672
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_dram_size_num_bytes 	2293760
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_sign 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_datasize 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_expoffset 	4
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_expbits 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_drotate 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_hflip 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_vflip 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_dflip 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_pflip 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_2__concat___muli___462_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_14 HMB_input PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_main_input_output 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_constant 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_has_init_data 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_variable_scalar 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_ddi_byte_size 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	76	/* 0x0000004c */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	80	/* 0x00000050 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dbase_byte_offset 	104	/* 0x00000068 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_byte_offset 	108	/* 0x0000006c */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_byte_offset 	92	/* 0x0000005c */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_byte_offset 	94	/* 0x0000005e */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate_bit_offset 	806	/* 0x00000326 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip_bit_offset 	807	/* 0x00000327 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip_bit_offset 	808	/* 0x00000328 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip_bit_offset 	809	/* 0x00000329 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip_bit_offset 	810	/* 0x0000032a */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_W 	160
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_H 	64
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_D 	16
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_P 	1
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_data_num_bytes 	1
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_denable 	1
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_format 	3
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_width 	4
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_height 	1
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	20480
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_size_num_bytes 	163840
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_sign 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_datasize 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_expoffset 	4
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_expbits 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_14 SMB_input __pvcn_770_ */
#define flexidag_openseg_prim_split_14___pvcn_770__cnngen_demangled_name 	"__pvcn_770_"
#define flexidag_openseg_prim_split_14___pvcn_770__is_constant 	1
#define flexidag_openseg_prim_split_14___pvcn_770__has_init_data 	1
#define flexidag_openseg_prim_split_14___pvcn_770__is_variable_scalar 	0
#define flexidag_openseg_prim_split_14___pvcn_770__is_bitvector 	0
#define flexidag_openseg_prim_split_14___pvcn_770__is_rlz 	0
#define flexidag_openseg_prim_split_14___pvcn_770__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_14___pvcn_770__byte_offset 	116	/* 0x00000074 */
#define flexidag_openseg_prim_split_14___pvcn_770__vbase_byte_offset 	120	/* 0x00000078 */
#define flexidag_openseg_prim_split_14___pvcn_770__dbase_byte_offset 	144	/* 0x00000090 */
#define flexidag_openseg_prim_split_14___pvcn_770__dpitchm1_byte_offset 	148	/* 0x00000094 */
#define flexidag_openseg_prim_split_14___pvcn_770__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_14___pvcn_770__W 	1620
#define flexidag_openseg_prim_split_14___pvcn_770__H 	1
#define flexidag_openseg_prim_split_14___pvcn_770__D 	1
#define flexidag_openseg_prim_split_14___pvcn_770__P 	1
#define flexidag_openseg_prim_split_14___pvcn_770__data_num_bytes 	1
#define flexidag_openseg_prim_split_14___pvcn_770__denable 	1
#define flexidag_openseg_prim_split_14___pvcn_770__dpitch_num_bytes 	1664
#define flexidag_openseg_prim_split_14___pvcn_770__dram_format 	0
#define flexidag_openseg_prim_split_14___pvcn_770__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_14___pvcn_770__tile_width 	1
#define flexidag_openseg_prim_split_14___pvcn_770__tile_height 	1
#define flexidag_openseg_prim_split_14___pvcn_770__vmem_buffer_num_bytes 	1620
#define flexidag_openseg_prim_split_14___pvcn_770__dram_size_num_bytes 	1664

/* flexidag_openseg_prim_split_14 SMB_input __pvcn_771_ */
#define flexidag_openseg_prim_split_14___pvcn_771__cnngen_demangled_name 	"__pvcn_771_"
#define flexidag_openseg_prim_split_14___pvcn_771__is_constant 	1
#define flexidag_openseg_prim_split_14___pvcn_771__has_init_data 	1
#define flexidag_openseg_prim_split_14___pvcn_771__is_variable_scalar 	0
#define flexidag_openseg_prim_split_14___pvcn_771__is_bitvector 	0
#define flexidag_openseg_prim_split_14___pvcn_771__is_rlz 	0
#define flexidag_openseg_prim_split_14___pvcn_771__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_14___pvcn_771__byte_offset 	152	/* 0x00000098 */
#define flexidag_openseg_prim_split_14___pvcn_771__vbase_byte_offset 	156	/* 0x0000009c */
#define flexidag_openseg_prim_split_14___pvcn_771__dbase_byte_offset 	180	/* 0x000000b4 */
#define flexidag_openseg_prim_split_14___pvcn_771__dpitchm1_byte_offset 	184	/* 0x000000b8 */
#define flexidag_openseg_prim_split_14___pvcn_771__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_14___pvcn_771__W 	96
#define flexidag_openseg_prim_split_14___pvcn_771__H 	1
#define flexidag_openseg_prim_split_14___pvcn_771__D 	1
#define flexidag_openseg_prim_split_14___pvcn_771__P 	1
#define flexidag_openseg_prim_split_14___pvcn_771__data_num_bytes 	1
#define flexidag_openseg_prim_split_14___pvcn_771__denable 	1
#define flexidag_openseg_prim_split_14___pvcn_771__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_14___pvcn_771__dram_format 	0
#define flexidag_openseg_prim_split_14___pvcn_771__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_14___pvcn_771__tile_width 	1
#define flexidag_openseg_prim_split_14___pvcn_771__tile_height 	1
#define flexidag_openseg_prim_split_14___pvcn_771__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_14___pvcn_771__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_14 SMB_input __pvcn_781_ */
#define flexidag_openseg_prim_split_14___pvcn_781__cnngen_demangled_name 	"__pvcn_781_"
#define flexidag_openseg_prim_split_14___pvcn_781__is_constant 	1
#define flexidag_openseg_prim_split_14___pvcn_781__has_init_data 	1
#define flexidag_openseg_prim_split_14___pvcn_781__is_variable_scalar 	0
#define flexidag_openseg_prim_split_14___pvcn_781__is_bitvector 	0
#define flexidag_openseg_prim_split_14___pvcn_781__is_rlz 	0
#define flexidag_openseg_prim_split_14___pvcn_781__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_14___pvcn_781__byte_offset 	192	/* 0x000000c0 */
#define flexidag_openseg_prim_split_14___pvcn_781__vbase_byte_offset 	196	/* 0x000000c4 */
#define flexidag_openseg_prim_split_14___pvcn_781__dbase_byte_offset 	220	/* 0x000000dc */
#define flexidag_openseg_prim_split_14___pvcn_781__dpitchm1_byte_offset 	224	/* 0x000000e0 */
#define flexidag_openseg_prim_split_14___pvcn_781__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_14___pvcn_781__W 	46348
#define flexidag_openseg_prim_split_14___pvcn_781__H 	1
#define flexidag_openseg_prim_split_14___pvcn_781__D 	1
#define flexidag_openseg_prim_split_14___pvcn_781__P 	1
#define flexidag_openseg_prim_split_14___pvcn_781__data_num_bytes 	1
#define flexidag_openseg_prim_split_14___pvcn_781__denable 	1
#define flexidag_openseg_prim_split_14___pvcn_781__dpitch_num_bytes 	46400
#define flexidag_openseg_prim_split_14___pvcn_781__dram_format 	0
#define flexidag_openseg_prim_split_14___pvcn_781__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_14___pvcn_781__tile_width 	1
#define flexidag_openseg_prim_split_14___pvcn_781__tile_height 	1
#define flexidag_openseg_prim_split_14___pvcn_781__vmem_buffer_num_bytes 	46348
#define flexidag_openseg_prim_split_14___pvcn_781__dram_size_num_bytes 	46400

/* flexidag_openseg_prim_split_14 SMB_input __pvcn_782_ */
#define flexidag_openseg_prim_split_14___pvcn_782__cnngen_demangled_name 	"__pvcn_782_"
#define flexidag_openseg_prim_split_14___pvcn_782__is_constant 	1
#define flexidag_openseg_prim_split_14___pvcn_782__has_init_data 	1
#define flexidag_openseg_prim_split_14___pvcn_782__is_variable_scalar 	0
#define flexidag_openseg_prim_split_14___pvcn_782__is_bitvector 	0
#define flexidag_openseg_prim_split_14___pvcn_782__is_rlz 	0
#define flexidag_openseg_prim_split_14___pvcn_782__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_14___pvcn_782__byte_offset 	232	/* 0x000000e8 */
#define flexidag_openseg_prim_split_14___pvcn_782__vbase_byte_offset 	236	/* 0x000000ec */
#define flexidag_openseg_prim_split_14___pvcn_782__dbase_byte_offset 	260	/* 0x00000104 */
#define flexidag_openseg_prim_split_14___pvcn_782__dpitchm1_byte_offset 	264	/* 0x00000108 */
#define flexidag_openseg_prim_split_14___pvcn_782__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_14___pvcn_782__W 	1280
#define flexidag_openseg_prim_split_14___pvcn_782__H 	1
#define flexidag_openseg_prim_split_14___pvcn_782__D 	1
#define flexidag_openseg_prim_split_14___pvcn_782__P 	1
#define flexidag_openseg_prim_split_14___pvcn_782__data_num_bytes 	1
#define flexidag_openseg_prim_split_14___pvcn_782__denable 	1
#define flexidag_openseg_prim_split_14___pvcn_782__dpitch_num_bytes 	1280
#define flexidag_openseg_prim_split_14___pvcn_782__dram_format 	0
#define flexidag_openseg_prim_split_14___pvcn_782__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_14___pvcn_782__tile_width 	1
#define flexidag_openseg_prim_split_14___pvcn_782__tile_height 	1
#define flexidag_openseg_prim_split_14___pvcn_782__vmem_buffer_num_bytes 	1280
#define flexidag_openseg_prim_split_14___pvcn_782__dram_size_num_bytes 	1280

/* flexidag_openseg_prim_split_14 VCB PeleeNet__stage_2_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	288	/* 0x00000120 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	296	/* 0x00000128 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	30720

/* flexidag_openseg_prim_split_14 VCB PeleeNet__stage_2_dense_block_3__concat */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__concat_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_3__concat"
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__concat_is_bitvector 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__concat_is_rlz 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__concat_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__concat_byte_offset 	368	/* 0x00000170 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__concat_vbase_byte_offset 	376	/* 0x00000178 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_dense_block_3__concat_vmem_buffer_num_bytes 	167936

/* flexidag_openseg_prim_split_14 HMB_output PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_main_input_output 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	416	/* 0x000001a0 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	420	/* 0x000001a4 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_dbase_byte_offset 	444	/* 0x000001bc */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_byte_offset 	448	/* 0x000001c0 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_byte_offset 	432	/* 0x000001b0 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_byte_offset 	434	/* 0x000001b2 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate_bit_offset 	3526	/* 0x00000dc6 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip_bit_offset 	3527	/* 0x00000dc7 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip_bit_offset 	3528	/* 0x00000dc8 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip_bit_offset 	3529	/* 0x00000dc9 */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip_bit_offset 	3530	/* 0x00000dca */
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_W 	160
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_H 	64
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_D 	256
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_P 	1
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_data_num_bytes 	1
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_denable 	1
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_format 	3
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_width 	4
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_height 	1
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	163840
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_size_num_bytes 	2621440
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_sign 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_datasize 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_expoffset 	5
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_expbits 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip 	0
#define flexidag_openseg_prim_split_14_PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_14 SMB_output __vas_created_terminate__v0 */
#define flexidag_openseg_prim_split_14___vas_created_terminate__v0_cnngen_demangled_name 	"__vas_created_terminate__v0"
#define flexidag_openseg_prim_split_14___vas_created_terminate__v0_is_main_input_output 	0
#define flexidag_openseg_prim_split_14___vas_created_terminate__v0_is_bitvector 	1
#define flexidag_openseg_prim_split_14___vas_created_terminate__v0_is_rlz 	0
#define flexidag_openseg_prim_split_14___vas_created_terminate__v0_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_14___vas_created_terminate__v0_byte_offset 	456	/* 0x000001c8 */
#define flexidag_openseg_prim_split_14___vas_created_terminate__v0_vbase_byte_offset 	460	/* 0x000001cc */
#define flexidag_openseg_prim_split_14___vas_created_terminate__v0_W 	256
#define flexidag_openseg_prim_split_14___vas_created_terminate__v0_H 	3
#define flexidag_openseg_prim_split_14___vas_created_terminate__v0_D 	1
#define flexidag_openseg_prim_split_14___vas_created_terminate__v0_P 	1
#define flexidag_openseg_prim_split_14___vas_created_terminate__v0_data_num_bytes 	1
#define flexidag_openseg_prim_split_14___vas_created_terminate__v0_denable 	0
#define flexidag_openseg_prim_split_14___vas_created_terminate__v0_dram_format 	0
#define flexidag_openseg_prim_split_14___vas_created_terminate__v0_vp_interleave_mode 	1
#define flexidag_openseg_prim_split_14___vas_created_terminate__v0_tile_width 	1
#define flexidag_openseg_prim_split_14___vas_created_terminate__v0_tile_height 	1
#define flexidag_openseg_prim_split_14___vas_created_terminate__v0_vmem_buffer_num_bytes 	96


#endif /* flexidag_openseg_prim_split_14_H */
