////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2020 Ambarella International LP
////////////////////////////////////////////////////////////////////////////////
// This file and its contents ("Software") are protected by intellectual
// property rights including, without limitation, U.S. and/or foreign
// copyrights. This Software is also the confidential and proprietary
// information of Ambarella International LP and its licensors. You may not use,
// reproduce, disclose, distribute, modify, or otherwise prepare derivative
// works of this Software or any portion thereof except pursuant to a signed
// license agreement or nondisclosure agreement with Ambarella International LP
// or its authorized affiliates. In the absence of such an agreement, you agree
// to promptly notify and return this Software to Ambarella International LP.
//
// THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL AMBARELLA INTERNATIONAL LP OR ITS AFFILIATES BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR MALFUNCTION;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
// OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
// ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////
#ifndef flexidag_openseg_prim_split_29_H
#define flexidag_openseg_prim_split_29_H

#define vas_gen_header_version                  	7

/* dag name */
#define flexidag_openseg_prim_split_29_DAG_NAME 	"flexidag_openseg_prim_split_29"

/* VDG file info */
#define flexidag_openseg_prim_split_29_vdg_name 	"flexidag_openseg_split_29.vdg"

/* VDG DAG memory info */
#define flexidag_openseg_prim_split_29_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_29_byte_size 	796	/* 0x0000031c */
#define flexidag_openseg_prim_split_29_preferred_dram_xfer_size 	1

/* flexidag_openseg_prim_split_29 VMEM info */
#define flexidag_openseg_prim_split_29_use_ping_pong_vmem 	0
#define flexidag_openseg_prim_split_29_VMEM_start 	4096	/* 0x00001000 */
#define flexidag_openseg_prim_split_29_VMEM_end 	512844	/* 0x0007d34c */
#define flexidag_openseg_prim_split_29_image_start 	461152	/* 0x00070960 */
#define flexidag_openseg_prim_split_29_image_size 	52488	/* 0x0000cd08 */
#define flexidag_openseg_prim_split_29_dagbin_start 	512844	/* 0x0007d34c */

/* flexidag_openseg_prim_split_29 DAG info */
#define flexidag_openseg_prim_split_29_estimated_cycles 	141652
#define flexidag_openseg_prim_split_29_ddi_byte_size 	0	/* 0x00000000 */

/*******************************************************************************
 * DAG byte offset info for HMB/SMB/VCB and their fields
 * in DAG 'flexidag_openseg_prim_split_29' in source file 'pre_split20_flexidag_openseg_split_0.vas'
 ******************************************************************************/
/* flexidag_openseg_prim_split_29 SMB_input __pvcn_1006_ */
#define flexidag_openseg_prim_split_29___pvcn_1006__cnngen_demangled_name 	"__pvcn_1006_"
#define flexidag_openseg_prim_split_29___pvcn_1006__is_constant 	1
#define flexidag_openseg_prim_split_29___pvcn_1006__has_init_data 	1
#define flexidag_openseg_prim_split_29___pvcn_1006__is_variable_scalar 	0
#define flexidag_openseg_prim_split_29___pvcn_1006__is_bitvector 	0
#define flexidag_openseg_prim_split_29___pvcn_1006__is_rlz 	0
#define flexidag_openseg_prim_split_29___pvcn_1006__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_29___pvcn_1006__byte_offset 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_29___pvcn_1006__vbase_byte_offset 	4	/* 0x00000004 */
#define flexidag_openseg_prim_split_29___pvcn_1006__dbase_byte_offset 	28	/* 0x0000001c */
#define flexidag_openseg_prim_split_29___pvcn_1006__dpitchm1_byte_offset 	32	/* 0x00000020 */
#define flexidag_openseg_prim_split_29___pvcn_1006__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_29___pvcn_1006__W 	37964
#define flexidag_openseg_prim_split_29___pvcn_1006__H 	1
#define flexidag_openseg_prim_split_29___pvcn_1006__D 	1
#define flexidag_openseg_prim_split_29___pvcn_1006__P 	1
#define flexidag_openseg_prim_split_29___pvcn_1006__data_num_bytes 	1
#define flexidag_openseg_prim_split_29___pvcn_1006__denable 	1
#define flexidag_openseg_prim_split_29___pvcn_1006__dpitch_num_bytes 	38016
#define flexidag_openseg_prim_split_29___pvcn_1006__dram_format 	0
#define flexidag_openseg_prim_split_29___pvcn_1006__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_29___pvcn_1006__tile_width 	1
#define flexidag_openseg_prim_split_29___pvcn_1006__tile_height 	1
#define flexidag_openseg_prim_split_29___pvcn_1006__vmem_buffer_num_bytes 	37964
#define flexidag_openseg_prim_split_29___pvcn_1006__dram_size_num_bytes 	38016

/* flexidag_openseg_prim_split_29 SMB_input __pvcn_1007_ */
#define flexidag_openseg_prim_split_29___pvcn_1007__cnngen_demangled_name 	"__pvcn_1007_"
#define flexidag_openseg_prim_split_29___pvcn_1007__is_constant 	1
#define flexidag_openseg_prim_split_29___pvcn_1007__has_init_data 	1
#define flexidag_openseg_prim_split_29___pvcn_1007__is_variable_scalar 	0
#define flexidag_openseg_prim_split_29___pvcn_1007__is_bitvector 	0
#define flexidag_openseg_prim_split_29___pvcn_1007__is_rlz 	0
#define flexidag_openseg_prim_split_29___pvcn_1007__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_29___pvcn_1007__byte_offset 	36	/* 0x00000024 */
#define flexidag_openseg_prim_split_29___pvcn_1007__vbase_byte_offset 	40	/* 0x00000028 */
#define flexidag_openseg_prim_split_29___pvcn_1007__dbase_byte_offset 	64	/* 0x00000040 */
#define flexidag_openseg_prim_split_29___pvcn_1007__dpitchm1_byte_offset 	68	/* 0x00000044 */
#define flexidag_openseg_prim_split_29___pvcn_1007__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_29___pvcn_1007__W 	640
#define flexidag_openseg_prim_split_29___pvcn_1007__H 	1
#define flexidag_openseg_prim_split_29___pvcn_1007__D 	1
#define flexidag_openseg_prim_split_29___pvcn_1007__P 	1
#define flexidag_openseg_prim_split_29___pvcn_1007__data_num_bytes 	1
#define flexidag_openseg_prim_split_29___pvcn_1007__denable 	1
#define flexidag_openseg_prim_split_29___pvcn_1007__dpitch_num_bytes 	640
#define flexidag_openseg_prim_split_29___pvcn_1007__dram_format 	0
#define flexidag_openseg_prim_split_29___pvcn_1007__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_29___pvcn_1007__tile_width 	1
#define flexidag_openseg_prim_split_29___pvcn_1007__tile_height 	1
#define flexidag_openseg_prim_split_29___pvcn_1007__vmem_buffer_num_bytes 	640
#define flexidag_openseg_prim_split_29___pvcn_1007__dram_size_num_bytes 	640

/* flexidag_openseg_prim_split_29 SMB_input __pvcn_1010_ */
#define flexidag_openseg_prim_split_29___pvcn_1010__cnngen_demangled_name 	"__pvcn_1010_"
#define flexidag_openseg_prim_split_29___pvcn_1010__is_constant 	1
#define flexidag_openseg_prim_split_29___pvcn_1010__has_init_data 	1
#define flexidag_openseg_prim_split_29___pvcn_1010__is_variable_scalar 	0
#define flexidag_openseg_prim_split_29___pvcn_1010__is_bitvector 	0
#define flexidag_openseg_prim_split_29___pvcn_1010__is_rlz 	0
#define flexidag_openseg_prim_split_29___pvcn_1010__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_29___pvcn_1010__byte_offset 	76	/* 0x0000004c */
#define flexidag_openseg_prim_split_29___pvcn_1010__vbase_byte_offset 	80	/* 0x00000050 */
#define flexidag_openseg_prim_split_29___pvcn_1010__dbase_byte_offset 	104	/* 0x00000068 */
#define flexidag_openseg_prim_split_29___pvcn_1010__dpitchm1_byte_offset 	108	/* 0x0000006c */
#define flexidag_openseg_prim_split_29___pvcn_1010__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_29___pvcn_1010__W 	5716
#define flexidag_openseg_prim_split_29___pvcn_1010__H 	1
#define flexidag_openseg_prim_split_29___pvcn_1010__D 	1
#define flexidag_openseg_prim_split_29___pvcn_1010__P 	1
#define flexidag_openseg_prim_split_29___pvcn_1010__data_num_bytes 	1
#define flexidag_openseg_prim_split_29___pvcn_1010__denable 	1
#define flexidag_openseg_prim_split_29___pvcn_1010__dpitch_num_bytes 	5760
#define flexidag_openseg_prim_split_29___pvcn_1010__dram_format 	0
#define flexidag_openseg_prim_split_29___pvcn_1010__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_29___pvcn_1010__tile_width 	1
#define flexidag_openseg_prim_split_29___pvcn_1010__tile_height 	1
#define flexidag_openseg_prim_split_29___pvcn_1010__vmem_buffer_num_bytes 	5716
#define flexidag_openseg_prim_split_29___pvcn_1010__dram_size_num_bytes 	5760

/* flexidag_openseg_prim_split_29 SMB_input __pvcn_1011_ */
#define flexidag_openseg_prim_split_29___pvcn_1011__cnngen_demangled_name 	"__pvcn_1011_"
#define flexidag_openseg_prim_split_29___pvcn_1011__is_constant 	1
#define flexidag_openseg_prim_split_29___pvcn_1011__has_init_data 	1
#define flexidag_openseg_prim_split_29___pvcn_1011__is_variable_scalar 	0
#define flexidag_openseg_prim_split_29___pvcn_1011__is_bitvector 	0
#define flexidag_openseg_prim_split_29___pvcn_1011__is_rlz 	0
#define flexidag_openseg_prim_split_29___pvcn_1011__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_29___pvcn_1011__byte_offset 	116	/* 0x00000074 */
#define flexidag_openseg_prim_split_29___pvcn_1011__vbase_byte_offset 	120	/* 0x00000078 */
#define flexidag_openseg_prim_split_29___pvcn_1011__dbase_byte_offset 	144	/* 0x00000090 */
#define flexidag_openseg_prim_split_29___pvcn_1011__dpitchm1_byte_offset 	148	/* 0x00000094 */
#define flexidag_openseg_prim_split_29___pvcn_1011__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_29___pvcn_1011__W 	96
#define flexidag_openseg_prim_split_29___pvcn_1011__H 	1
#define flexidag_openseg_prim_split_29___pvcn_1011__D 	1
#define flexidag_openseg_prim_split_29___pvcn_1011__P 	1
#define flexidag_openseg_prim_split_29___pvcn_1011__data_num_bytes 	1
#define flexidag_openseg_prim_split_29___pvcn_1011__denable 	1
#define flexidag_openseg_prim_split_29___pvcn_1011__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_29___pvcn_1011__dram_format 	0
#define flexidag_openseg_prim_split_29___pvcn_1011__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_29___pvcn_1011__tile_width 	1
#define flexidag_openseg_prim_split_29___pvcn_1011__tile_height 	1
#define flexidag_openseg_prim_split_29___pvcn_1011__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_29___pvcn_1011__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_29 SMB_input __pvcn_1013_ */
#define flexidag_openseg_prim_split_29___pvcn_1013__cnngen_demangled_name 	"__pvcn_1013_"
#define flexidag_openseg_prim_split_29___pvcn_1013__is_constant 	1
#define flexidag_openseg_prim_split_29___pvcn_1013__has_init_data 	1
#define flexidag_openseg_prim_split_29___pvcn_1013__is_variable_scalar 	0
#define flexidag_openseg_prim_split_29___pvcn_1013__is_bitvector 	0
#define flexidag_openseg_prim_split_29___pvcn_1013__is_rlz 	0
#define flexidag_openseg_prim_split_29___pvcn_1013__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_29___pvcn_1013__byte_offset 	156	/* 0x0000009c */
#define flexidag_openseg_prim_split_29___pvcn_1013__vbase_byte_offset 	160	/* 0x000000a0 */
#define flexidag_openseg_prim_split_29___pvcn_1013__dbase_byte_offset 	184	/* 0x000000b8 */
#define flexidag_openseg_prim_split_29___pvcn_1013__dpitchm1_byte_offset 	188	/* 0x000000bc */
#define flexidag_openseg_prim_split_29___pvcn_1013__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_29___pvcn_1013__W 	1428
#define flexidag_openseg_prim_split_29___pvcn_1013__H 	1
#define flexidag_openseg_prim_split_29___pvcn_1013__D 	1
#define flexidag_openseg_prim_split_29___pvcn_1013__P 	1
#define flexidag_openseg_prim_split_29___pvcn_1013__data_num_bytes 	1
#define flexidag_openseg_prim_split_29___pvcn_1013__denable 	1
#define flexidag_openseg_prim_split_29___pvcn_1013__dpitch_num_bytes 	1472
#define flexidag_openseg_prim_split_29___pvcn_1013__dram_format 	0
#define flexidag_openseg_prim_split_29___pvcn_1013__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_29___pvcn_1013__tile_width 	1
#define flexidag_openseg_prim_split_29___pvcn_1013__tile_height 	1
#define flexidag_openseg_prim_split_29___pvcn_1013__vmem_buffer_num_bytes 	1428
#define flexidag_openseg_prim_split_29___pvcn_1013__dram_size_num_bytes 	1472

/* flexidag_openseg_prim_split_29 SMB_input __pvcn_1014_ */
#define flexidag_openseg_prim_split_29___pvcn_1014__cnngen_demangled_name 	"__pvcn_1014_"
#define flexidag_openseg_prim_split_29___pvcn_1014__is_constant 	1
#define flexidag_openseg_prim_split_29___pvcn_1014__has_init_data 	1
#define flexidag_openseg_prim_split_29___pvcn_1014__is_variable_scalar 	0
#define flexidag_openseg_prim_split_29___pvcn_1014__is_bitvector 	0
#define flexidag_openseg_prim_split_29___pvcn_1014__is_rlz 	0
#define flexidag_openseg_prim_split_29___pvcn_1014__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_29___pvcn_1014__byte_offset 	196	/* 0x000000c4 */
#define flexidag_openseg_prim_split_29___pvcn_1014__vbase_byte_offset 	200	/* 0x000000c8 */
#define flexidag_openseg_prim_split_29___pvcn_1014__dbase_byte_offset 	224	/* 0x000000e0 */
#define flexidag_openseg_prim_split_29___pvcn_1014__dpitchm1_byte_offset 	228	/* 0x000000e4 */
#define flexidag_openseg_prim_split_29___pvcn_1014__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_29___pvcn_1014__W 	96
#define flexidag_openseg_prim_split_29___pvcn_1014__H 	1
#define flexidag_openseg_prim_split_29___pvcn_1014__D 	1
#define flexidag_openseg_prim_split_29___pvcn_1014__P 	1
#define flexidag_openseg_prim_split_29___pvcn_1014__data_num_bytes 	1
#define flexidag_openseg_prim_split_29___pvcn_1014__denable 	1
#define flexidag_openseg_prim_split_29___pvcn_1014__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_29___pvcn_1014__dram_format 	0
#define flexidag_openseg_prim_split_29___pvcn_1014__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_29___pvcn_1014__tile_width 	1
#define flexidag_openseg_prim_split_29___pvcn_1014__tile_height 	1
#define flexidag_openseg_prim_split_29___pvcn_1014__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_29___pvcn_1014__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_29 SMB_input __pvcn_1017_ */
#define flexidag_openseg_prim_split_29___pvcn_1017__cnngen_demangled_name 	"__pvcn_1017_"
#define flexidag_openseg_prim_split_29___pvcn_1017__is_constant 	1
#define flexidag_openseg_prim_split_29___pvcn_1017__has_init_data 	1
#define flexidag_openseg_prim_split_29___pvcn_1017__is_variable_scalar 	0
#define flexidag_openseg_prim_split_29___pvcn_1017__is_bitvector 	0
#define flexidag_openseg_prim_split_29___pvcn_1017__is_rlz 	0
#define flexidag_openseg_prim_split_29___pvcn_1017__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_29___pvcn_1017__byte_offset 	236	/* 0x000000ec */
#define flexidag_openseg_prim_split_29___pvcn_1017__vbase_byte_offset 	240	/* 0x000000f0 */
#define flexidag_openseg_prim_split_29___pvcn_1017__dbase_byte_offset 	264	/* 0x00000108 */
#define flexidag_openseg_prim_split_29___pvcn_1017__dpitchm1_byte_offset 	268	/* 0x0000010c */
#define flexidag_openseg_prim_split_29___pvcn_1017__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_29___pvcn_1017__W 	5656
#define flexidag_openseg_prim_split_29___pvcn_1017__H 	1
#define flexidag_openseg_prim_split_29___pvcn_1017__D 	1
#define flexidag_openseg_prim_split_29___pvcn_1017__P 	1
#define flexidag_openseg_prim_split_29___pvcn_1017__data_num_bytes 	1
#define flexidag_openseg_prim_split_29___pvcn_1017__denable 	1
#define flexidag_openseg_prim_split_29___pvcn_1017__dpitch_num_bytes 	5696
#define flexidag_openseg_prim_split_29___pvcn_1017__dram_format 	0
#define flexidag_openseg_prim_split_29___pvcn_1017__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_29___pvcn_1017__tile_width 	1
#define flexidag_openseg_prim_split_29___pvcn_1017__tile_height 	1
#define flexidag_openseg_prim_split_29___pvcn_1017__vmem_buffer_num_bytes 	5656
#define flexidag_openseg_prim_split_29___pvcn_1017__dram_size_num_bytes 	5696

/* flexidag_openseg_prim_split_29 SMB_input __pvcn_1018_ */
#define flexidag_openseg_prim_split_29___pvcn_1018__cnngen_demangled_name 	"__pvcn_1018_"
#define flexidag_openseg_prim_split_29___pvcn_1018__is_constant 	1
#define flexidag_openseg_prim_split_29___pvcn_1018__has_init_data 	1
#define flexidag_openseg_prim_split_29___pvcn_1018__is_variable_scalar 	0
#define flexidag_openseg_prim_split_29___pvcn_1018__is_bitvector 	0
#define flexidag_openseg_prim_split_29___pvcn_1018__is_rlz 	0
#define flexidag_openseg_prim_split_29___pvcn_1018__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_29___pvcn_1018__byte_offset 	276	/* 0x00000114 */
#define flexidag_openseg_prim_split_29___pvcn_1018__vbase_byte_offset 	280	/* 0x00000118 */
#define flexidag_openseg_prim_split_29___pvcn_1018__dbase_byte_offset 	304	/* 0x00000130 */
#define flexidag_openseg_prim_split_29___pvcn_1018__dpitchm1_byte_offset 	308	/* 0x00000134 */
#define flexidag_openseg_prim_split_29___pvcn_1018__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_29___pvcn_1018__W 	96
#define flexidag_openseg_prim_split_29___pvcn_1018__H 	1
#define flexidag_openseg_prim_split_29___pvcn_1018__D 	1
#define flexidag_openseg_prim_split_29___pvcn_1018__P 	1
#define flexidag_openseg_prim_split_29___pvcn_1018__data_num_bytes 	1
#define flexidag_openseg_prim_split_29___pvcn_1018__denable 	1
#define flexidag_openseg_prim_split_29___pvcn_1018__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_29___pvcn_1018__dram_format 	0
#define flexidag_openseg_prim_split_29___pvcn_1018__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_29___pvcn_1018__tile_width 	1
#define flexidag_openseg_prim_split_29___pvcn_1018__tile_height 	1
#define flexidag_openseg_prim_split_29___pvcn_1018__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_29___pvcn_1018__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_29 HMB_input PeleeNet__stage_3_dense_block_6__concat______muli___487 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_6__concat______muli___487"
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_is_main_input_output 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_is_constant 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_has_init_data 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_is_variable_scalar 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_ddi_byte_size 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_is_bitvector 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_is_rlz 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_byte_offset 	316	/* 0x0000013c */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_vbase_byte_offset 	320	/* 0x00000140 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_dbase_byte_offset 	344	/* 0x00000158 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_dpitchm1_byte_offset 	348	/* 0x0000015c */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_vwidth_minus_one_byte_offset 	332	/* 0x0000014c */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_vheight_minus_one_byte_offset 	334	/* 0x0000014e */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_drotate_bit_offset 	2726	/* 0x00000aa6 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_hflip_bit_offset 	2727	/* 0x00000aa7 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_vflip_bit_offset 	2728	/* 0x00000aa8 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_dflip_bit_offset 	2729	/* 0x00000aa9 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_pflip_bit_offset 	2730	/* 0x00000aaa */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_W 	80
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_H 	32
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_D 	480
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_P 	1
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_data_num_bytes 	1
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_denable 	1
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_dram_format 	3
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_tile_width 	4
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_tile_height 	1
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_vmem_buffer_num_bytes 	161280
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_dram_size_num_bytes 	1228800
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_sign 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_datasize 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_expoffset 	5
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_expbits 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_drotate 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_hflip 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_vflip 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_dflip 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_pflip 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_6__concat______muli___487_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_29 VCB PeleeNet__stage_3_dense_block_7__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___488___9 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___488___9_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_7__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___488___9"
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___488___9_is_bitvector 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___488___9_is_rlz 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___488___9_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___488___9_byte_offset 	368	/* 0x00000170 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___488___9_vbase_byte_offset 	376	/* 0x00000178 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___488___9_vmem_buffer_num_bytes 	81920

/* flexidag_openseg_prim_split_29 VCB PeleeNet__stage_3_dense_block_7__conv_right_0__Relu */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_0__Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_7__conv_right_0__Relu"
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_0__Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_0__Relu_is_rlz 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_0__Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_0__Relu_byte_offset 	452	/* 0x000001c4 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_0__Relu_vbase_byte_offset 	460	/* 0x000001cc */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_0__Relu_vmem_buffer_num_bytes 	78848

/* flexidag_openseg_prim_split_29 VCB PeleeNet__stage_3_dense_block_7__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_7__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	500	/* 0x000001f4 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	508	/* 0x000001fc */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	25344

/* flexidag_openseg_prim_split_29 HMB_output PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_main_input_output 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	548	/* 0x00000224 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	552	/* 0x00000228 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dbase_byte_offset 	576	/* 0x00000240 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_byte_offset 	580	/* 0x00000244 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_byte_offset 	564	/* 0x00000234 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_byte_offset 	566	/* 0x00000236 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate_bit_offset 	4582	/* 0x000011e6 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip_bit_offset 	4583	/* 0x000011e7 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip_bit_offset 	4584	/* 0x000011e8 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip_bit_offset 	4585	/* 0x000011e9 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip_bit_offset 	4586	/* 0x000011ea */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_W 	80
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_H 	32
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_D 	16
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_P 	1
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_data_num_bytes 	1
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_denable 	1
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_format 	3
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_width 	4
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_height 	1
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	20480
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_size_num_bytes 	40960
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_sign 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_datasize 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_expoffset 	5
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_expbits 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_29 VCB PeleeNet__stage_3_dense_block_7__conv_left_0__Relu */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_0__Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_7__conv_left_0__Relu"
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_0__Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_0__Relu_is_rlz 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_0__Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_0__Relu_byte_offset 	632	/* 0x00000278 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_0__Relu_vbase_byte_offset 	640	/* 0x00000280 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_0__Relu_vmem_buffer_num_bytes 	78848

/* flexidag_openseg_prim_split_29 HMB_output PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_main_input_output 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	680	/* 0x000002a8 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	684	/* 0x000002ac */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dbase_byte_offset 	708	/* 0x000002c4 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_byte_offset 	712	/* 0x000002c8 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_byte_offset 	696	/* 0x000002b8 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_byte_offset 	698	/* 0x000002ba */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate_bit_offset 	5638	/* 0x00001606 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip_bit_offset 	5639	/* 0x00001607 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip_bit_offset 	5640	/* 0x00001608 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip_bit_offset 	5641	/* 0x00001609 */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip_bit_offset 	5642	/* 0x0000160a */
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_W 	80
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_H 	32
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_D 	16
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_P 	1
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_data_num_bytes 	1
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_denable 	1
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_format 	3
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_width 	4
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_height 	1
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	10240
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_size_num_bytes 	40960
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_sign 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_datasize 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_expoffset 	5
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_expbits 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip 	0
#define flexidag_openseg_prim_split_29_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_29 SMB_output __vas_created_terminate__v0 */
#define flexidag_openseg_prim_split_29___vas_created_terminate__v0_cnngen_demangled_name 	"__vas_created_terminate__v0"
#define flexidag_openseg_prim_split_29___vas_created_terminate__v0_is_main_input_output 	0
#define flexidag_openseg_prim_split_29___vas_created_terminate__v0_is_bitvector 	1
#define flexidag_openseg_prim_split_29___vas_created_terminate__v0_is_rlz 	0
#define flexidag_openseg_prim_split_29___vas_created_terminate__v0_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_29___vas_created_terminate__v0_byte_offset 	720	/* 0x000002d0 */
#define flexidag_openseg_prim_split_29___vas_created_terminate__v0_vbase_byte_offset 	724	/* 0x000002d4 */
#define flexidag_openseg_prim_split_29___vas_created_terminate__v0_W 	256
#define flexidag_openseg_prim_split_29___vas_created_terminate__v0_H 	3
#define flexidag_openseg_prim_split_29___vas_created_terminate__v0_D 	1
#define flexidag_openseg_prim_split_29___vas_created_terminate__v0_P 	1
#define flexidag_openseg_prim_split_29___vas_created_terminate__v0_data_num_bytes 	1
#define flexidag_openseg_prim_split_29___vas_created_terminate__v0_denable 	0
#define flexidag_openseg_prim_split_29___vas_created_terminate__v0_dram_format 	0
#define flexidag_openseg_prim_split_29___vas_created_terminate__v0_vp_interleave_mode 	1
#define flexidag_openseg_prim_split_29___vas_created_terminate__v0_tile_width 	1
#define flexidag_openseg_prim_split_29___vas_created_terminate__v0_tile_height 	1
#define flexidag_openseg_prim_split_29___vas_created_terminate__v0_vmem_buffer_num_bytes 	96


#endif /* flexidag_openseg_prim_split_29_H */
