////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2020 Ambarella International LP
////////////////////////////////////////////////////////////////////////////////
// This file and its contents ("Software") are protected by intellectual
// property rights including, without limitation, U.S. and/or foreign
// copyrights. This Software is also the confidential and proprietary
// information of Ambarella International LP and its licensors. You may not use,
// reproduce, disclose, distribute, modify, or otherwise prepare derivative
// works of this Software or any portion thereof except pursuant to a signed
// license agreement or nondisclosure agreement with Ambarella International LP
// or its authorized affiliates. In the absence of such an agreement, you agree
// to promptly notify and return this Software to Ambarella International LP.
//
// THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL AMBARELLA INTERNATIONAL LP OR ITS AFFILIATES BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR MALFUNCTION;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
// OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
// ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////
#ifndef flexidag_openseg_prim_split_23_H
#define flexidag_openseg_prim_split_23_H

#define vas_gen_header_version                  	7

/* dag name */
#define flexidag_openseg_prim_split_23_DAG_NAME 	"flexidag_openseg_prim_split_23"

/* VDG file info */
#define flexidag_openseg_prim_split_23_vdg_name 	"flexidag_openseg_split_23.vdg"

/* VDG DAG memory info */
#define flexidag_openseg_prim_split_23_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_23_byte_size 	856	/* 0x00000358 */
#define flexidag_openseg_prim_split_23_preferred_dram_xfer_size 	1

/* flexidag_openseg_prim_split_23 VMEM info */
#define flexidag_openseg_prim_split_23_use_ping_pong_vmem 	0
#define flexidag_openseg_prim_split_23_VMEM_start 	4096	/* 0x00001000 */
#define flexidag_openseg_prim_split_23_VMEM_end 	504100	/* 0x0007b124 */
#define flexidag_openseg_prim_split_23_image_start 	459616	/* 0x00070360 */
#define flexidag_openseg_prim_split_23_image_size 	45340	/* 0x0000b11c */
#define flexidag_openseg_prim_split_23_dagbin_start 	504100	/* 0x0007b124 */

/* flexidag_openseg_prim_split_23 DAG info */
#define flexidag_openseg_prim_split_23_estimated_cycles 	146661
#define flexidag_openseg_prim_split_23_ddi_byte_size 	0	/* 0x00000000 */

/*******************************************************************************
 * DAG byte offset info for HMB/SMB/VCB and their fields
 * in DAG 'flexidag_openseg_prim_split_23' in source file 'pre_split17_flexidag_openseg_split_0.vas'
 ******************************************************************************/
/* flexidag_openseg_prim_split_23 SMB_input __pvcn_946_ */
#define flexidag_openseg_prim_split_23___pvcn_946__cnngen_demangled_name 	"__pvcn_946_"
#define flexidag_openseg_prim_split_23___pvcn_946__is_constant 	1
#define flexidag_openseg_prim_split_23___pvcn_946__has_init_data 	1
#define flexidag_openseg_prim_split_23___pvcn_946__is_variable_scalar 	0
#define flexidag_openseg_prim_split_23___pvcn_946__is_bitvector 	0
#define flexidag_openseg_prim_split_23___pvcn_946__is_rlz 	0
#define flexidag_openseg_prim_split_23___pvcn_946__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_23___pvcn_946__byte_offset 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_23___pvcn_946__vbase_byte_offset 	4	/* 0x00000004 */
#define flexidag_openseg_prim_split_23___pvcn_946__dbase_byte_offset 	28	/* 0x0000001c */
#define flexidag_openseg_prim_split_23___pvcn_946__dpitchm1_byte_offset 	32	/* 0x00000020 */
#define flexidag_openseg_prim_split_23___pvcn_946__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_23___pvcn_946__W 	30628
#define flexidag_openseg_prim_split_23___pvcn_946__H 	1
#define flexidag_openseg_prim_split_23___pvcn_946__D 	1
#define flexidag_openseg_prim_split_23___pvcn_946__P 	1
#define flexidag_openseg_prim_split_23___pvcn_946__data_num_bytes 	1
#define flexidag_openseg_prim_split_23___pvcn_946__denable 	1
#define flexidag_openseg_prim_split_23___pvcn_946__dpitch_num_bytes 	30656
#define flexidag_openseg_prim_split_23___pvcn_946__dram_format 	0
#define flexidag_openseg_prim_split_23___pvcn_946__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_23___pvcn_946__tile_width 	1
#define flexidag_openseg_prim_split_23___pvcn_946__tile_height 	1
#define flexidag_openseg_prim_split_23___pvcn_946__vmem_buffer_num_bytes 	30628
#define flexidag_openseg_prim_split_23___pvcn_946__dram_size_num_bytes 	30656

/* flexidag_openseg_prim_split_23 SMB_input __pvcn_947_ */
#define flexidag_openseg_prim_split_23___pvcn_947__cnngen_demangled_name 	"__pvcn_947_"
#define flexidag_openseg_prim_split_23___pvcn_947__is_constant 	1
#define flexidag_openseg_prim_split_23___pvcn_947__has_init_data 	1
#define flexidag_openseg_prim_split_23___pvcn_947__is_variable_scalar 	0
#define flexidag_openseg_prim_split_23___pvcn_947__is_bitvector 	0
#define flexidag_openseg_prim_split_23___pvcn_947__is_rlz 	0
#define flexidag_openseg_prim_split_23___pvcn_947__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_23___pvcn_947__byte_offset 	36	/* 0x00000024 */
#define flexidag_openseg_prim_split_23___pvcn_947__vbase_byte_offset 	40	/* 0x00000028 */
#define flexidag_openseg_prim_split_23___pvcn_947__dbase_byte_offset 	64	/* 0x00000040 */
#define flexidag_openseg_prim_split_23___pvcn_947__dpitchm1_byte_offset 	68	/* 0x00000044 */
#define flexidag_openseg_prim_split_23___pvcn_947__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_23___pvcn_947__W 	640
#define flexidag_openseg_prim_split_23___pvcn_947__H 	1
#define flexidag_openseg_prim_split_23___pvcn_947__D 	1
#define flexidag_openseg_prim_split_23___pvcn_947__P 	1
#define flexidag_openseg_prim_split_23___pvcn_947__data_num_bytes 	1
#define flexidag_openseg_prim_split_23___pvcn_947__denable 	1
#define flexidag_openseg_prim_split_23___pvcn_947__dpitch_num_bytes 	640
#define flexidag_openseg_prim_split_23___pvcn_947__dram_format 	0
#define flexidag_openseg_prim_split_23___pvcn_947__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_23___pvcn_947__tile_width 	1
#define flexidag_openseg_prim_split_23___pvcn_947__tile_height 	1
#define flexidag_openseg_prim_split_23___pvcn_947__vmem_buffer_num_bytes 	640
#define flexidag_openseg_prim_split_23___pvcn_947__dram_size_num_bytes 	640

/* flexidag_openseg_prim_split_23 SMB_input __pvcn_952_ */
#define flexidag_openseg_prim_split_23___pvcn_952__cnngen_demangled_name 	"__pvcn_952_"
#define flexidag_openseg_prim_split_23___pvcn_952__is_constant 	1
#define flexidag_openseg_prim_split_23___pvcn_952__has_init_data 	1
#define flexidag_openseg_prim_split_23___pvcn_952__is_variable_scalar 	0
#define flexidag_openseg_prim_split_23___pvcn_952__is_bitvector 	0
#define flexidag_openseg_prim_split_23___pvcn_952__is_rlz 	0
#define flexidag_openseg_prim_split_23___pvcn_952__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_23___pvcn_952__byte_offset 	88	/* 0x00000058 */
#define flexidag_openseg_prim_split_23___pvcn_952__vbase_byte_offset 	92	/* 0x0000005c */
#define flexidag_openseg_prim_split_23___pvcn_952__dbase_byte_offset 	116	/* 0x00000074 */
#define flexidag_openseg_prim_split_23___pvcn_952__dpitchm1_byte_offset 	120	/* 0x00000078 */
#define flexidag_openseg_prim_split_23___pvcn_952__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_23___pvcn_952__W 	5728
#define flexidag_openseg_prim_split_23___pvcn_952__H 	1
#define flexidag_openseg_prim_split_23___pvcn_952__D 	1
#define flexidag_openseg_prim_split_23___pvcn_952__P 	1
#define flexidag_openseg_prim_split_23___pvcn_952__data_num_bytes 	1
#define flexidag_openseg_prim_split_23___pvcn_952__denable 	1
#define flexidag_openseg_prim_split_23___pvcn_952__dpitch_num_bytes 	5760
#define flexidag_openseg_prim_split_23___pvcn_952__dram_format 	0
#define flexidag_openseg_prim_split_23___pvcn_952__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_23___pvcn_952__tile_width 	1
#define flexidag_openseg_prim_split_23___pvcn_952__tile_height 	1
#define flexidag_openseg_prim_split_23___pvcn_952__vmem_buffer_num_bytes 	5728
#define flexidag_openseg_prim_split_23___pvcn_952__dram_size_num_bytes 	5760

/* flexidag_openseg_prim_split_23 SMB_input __pvcn_953_ */
#define flexidag_openseg_prim_split_23___pvcn_953__cnngen_demangled_name 	"__pvcn_953_"
#define flexidag_openseg_prim_split_23___pvcn_953__is_constant 	1
#define flexidag_openseg_prim_split_23___pvcn_953__has_init_data 	1
#define flexidag_openseg_prim_split_23___pvcn_953__is_variable_scalar 	0
#define flexidag_openseg_prim_split_23___pvcn_953__is_bitvector 	0
#define flexidag_openseg_prim_split_23___pvcn_953__is_rlz 	0
#define flexidag_openseg_prim_split_23___pvcn_953__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_23___pvcn_953__byte_offset 	128	/* 0x00000080 */
#define flexidag_openseg_prim_split_23___pvcn_953__vbase_byte_offset 	132	/* 0x00000084 */
#define flexidag_openseg_prim_split_23___pvcn_953__dbase_byte_offset 	156	/* 0x0000009c */
#define flexidag_openseg_prim_split_23___pvcn_953__dpitchm1_byte_offset 	160	/* 0x000000a0 */
#define flexidag_openseg_prim_split_23___pvcn_953__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_23___pvcn_953__W 	96
#define flexidag_openseg_prim_split_23___pvcn_953__H 	1
#define flexidag_openseg_prim_split_23___pvcn_953__D 	1
#define flexidag_openseg_prim_split_23___pvcn_953__P 	1
#define flexidag_openseg_prim_split_23___pvcn_953__data_num_bytes 	1
#define flexidag_openseg_prim_split_23___pvcn_953__denable 	1
#define flexidag_openseg_prim_split_23___pvcn_953__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_23___pvcn_953__dram_format 	0
#define flexidag_openseg_prim_split_23___pvcn_953__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_23___pvcn_953__tile_width 	1
#define flexidag_openseg_prim_split_23___pvcn_953__tile_height 	1
#define flexidag_openseg_prim_split_23___pvcn_953__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_23___pvcn_953__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_23 SMB_input __pvcn_955_ */
#define flexidag_openseg_prim_split_23___pvcn_955__cnngen_demangled_name 	"__pvcn_955_"
#define flexidag_openseg_prim_split_23___pvcn_955__is_constant 	1
#define flexidag_openseg_prim_split_23___pvcn_955__has_init_data 	1
#define flexidag_openseg_prim_split_23___pvcn_955__is_variable_scalar 	0
#define flexidag_openseg_prim_split_23___pvcn_955__is_bitvector 	0
#define flexidag_openseg_prim_split_23___pvcn_955__is_rlz 	0
#define flexidag_openseg_prim_split_23___pvcn_955__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_23___pvcn_955__byte_offset 	168	/* 0x000000a8 */
#define flexidag_openseg_prim_split_23___pvcn_955__vbase_byte_offset 	172	/* 0x000000ac */
#define flexidag_openseg_prim_split_23___pvcn_955__dbase_byte_offset 	196	/* 0x000000c4 */
#define flexidag_openseg_prim_split_23___pvcn_955__dpitchm1_byte_offset 	200	/* 0x000000c8 */
#define flexidag_openseg_prim_split_23___pvcn_955__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_23___pvcn_955__W 	1412
#define flexidag_openseg_prim_split_23___pvcn_955__H 	1
#define flexidag_openseg_prim_split_23___pvcn_955__D 	1
#define flexidag_openseg_prim_split_23___pvcn_955__P 	1
#define flexidag_openseg_prim_split_23___pvcn_955__data_num_bytes 	1
#define flexidag_openseg_prim_split_23___pvcn_955__denable 	1
#define flexidag_openseg_prim_split_23___pvcn_955__dpitch_num_bytes 	1472
#define flexidag_openseg_prim_split_23___pvcn_955__dram_format 	0
#define flexidag_openseg_prim_split_23___pvcn_955__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_23___pvcn_955__tile_width 	1
#define flexidag_openseg_prim_split_23___pvcn_955__tile_height 	1
#define flexidag_openseg_prim_split_23___pvcn_955__vmem_buffer_num_bytes 	1412
#define flexidag_openseg_prim_split_23___pvcn_955__dram_size_num_bytes 	1472

/* flexidag_openseg_prim_split_23 SMB_input __pvcn_956_ */
#define flexidag_openseg_prim_split_23___pvcn_956__cnngen_demangled_name 	"__pvcn_956_"
#define flexidag_openseg_prim_split_23___pvcn_956__is_constant 	1
#define flexidag_openseg_prim_split_23___pvcn_956__has_init_data 	1
#define flexidag_openseg_prim_split_23___pvcn_956__is_variable_scalar 	0
#define flexidag_openseg_prim_split_23___pvcn_956__is_bitvector 	0
#define flexidag_openseg_prim_split_23___pvcn_956__is_rlz 	0
#define flexidag_openseg_prim_split_23___pvcn_956__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_23___pvcn_956__byte_offset 	208	/* 0x000000d0 */
#define flexidag_openseg_prim_split_23___pvcn_956__vbase_byte_offset 	212	/* 0x000000d4 */
#define flexidag_openseg_prim_split_23___pvcn_956__dbase_byte_offset 	236	/* 0x000000ec */
#define flexidag_openseg_prim_split_23___pvcn_956__dpitchm1_byte_offset 	240	/* 0x000000f0 */
#define flexidag_openseg_prim_split_23___pvcn_956__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_23___pvcn_956__W 	96
#define flexidag_openseg_prim_split_23___pvcn_956__H 	1
#define flexidag_openseg_prim_split_23___pvcn_956__D 	1
#define flexidag_openseg_prim_split_23___pvcn_956__P 	1
#define flexidag_openseg_prim_split_23___pvcn_956__data_num_bytes 	1
#define flexidag_openseg_prim_split_23___pvcn_956__denable 	1
#define flexidag_openseg_prim_split_23___pvcn_956__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_23___pvcn_956__dram_format 	0
#define flexidag_openseg_prim_split_23___pvcn_956__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_23___pvcn_956__tile_width 	1
#define flexidag_openseg_prim_split_23___pvcn_956__tile_height 	1
#define flexidag_openseg_prim_split_23___pvcn_956__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_23___pvcn_956__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_23 SMB_input __pvcn_959_ */
#define flexidag_openseg_prim_split_23___pvcn_959__cnngen_demangled_name 	"__pvcn_959_"
#define flexidag_openseg_prim_split_23___pvcn_959__is_constant 	1
#define flexidag_openseg_prim_split_23___pvcn_959__has_init_data 	1
#define flexidag_openseg_prim_split_23___pvcn_959__is_variable_scalar 	0
#define flexidag_openseg_prim_split_23___pvcn_959__is_bitvector 	0
#define flexidag_openseg_prim_split_23___pvcn_959__is_rlz 	0
#define flexidag_openseg_prim_split_23___pvcn_959__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_23___pvcn_959__byte_offset 	248	/* 0x000000f8 */
#define flexidag_openseg_prim_split_23___pvcn_959__vbase_byte_offset 	252	/* 0x000000fc */
#define flexidag_openseg_prim_split_23___pvcn_959__dbase_byte_offset 	276	/* 0x00000114 */
#define flexidag_openseg_prim_split_23___pvcn_959__dpitchm1_byte_offset 	280	/* 0x00000118 */
#define flexidag_openseg_prim_split_23___pvcn_959__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_23___pvcn_959__W 	5788
#define flexidag_openseg_prim_split_23___pvcn_959__H 	1
#define flexidag_openseg_prim_split_23___pvcn_959__D 	1
#define flexidag_openseg_prim_split_23___pvcn_959__P 	1
#define flexidag_openseg_prim_split_23___pvcn_959__data_num_bytes 	1
#define flexidag_openseg_prim_split_23___pvcn_959__denable 	1
#define flexidag_openseg_prim_split_23___pvcn_959__dpitch_num_bytes 	5824
#define flexidag_openseg_prim_split_23___pvcn_959__dram_format 	0
#define flexidag_openseg_prim_split_23___pvcn_959__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_23___pvcn_959__tile_width 	1
#define flexidag_openseg_prim_split_23___pvcn_959__tile_height 	1
#define flexidag_openseg_prim_split_23___pvcn_959__vmem_buffer_num_bytes 	5788
#define flexidag_openseg_prim_split_23___pvcn_959__dram_size_num_bytes 	5824

/* flexidag_openseg_prim_split_23 SMB_input __pvcn_960_ */
#define flexidag_openseg_prim_split_23___pvcn_960__cnngen_demangled_name 	"__pvcn_960_"
#define flexidag_openseg_prim_split_23___pvcn_960__is_constant 	1
#define flexidag_openseg_prim_split_23___pvcn_960__has_init_data 	1
#define flexidag_openseg_prim_split_23___pvcn_960__is_variable_scalar 	0
#define flexidag_openseg_prim_split_23___pvcn_960__is_bitvector 	0
#define flexidag_openseg_prim_split_23___pvcn_960__is_rlz 	0
#define flexidag_openseg_prim_split_23___pvcn_960__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_23___pvcn_960__byte_offset 	288	/* 0x00000120 */
#define flexidag_openseg_prim_split_23___pvcn_960__vbase_byte_offset 	292	/* 0x00000124 */
#define flexidag_openseg_prim_split_23___pvcn_960__dbase_byte_offset 	316	/* 0x0000013c */
#define flexidag_openseg_prim_split_23___pvcn_960__dpitchm1_byte_offset 	320	/* 0x00000140 */
#define flexidag_openseg_prim_split_23___pvcn_960__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_23___pvcn_960__W 	96
#define flexidag_openseg_prim_split_23___pvcn_960__H 	1
#define flexidag_openseg_prim_split_23___pvcn_960__D 	1
#define flexidag_openseg_prim_split_23___pvcn_960__P 	1
#define flexidag_openseg_prim_split_23___pvcn_960__data_num_bytes 	1
#define flexidag_openseg_prim_split_23___pvcn_960__denable 	1
#define flexidag_openseg_prim_split_23___pvcn_960__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_23___pvcn_960__dram_format 	0
#define flexidag_openseg_prim_split_23___pvcn_960__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_23___pvcn_960__tile_width 	1
#define flexidag_openseg_prim_split_23___pvcn_960__tile_height 	1
#define flexidag_openseg_prim_split_23___pvcn_960__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_23___pvcn_960__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_23 HMB_input PeleeNet__stage_3_dense_block_3__concat______muli___478 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_3__concat______muli___478"
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_is_main_input_output 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_is_constant 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_has_init_data 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_is_variable_scalar 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_ddi_byte_size 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_is_bitvector 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_is_rlz 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_byte_offset 	328	/* 0x00000148 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_vbase_byte_offset 	332	/* 0x0000014c */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_dbase_byte_offset 	356	/* 0x00000164 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_dpitchm1_byte_offset 	360	/* 0x00000168 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_vwidth_minus_one_byte_offset 	344	/* 0x00000158 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_vheight_minus_one_byte_offset 	346	/* 0x0000015a */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_drotate_bit_offset 	2822	/* 0x00000b06 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_hflip_bit_offset 	2823	/* 0x00000b07 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_vflip_bit_offset 	2824	/* 0x00000b08 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_dflip_bit_offset 	2825	/* 0x00000b09 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_pflip_bit_offset 	2826	/* 0x00000b0a */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_W 	80
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_H 	32
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_D 	384
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_P 	1
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_data_num_bytes 	1
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_denable 	1
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_dram_format 	3
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_tile_width 	4
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_tile_height 	1
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_vmem_buffer_num_bytes 	129024
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_dram_size_num_bytes 	983040
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_sign 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_datasize 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_expoffset 	5
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_expbits 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_drotate 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_hflip 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_vflip 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_dflip 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_pflip 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_3__concat______muli___478_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_23 VCB PeleeNet__stage_3_dense_block_4__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_4__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm"
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm_is_bitvector 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm_is_rlz 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm_byte_offset 	380	/* 0x0000017c */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm_vbase_byte_offset 	388	/* 0x00000184 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm_vmem_buffer_num_bytes 	40960

/* flexidag_openseg_prim_split_23 VCB PeleeNet__stage_3_dense_block_4__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___muli___479___80 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___muli___479___80_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_4__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___muli___479___80"
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___muli___479___80_is_bitvector 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___muli___479___80_is_rlz 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___muli___479___80_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___muli___479___80_byte_offset 	428	/* 0x000001ac */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___muli___479___80_vbase_byte_offset 	436	/* 0x000001b4 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___muli___479___80_vmem_buffer_num_bytes 	61440

/* flexidag_openseg_prim_split_23 VCB PeleeNet__stage_3_dense_block_4__conv_right_0__Relu */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_0__Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_4__conv_right_0__Relu"
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_0__Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_0__Relu_is_rlz 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_0__Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_0__Relu_byte_offset 	512	/* 0x00000200 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_0__Relu_vbase_byte_offset 	520	/* 0x00000208 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_0__Relu_vmem_buffer_num_bytes 	78848

/* flexidag_openseg_prim_split_23 VCB PeleeNet__stage_3_dense_block_4__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_4__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	560	/* 0x00000230 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	568	/* 0x00000238 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	25344

/* flexidag_openseg_prim_split_23 HMB_output PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_main_input_output 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	608	/* 0x00000260 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	612	/* 0x00000264 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dbase_byte_offset 	636	/* 0x0000027c */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_byte_offset 	640	/* 0x00000280 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_byte_offset 	624	/* 0x00000270 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_byte_offset 	626	/* 0x00000272 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate_bit_offset 	5062	/* 0x000013c6 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip_bit_offset 	5063	/* 0x000013c7 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip_bit_offset 	5064	/* 0x000013c8 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip_bit_offset 	5065	/* 0x000013c9 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip_bit_offset 	5066	/* 0x000013ca */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_W 	80
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_H 	32
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_D 	16
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_P 	1
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_data_num_bytes 	1
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_denable 	1
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_format 	3
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_width 	4
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_height 	1
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	20480
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_size_num_bytes 	40960
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_sign 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_datasize 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_expoffset 	5
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_expbits 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_23 VCB PeleeNet__stage_3_dense_block_4__conv_left_0__Relu */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_4__conv_left_0__Relu"
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Relu_is_rlz 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Relu_byte_offset 	692	/* 0x000002b4 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Relu_vbase_byte_offset 	700	/* 0x000002bc */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_0__Relu_vmem_buffer_num_bytes 	78848

/* flexidag_openseg_prim_split_23 HMB_output PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_main_input_output 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	740	/* 0x000002e4 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	744	/* 0x000002e8 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dbase_byte_offset 	768	/* 0x00000300 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_byte_offset 	772	/* 0x00000304 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_byte_offset 	756	/* 0x000002f4 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_byte_offset 	758	/* 0x000002f6 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate_bit_offset 	6118	/* 0x000017e6 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip_bit_offset 	6119	/* 0x000017e7 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip_bit_offset 	6120	/* 0x000017e8 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip_bit_offset 	6121	/* 0x000017e9 */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip_bit_offset 	6122	/* 0x000017ea */
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_W 	80
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_H 	32
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_D 	16
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_P 	1
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_data_num_bytes 	1
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_denable 	1
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_format 	3
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_width 	4
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_height 	1
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	20480
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_size_num_bytes 	40960
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_sign 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_datasize 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_expoffset 	5
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_expbits 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip 	0
#define flexidag_openseg_prim_split_23_PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_23 SMB_output __vas_created_terminate__v0 */
#define flexidag_openseg_prim_split_23___vas_created_terminate__v0_cnngen_demangled_name 	"__vas_created_terminate__v0"
#define flexidag_openseg_prim_split_23___vas_created_terminate__v0_is_main_input_output 	0
#define flexidag_openseg_prim_split_23___vas_created_terminate__v0_is_bitvector 	1
#define flexidag_openseg_prim_split_23___vas_created_terminate__v0_is_rlz 	0
#define flexidag_openseg_prim_split_23___vas_created_terminate__v0_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_23___vas_created_terminate__v0_byte_offset 	780	/* 0x0000030c */
#define flexidag_openseg_prim_split_23___vas_created_terminate__v0_vbase_byte_offset 	784	/* 0x00000310 */
#define flexidag_openseg_prim_split_23___vas_created_terminate__v0_W 	256
#define flexidag_openseg_prim_split_23___vas_created_terminate__v0_H 	3
#define flexidag_openseg_prim_split_23___vas_created_terminate__v0_D 	1
#define flexidag_openseg_prim_split_23___vas_created_terminate__v0_P 	1
#define flexidag_openseg_prim_split_23___vas_created_terminate__v0_data_num_bytes 	1
#define flexidag_openseg_prim_split_23___vas_created_terminate__v0_denable 	0
#define flexidag_openseg_prim_split_23___vas_created_terminate__v0_dram_format 	0
#define flexidag_openseg_prim_split_23___vas_created_terminate__v0_vp_interleave_mode 	1
#define flexidag_openseg_prim_split_23___vas_created_terminate__v0_tile_width 	1
#define flexidag_openseg_prim_split_23___vas_created_terminate__v0_tile_height 	1
#define flexidag_openseg_prim_split_23___vas_created_terminate__v0_vmem_buffer_num_bytes 	96


#endif /* flexidag_openseg_prim_split_23_H */
