////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2020 Ambarella International LP
////////////////////////////////////////////////////////////////////////////////
// This file and its contents ("Software") are protected by intellectual
// property rights including, without limitation, U.S. and/or foreign
// copyrights. This Software is also the confidential and proprietary
// information of Ambarella International LP and its licensors. You may not use,
// reproduce, disclose, distribute, modify, or otherwise prepare derivative
// works of this Software or any portion thereof except pursuant to a signed
// license agreement or nondisclosure agreement with Ambarella International LP
// or its authorized affiliates. In the absence of such an agreement, you agree
// to promptly notify and return this Software to Ambarella International LP.
//
// THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL AMBARELLA INTERNATIONAL LP OR ITS AFFILIATES BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR MALFUNCTION;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
// OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
// ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////
#ifndef flexidag_openseg_prim_split_16_H
#define flexidag_openseg_prim_split_16_H

#define vas_gen_header_version                  	7

/* dag name */
#define flexidag_openseg_prim_split_16_DAG_NAME 	"flexidag_openseg_prim_split_16"

/* VDG file info */
#define flexidag_openseg_prim_split_16_vdg_name 	"flexidag_openseg_split_16.vdg"

/* VDG DAG memory info */
#define flexidag_openseg_prim_split_16_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_16_byte_size 	164	/* 0x000000a4 */
#define flexidag_openseg_prim_split_16_preferred_dram_xfer_size 	1

/* flexidag_openseg_prim_split_16 VMEM info */
#define flexidag_openseg_prim_split_16_use_ping_pong_vmem 	0
#define flexidag_openseg_prim_split_16_VMEM_start 	4096	/* 0x00001000 */
#define flexidag_openseg_prim_split_16_VMEM_end 	36960	/* 0x00009060 */
#define flexidag_openseg_prim_split_16_image_start 	36960	/* 0x00009060 */
#define flexidag_openseg_prim_split_16_image_size 	164	/* 0x000000a4 */
#define flexidag_openseg_prim_split_16_dagbin_start 	36960	/* 0x00009060 */

/* flexidag_openseg_prim_split_16 DAG info */
#define flexidag_openseg_prim_split_16_estimated_cycles 	41008
#define flexidag_openseg_prim_split_16_ddi_byte_size 	0	/* 0x00000000 */

/*******************************************************************************
 * DAG byte offset info for HMB/SMB/VCB and their fields
 * in DAG 'flexidag_openseg_prim_split_16' in source file 'pre_split15_flexidag_openseg_split_0.vas'
 ******************************************************************************/
/* flexidag_openseg_prim_split_16 HMB_input PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_cnngen_demangled_name 	"PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66"
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_is_main_input_output 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_is_constant 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_has_init_data 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_is_variable_scalar 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_ddi_byte_size 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_is_bitvector 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_is_rlz 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_byte_offset 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_vbase_byte_offset 	4	/* 0x00000004 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_dbase_byte_offset 	28	/* 0x0000001c */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_dpitchm1_byte_offset 	32	/* 0x00000020 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_vwidth_minus_one_byte_offset 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_vheight_minus_one_byte_offset 	18	/* 0x00000012 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_drotate_bit_offset 	198	/* 0x000000c6 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_hflip_bit_offset 	199	/* 0x000000c7 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_vflip_bit_offset 	200	/* 0x000000c8 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_dflip_bit_offset 	201	/* 0x000000c9 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_pflip_bit_offset 	202	/* 0x000000ca */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_W 	80
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_H 	32
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_D 	256
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_P 	1
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_data_num_bytes 	1
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_denable 	1
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_dram_format 	3
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_tile_width 	4
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_tile_height 	1
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_vmem_buffer_num_bytes 	16384
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_dram_size_num_bytes 	655360
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_sign 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_datasize 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_expoffset 	6
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_expbits 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_drotate 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_hflip 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_vflip 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_dflip 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_pflip 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_16 HMB_output PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243_ */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__cnngen_demangled_name 	"PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243_"
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__is_main_input_output 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__is_bitvector 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__is_rlz 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__byte_offset 	48	/* 0x00000030 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__vbase_byte_offset 	52	/* 0x00000034 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__dbase_byte_offset 	76	/* 0x0000004c */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__dpitchm1_byte_offset 	80	/* 0x00000050 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__vwidth_minus_one_byte_offset 	64	/* 0x00000040 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__vheight_minus_one_byte_offset 	66	/* 0x00000042 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__drotate_bit_offset 	582	/* 0x00000246 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__hflip_bit_offset 	583	/* 0x00000247 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__vflip_bit_offset 	584	/* 0x00000248 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__dflip_bit_offset 	585	/* 0x00000249 */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__pflip_bit_offset 	586	/* 0x0000024a */
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__W 	80
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__H 	32
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__D 	256
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__P 	1
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__data_num_bytes 	1
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__denable 	1
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__dram_format 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__vp_interleave_mode 	2
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__tile_width 	4
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__tile_height 	1
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__vmem_buffer_num_bytes 	16384
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__dram_size_num_bytes 	1048576
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__sign 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__datasize 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__expoffset 	6
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__expbits 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__drotate 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__hflip 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__vflip 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__dflip 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__pflip 	0
#define flexidag_openseg_prim_split_16_PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__trailing_extra_elements 	0

/* flexidag_openseg_prim_split_16 SMB_output __vas_created_terminate__v0 */
#define flexidag_openseg_prim_split_16___vas_created_terminate__v0_cnngen_demangled_name 	"__vas_created_terminate__v0"
#define flexidag_openseg_prim_split_16___vas_created_terminate__v0_is_main_input_output 	0
#define flexidag_openseg_prim_split_16___vas_created_terminate__v0_is_bitvector 	1
#define flexidag_openseg_prim_split_16___vas_created_terminate__v0_is_rlz 	0
#define flexidag_openseg_prim_split_16___vas_created_terminate__v0_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_16___vas_created_terminate__v0_byte_offset 	88	/* 0x00000058 */
#define flexidag_openseg_prim_split_16___vas_created_terminate__v0_vbase_byte_offset 	92	/* 0x0000005c */
#define flexidag_openseg_prim_split_16___vas_created_terminate__v0_W 	256
#define flexidag_openseg_prim_split_16___vas_created_terminate__v0_H 	3
#define flexidag_openseg_prim_split_16___vas_created_terminate__v0_D 	1
#define flexidag_openseg_prim_split_16___vas_created_terminate__v0_P 	1
#define flexidag_openseg_prim_split_16___vas_created_terminate__v0_data_num_bytes 	1
#define flexidag_openseg_prim_split_16___vas_created_terminate__v0_denable 	0
#define flexidag_openseg_prim_split_16___vas_created_terminate__v0_dram_format 	0
#define flexidag_openseg_prim_split_16___vas_created_terminate__v0_vp_interleave_mode 	1
#define flexidag_openseg_prim_split_16___vas_created_terminate__v0_tile_width 	1
#define flexidag_openseg_prim_split_16___vas_created_terminate__v0_tile_height 	1
#define flexidag_openseg_prim_split_16___vas_created_terminate__v0_vmem_buffer_num_bytes 	96


#endif /* flexidag_openseg_prim_split_16_H */
