////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2020 Ambarella International LP
////////////////////////////////////////////////////////////////////////////////
// This file and its contents ("Software") are protected by intellectual
// property rights including, without limitation, U.S. and/or foreign
// copyrights. This Software is also the confidential and proprietary
// information of Ambarella International LP and its licensors. You may not use,
// reproduce, disclose, distribute, modify, or otherwise prepare derivative
// works of this Software or any portion thereof except pursuant to a signed
// license agreement or nondisclosure agreement with Ambarella International LP
// or its authorized affiliates. In the absence of such an agreement, you agree
// to promptly notify and return this Software to Ambarella International LP.
//
// THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL AMBARELLA INTERNATIONAL LP OR ITS AFFILIATES BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR MALFUNCTION;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
// OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
// ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////
#ifndef flexidag_openseg_prim_split_30_H
#define flexidag_openseg_prim_split_30_H

#define vas_gen_header_version                  	7

/* dag name */
#define flexidag_openseg_prim_split_30_DAG_NAME 	"flexidag_openseg_prim_split_30"

/* VDG file info */
#define flexidag_openseg_prim_split_30_vdg_name 	"flexidag_openseg_split_30.vdg"

/* VDG DAG memory info */
#define flexidag_openseg_prim_split_30_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_30_byte_size 	292	/* 0x00000124 */
#define flexidag_openseg_prim_split_30_preferred_dram_xfer_size 	1

/* flexidag_openseg_prim_split_30 VMEM info */
#define flexidag_openseg_prim_split_30_use_ping_pong_vmem 	0
#define flexidag_openseg_prim_split_30_VMEM_start 	4096	/* 0x00001000 */
#define flexidag_openseg_prim_split_30_VMEM_end 	108640	/* 0x0001a860 */
#define flexidag_openseg_prim_split_30_image_start 	108640	/* 0x0001a860 */
#define flexidag_openseg_prim_split_30_image_size 	292	/* 0x00000124 */
#define flexidag_openseg_prim_split_30_dagbin_start 	108640	/* 0x0001a860 */

/* flexidag_openseg_prim_split_30 DAG info */
#define flexidag_openseg_prim_split_30_estimated_cycles 	81968
#define flexidag_openseg_prim_split_30_ddi_byte_size 	0	/* 0x00000000 */

/*******************************************************************************
 * DAG byte offset info for HMB/SMB/VCB and their fields
 * in DAG 'flexidag_openseg_prim_split_30' in source file 'pre_split20_flexidag_openseg_split_1.vas'
 ******************************************************************************/
/* flexidag_openseg_prim_split_30 HMB_input PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_main_input_output 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_constant 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_has_init_data 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_variable_scalar 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_ddi_byte_size 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	4	/* 0x00000004 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dbase_byte_offset 	28	/* 0x0000001c */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_byte_offset 	32	/* 0x00000020 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_byte_offset 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_byte_offset 	18	/* 0x00000012 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate_bit_offset 	198	/* 0x000000c6 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip_bit_offset 	199	/* 0x000000c7 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip_bit_offset 	200	/* 0x000000c8 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip_bit_offset 	201	/* 0x000000c9 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip_bit_offset 	202	/* 0x000000ca */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_W 	80
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_H 	32
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_D 	16
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_P 	1
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_data_num_bytes 	1
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_denable 	1
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_format 	3
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_width 	4
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_height 	1
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	20480
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_size_num_bytes 	40960
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_sign 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_datasize 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_expoffset 	5
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_expbits 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_30 HMB_input PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_main_input_output 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_constant 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_has_init_data 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_variable_scalar 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_ddi_byte_size 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	40	/* 0x00000028 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	44	/* 0x0000002c */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dbase_byte_offset 	68	/* 0x00000044 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_byte_offset 	72	/* 0x00000048 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_byte_offset 	56	/* 0x00000038 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_byte_offset 	58	/* 0x0000003a */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate_bit_offset 	518	/* 0x00000206 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip_bit_offset 	519	/* 0x00000207 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip_bit_offset 	520	/* 0x00000208 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip_bit_offset 	521	/* 0x00000209 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip_bit_offset 	522	/* 0x0000020a */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_W 	80
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_H 	32
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_D 	16
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_P 	1
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_data_num_bytes 	1
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_denable 	1
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_format 	3
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_width 	4
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_height 	1
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	20480
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_size_num_bytes 	40960
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_sign 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_datasize 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_expoffset 	5
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_expbits 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_30 HMB_input PeleeNet__stage_3_dense_block_6__concat______muli___487 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_6__concat______muli___487"
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_is_main_input_output 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_is_constant 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_has_init_data 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_is_variable_scalar 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_ddi_byte_size 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_is_bitvector 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_is_rlz 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_byte_offset 	76	/* 0x0000004c */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_vbase_byte_offset 	80	/* 0x00000050 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_dbase_byte_offset 	104	/* 0x00000068 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_dpitchm1_byte_offset 	108	/* 0x0000006c */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_vwidth_minus_one_byte_offset 	92	/* 0x0000005c */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_vheight_minus_one_byte_offset 	94	/* 0x0000005e */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_drotate_bit_offset 	806	/* 0x00000326 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_hflip_bit_offset 	807	/* 0x00000327 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_vflip_bit_offset 	808	/* 0x00000328 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_dflip_bit_offset 	809	/* 0x00000329 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_pflip_bit_offset 	810	/* 0x0000032a */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_W 	80
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_H 	32
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_D 	480
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_P 	1
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_data_num_bytes 	1
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_denable 	1
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_dram_format 	3
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_tile_width 	4
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_tile_height 	1
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_vmem_buffer_num_bytes 	30720
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_dram_size_num_bytes 	1228800
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_sign 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_datasize 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_expoffset 	5
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_expbits 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_drotate 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_hflip 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_vflip 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_dflip 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_pflip 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_6__concat______muli___487_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_30 HMB_output PeleeNet__stage_3_dense_block_7__concat */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_7__concat"
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_is_main_input_output 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_is_bitvector 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_is_rlz 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_byte_offset 	116	/* 0x00000074 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_vbase_byte_offset 	120	/* 0x00000078 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_dbase_byte_offset 	144	/* 0x00000090 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_dpitchm1_byte_offset 	148	/* 0x00000094 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_vwidth_minus_one_byte_offset 	132	/* 0x00000084 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_vheight_minus_one_byte_offset 	134	/* 0x00000086 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_drotate_bit_offset 	1126	/* 0x00000466 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_hflip_bit_offset 	1127	/* 0x00000467 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_vflip_bit_offset 	1128	/* 0x00000468 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_dflip_bit_offset 	1129	/* 0x00000469 */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_pflip_bit_offset 	1130	/* 0x0000046a */
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_W 	80
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_H 	32
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_D 	512
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_P 	1
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_data_num_bytes 	1
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_denable 	1
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_dram_format 	3
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_tile_width 	4
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_tile_height 	1
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_vmem_buffer_num_bytes 	32768
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_dram_size_num_bytes 	1310720
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_sign 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_datasize 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_expoffset 	5
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_expbits 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_drotate 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_hflip 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_vflip 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_dflip 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_pflip 	0
#define flexidag_openseg_prim_split_30_PeleeNet__stage_3_dense_block_7__concat_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_30 SMB_output __vas_created_terminate__v0 */
#define flexidag_openseg_prim_split_30___vas_created_terminate__v0_cnngen_demangled_name 	"__vas_created_terminate__v0"
#define flexidag_openseg_prim_split_30___vas_created_terminate__v0_is_main_input_output 	0
#define flexidag_openseg_prim_split_30___vas_created_terminate__v0_is_bitvector 	1
#define flexidag_openseg_prim_split_30___vas_created_terminate__v0_is_rlz 	0
#define flexidag_openseg_prim_split_30___vas_created_terminate__v0_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_30___vas_created_terminate__v0_byte_offset 	216	/* 0x000000d8 */
#define flexidag_openseg_prim_split_30___vas_created_terminate__v0_vbase_byte_offset 	220	/* 0x000000dc */
#define flexidag_openseg_prim_split_30___vas_created_terminate__v0_W 	256
#define flexidag_openseg_prim_split_30___vas_created_terminate__v0_H 	3
#define flexidag_openseg_prim_split_30___vas_created_terminate__v0_D 	1
#define flexidag_openseg_prim_split_30___vas_created_terminate__v0_P 	1
#define flexidag_openseg_prim_split_30___vas_created_terminate__v0_data_num_bytes 	1
#define flexidag_openseg_prim_split_30___vas_created_terminate__v0_denable 	0
#define flexidag_openseg_prim_split_30___vas_created_terminate__v0_dram_format 	0
#define flexidag_openseg_prim_split_30___vas_created_terminate__v0_vp_interleave_mode 	1
#define flexidag_openseg_prim_split_30___vas_created_terminate__v0_tile_width 	1
#define flexidag_openseg_prim_split_30___vas_created_terminate__v0_tile_height 	1
#define flexidag_openseg_prim_split_30___vas_created_terminate__v0_vmem_buffer_num_bytes 	96


#endif /* flexidag_openseg_prim_split_30_H */
