////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2020 Ambarella International LP
////////////////////////////////////////////////////////////////////////////////
// This file and its contents ("Software") are protected by intellectual
// property rights including, without limitation, U.S. and/or foreign
// copyrights. This Software is also the confidential and proprietary
// information of Ambarella International LP and its licensors. You may not use,
// reproduce, disclose, distribute, modify, or otherwise prepare derivative
// works of this Software or any portion thereof except pursuant to a signed
// license agreement or nondisclosure agreement with Ambarella International LP
// or its authorized affiliates. In the absence of such an agreement, you agree
// to promptly notify and return this Software to Ambarella International LP.
//
// THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL AMBARELLA INTERNATIONAL LP OR ITS AFFILIATES BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR MALFUNCTION;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
// OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
// ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////
#ifndef flexidag_openseg_prim_split_21_H
#define flexidag_openseg_prim_split_21_H

#define vas_gen_header_version                  	7

/* dag name */
#define flexidag_openseg_prim_split_21_DAG_NAME 	"flexidag_openseg_prim_split_21"

/* VDG file info */
#define flexidag_openseg_prim_split_21_vdg_name 	"flexidag_openseg_split_21.vdg"

/* VDG DAG memory info */
#define flexidag_openseg_prim_split_21_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_21_byte_size 	796	/* 0x0000031c */
#define flexidag_openseg_prim_split_21_preferred_dram_xfer_size 	1

/* flexidag_openseg_prim_split_21 VMEM info */
#define flexidag_openseg_prim_split_21_use_ping_pong_vmem 	0
#define flexidag_openseg_prim_split_21_VMEM_start 	4096	/* 0x00001000 */
#define flexidag_openseg_prim_split_21_VMEM_end 	470476	/* 0x00072dcc */
#define flexidag_openseg_prim_split_21_image_start 	428384	/* 0x00068960 */
#define flexidag_openseg_prim_split_21_image_size 	42888	/* 0x0000a788 */
#define flexidag_openseg_prim_split_21_dagbin_start 	470476	/* 0x00072dcc */

/* flexidag_openseg_prim_split_21 DAG info */
#define flexidag_openseg_prim_split_21_estimated_cycles 	121022
#define flexidag_openseg_prim_split_21_ddi_byte_size 	0	/* 0x00000000 */

/*******************************************************************************
 * DAG byte offset info for HMB/SMB/VCB and their fields
 * in DAG 'flexidag_openseg_prim_split_21' in source file 'pre_split16_flexidag_openseg_split_0.vas'
 ******************************************************************************/
/* flexidag_openseg_prim_split_21 SMB_input __pvcn_928_ */
#define flexidag_openseg_prim_split_21___pvcn_928__cnngen_demangled_name 	"__pvcn_928_"
#define flexidag_openseg_prim_split_21___pvcn_928__is_constant 	1
#define flexidag_openseg_prim_split_21___pvcn_928__has_init_data 	1
#define flexidag_openseg_prim_split_21___pvcn_928__is_variable_scalar 	0
#define flexidag_openseg_prim_split_21___pvcn_928__is_bitvector 	0
#define flexidag_openseg_prim_split_21___pvcn_928__is_rlz 	0
#define flexidag_openseg_prim_split_21___pvcn_928__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_21___pvcn_928__byte_offset 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_21___pvcn_928__vbase_byte_offset 	4	/* 0x00000004 */
#define flexidag_openseg_prim_split_21___pvcn_928__dbase_byte_offset 	28	/* 0x0000001c */
#define flexidag_openseg_prim_split_21___pvcn_928__dpitchm1_byte_offset 	32	/* 0x00000020 */
#define flexidag_openseg_prim_split_21___pvcn_928__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_21___pvcn_928__W 	28260
#define flexidag_openseg_prim_split_21___pvcn_928__H 	1
#define flexidag_openseg_prim_split_21___pvcn_928__D 	1
#define flexidag_openseg_prim_split_21___pvcn_928__P 	1
#define flexidag_openseg_prim_split_21___pvcn_928__data_num_bytes 	1
#define flexidag_openseg_prim_split_21___pvcn_928__denable 	1
#define flexidag_openseg_prim_split_21___pvcn_928__dpitch_num_bytes 	28288
#define flexidag_openseg_prim_split_21___pvcn_928__dram_format 	0
#define flexidag_openseg_prim_split_21___pvcn_928__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_21___pvcn_928__tile_width 	1
#define flexidag_openseg_prim_split_21___pvcn_928__tile_height 	1
#define flexidag_openseg_prim_split_21___pvcn_928__vmem_buffer_num_bytes 	28260
#define flexidag_openseg_prim_split_21___pvcn_928__dram_size_num_bytes 	28288

/* flexidag_openseg_prim_split_21 SMB_input __pvcn_929_ */
#define flexidag_openseg_prim_split_21___pvcn_929__cnngen_demangled_name 	"__pvcn_929_"
#define flexidag_openseg_prim_split_21___pvcn_929__is_constant 	1
#define flexidag_openseg_prim_split_21___pvcn_929__has_init_data 	1
#define flexidag_openseg_prim_split_21___pvcn_929__is_variable_scalar 	0
#define flexidag_openseg_prim_split_21___pvcn_929__is_bitvector 	0
#define flexidag_openseg_prim_split_21___pvcn_929__is_rlz 	0
#define flexidag_openseg_prim_split_21___pvcn_929__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_21___pvcn_929__byte_offset 	36	/* 0x00000024 */
#define flexidag_openseg_prim_split_21___pvcn_929__vbase_byte_offset 	40	/* 0x00000028 */
#define flexidag_openseg_prim_split_21___pvcn_929__dbase_byte_offset 	64	/* 0x00000040 */
#define flexidag_openseg_prim_split_21___pvcn_929__dpitchm1_byte_offset 	68	/* 0x00000044 */
#define flexidag_openseg_prim_split_21___pvcn_929__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_21___pvcn_929__W 	640
#define flexidag_openseg_prim_split_21___pvcn_929__H 	1
#define flexidag_openseg_prim_split_21___pvcn_929__D 	1
#define flexidag_openseg_prim_split_21___pvcn_929__P 	1
#define flexidag_openseg_prim_split_21___pvcn_929__data_num_bytes 	1
#define flexidag_openseg_prim_split_21___pvcn_929__denable 	1
#define flexidag_openseg_prim_split_21___pvcn_929__dpitch_num_bytes 	640
#define flexidag_openseg_prim_split_21___pvcn_929__dram_format 	0
#define flexidag_openseg_prim_split_21___pvcn_929__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_21___pvcn_929__tile_width 	1
#define flexidag_openseg_prim_split_21___pvcn_929__tile_height 	1
#define flexidag_openseg_prim_split_21___pvcn_929__vmem_buffer_num_bytes 	640
#define flexidag_openseg_prim_split_21___pvcn_929__dram_size_num_bytes 	640

/* flexidag_openseg_prim_split_21 SMB_input __pvcn_932_ */
#define flexidag_openseg_prim_split_21___pvcn_932__cnngen_demangled_name 	"__pvcn_932_"
#define flexidag_openseg_prim_split_21___pvcn_932__is_constant 	1
#define flexidag_openseg_prim_split_21___pvcn_932__has_init_data 	1
#define flexidag_openseg_prim_split_21___pvcn_932__is_variable_scalar 	0
#define flexidag_openseg_prim_split_21___pvcn_932__is_bitvector 	0
#define flexidag_openseg_prim_split_21___pvcn_932__is_rlz 	0
#define flexidag_openseg_prim_split_21___pvcn_932__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_21___pvcn_932__byte_offset 	76	/* 0x0000004c */
#define flexidag_openseg_prim_split_21___pvcn_932__vbase_byte_offset 	80	/* 0x00000050 */
#define flexidag_openseg_prim_split_21___pvcn_932__dbase_byte_offset 	104	/* 0x00000068 */
#define flexidag_openseg_prim_split_21___pvcn_932__dpitchm1_byte_offset 	108	/* 0x0000006c */
#define flexidag_openseg_prim_split_21___pvcn_932__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_21___pvcn_932__W 	5760
#define flexidag_openseg_prim_split_21___pvcn_932__H 	1
#define flexidag_openseg_prim_split_21___pvcn_932__D 	1
#define flexidag_openseg_prim_split_21___pvcn_932__P 	1
#define flexidag_openseg_prim_split_21___pvcn_932__data_num_bytes 	1
#define flexidag_openseg_prim_split_21___pvcn_932__denable 	1
#define flexidag_openseg_prim_split_21___pvcn_932__dpitch_num_bytes 	5760
#define flexidag_openseg_prim_split_21___pvcn_932__dram_format 	0
#define flexidag_openseg_prim_split_21___pvcn_932__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_21___pvcn_932__tile_width 	1
#define flexidag_openseg_prim_split_21___pvcn_932__tile_height 	1
#define flexidag_openseg_prim_split_21___pvcn_932__vmem_buffer_num_bytes 	5760
#define flexidag_openseg_prim_split_21___pvcn_932__dram_size_num_bytes 	5760

/* flexidag_openseg_prim_split_21 SMB_input __pvcn_933_ */
#define flexidag_openseg_prim_split_21___pvcn_933__cnngen_demangled_name 	"__pvcn_933_"
#define flexidag_openseg_prim_split_21___pvcn_933__is_constant 	1
#define flexidag_openseg_prim_split_21___pvcn_933__has_init_data 	1
#define flexidag_openseg_prim_split_21___pvcn_933__is_variable_scalar 	0
#define flexidag_openseg_prim_split_21___pvcn_933__is_bitvector 	0
#define flexidag_openseg_prim_split_21___pvcn_933__is_rlz 	0
#define flexidag_openseg_prim_split_21___pvcn_933__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_21___pvcn_933__byte_offset 	116	/* 0x00000074 */
#define flexidag_openseg_prim_split_21___pvcn_933__vbase_byte_offset 	120	/* 0x00000078 */
#define flexidag_openseg_prim_split_21___pvcn_933__dbase_byte_offset 	144	/* 0x00000090 */
#define flexidag_openseg_prim_split_21___pvcn_933__dpitchm1_byte_offset 	148	/* 0x00000094 */
#define flexidag_openseg_prim_split_21___pvcn_933__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_21___pvcn_933__W 	96
#define flexidag_openseg_prim_split_21___pvcn_933__H 	1
#define flexidag_openseg_prim_split_21___pvcn_933__D 	1
#define flexidag_openseg_prim_split_21___pvcn_933__P 	1
#define flexidag_openseg_prim_split_21___pvcn_933__data_num_bytes 	1
#define flexidag_openseg_prim_split_21___pvcn_933__denable 	1
#define flexidag_openseg_prim_split_21___pvcn_933__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_21___pvcn_933__dram_format 	0
#define flexidag_openseg_prim_split_21___pvcn_933__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_21___pvcn_933__tile_width 	1
#define flexidag_openseg_prim_split_21___pvcn_933__tile_height 	1
#define flexidag_openseg_prim_split_21___pvcn_933__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_21___pvcn_933__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_21 SMB_input __pvcn_935_ */
#define flexidag_openseg_prim_split_21___pvcn_935__cnngen_demangled_name 	"__pvcn_935_"
#define flexidag_openseg_prim_split_21___pvcn_935__is_constant 	1
#define flexidag_openseg_prim_split_21___pvcn_935__has_init_data 	1
#define flexidag_openseg_prim_split_21___pvcn_935__is_variable_scalar 	0
#define flexidag_openseg_prim_split_21___pvcn_935__is_bitvector 	0
#define flexidag_openseg_prim_split_21___pvcn_935__is_rlz 	0
#define flexidag_openseg_prim_split_21___pvcn_935__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_21___pvcn_935__byte_offset 	156	/* 0x0000009c */
#define flexidag_openseg_prim_split_21___pvcn_935__vbase_byte_offset 	160	/* 0x000000a0 */
#define flexidag_openseg_prim_split_21___pvcn_935__dbase_byte_offset 	184	/* 0x000000b8 */
#define flexidag_openseg_prim_split_21___pvcn_935__dpitchm1_byte_offset 	188	/* 0x000000bc */
#define flexidag_openseg_prim_split_21___pvcn_935__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_21___pvcn_935__W 	1436
#define flexidag_openseg_prim_split_21___pvcn_935__H 	1
#define flexidag_openseg_prim_split_21___pvcn_935__D 	1
#define flexidag_openseg_prim_split_21___pvcn_935__P 	1
#define flexidag_openseg_prim_split_21___pvcn_935__data_num_bytes 	1
#define flexidag_openseg_prim_split_21___pvcn_935__denable 	1
#define flexidag_openseg_prim_split_21___pvcn_935__dpitch_num_bytes 	1472
#define flexidag_openseg_prim_split_21___pvcn_935__dram_format 	0
#define flexidag_openseg_prim_split_21___pvcn_935__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_21___pvcn_935__tile_width 	1
#define flexidag_openseg_prim_split_21___pvcn_935__tile_height 	1
#define flexidag_openseg_prim_split_21___pvcn_935__vmem_buffer_num_bytes 	1436
#define flexidag_openseg_prim_split_21___pvcn_935__dram_size_num_bytes 	1472

/* flexidag_openseg_prim_split_21 SMB_input __pvcn_936_ */
#define flexidag_openseg_prim_split_21___pvcn_936__cnngen_demangled_name 	"__pvcn_936_"
#define flexidag_openseg_prim_split_21___pvcn_936__is_constant 	1
#define flexidag_openseg_prim_split_21___pvcn_936__has_init_data 	1
#define flexidag_openseg_prim_split_21___pvcn_936__is_variable_scalar 	0
#define flexidag_openseg_prim_split_21___pvcn_936__is_bitvector 	0
#define flexidag_openseg_prim_split_21___pvcn_936__is_rlz 	0
#define flexidag_openseg_prim_split_21___pvcn_936__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_21___pvcn_936__byte_offset 	196	/* 0x000000c4 */
#define flexidag_openseg_prim_split_21___pvcn_936__vbase_byte_offset 	200	/* 0x000000c8 */
#define flexidag_openseg_prim_split_21___pvcn_936__dbase_byte_offset 	224	/* 0x000000e0 */
#define flexidag_openseg_prim_split_21___pvcn_936__dpitchm1_byte_offset 	228	/* 0x000000e4 */
#define flexidag_openseg_prim_split_21___pvcn_936__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_21___pvcn_936__W 	96
#define flexidag_openseg_prim_split_21___pvcn_936__H 	1
#define flexidag_openseg_prim_split_21___pvcn_936__D 	1
#define flexidag_openseg_prim_split_21___pvcn_936__P 	1
#define flexidag_openseg_prim_split_21___pvcn_936__data_num_bytes 	1
#define flexidag_openseg_prim_split_21___pvcn_936__denable 	1
#define flexidag_openseg_prim_split_21___pvcn_936__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_21___pvcn_936__dram_format 	0
#define flexidag_openseg_prim_split_21___pvcn_936__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_21___pvcn_936__tile_width 	1
#define flexidag_openseg_prim_split_21___pvcn_936__tile_height 	1
#define flexidag_openseg_prim_split_21___pvcn_936__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_21___pvcn_936__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_21 SMB_input __pvcn_939_ */
#define flexidag_openseg_prim_split_21___pvcn_939__cnngen_demangled_name 	"__pvcn_939_"
#define flexidag_openseg_prim_split_21___pvcn_939__is_constant 	1
#define flexidag_openseg_prim_split_21___pvcn_939__has_init_data 	1
#define flexidag_openseg_prim_split_21___pvcn_939__is_variable_scalar 	0
#define flexidag_openseg_prim_split_21___pvcn_939__is_bitvector 	0
#define flexidag_openseg_prim_split_21___pvcn_939__is_rlz 	0
#define flexidag_openseg_prim_split_21___pvcn_939__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_21___pvcn_939__byte_offset 	236	/* 0x000000ec */
#define flexidag_openseg_prim_split_21___pvcn_939__vbase_byte_offset 	240	/* 0x000000f0 */
#define flexidag_openseg_prim_split_21___pvcn_939__dbase_byte_offset 	264	/* 0x00000108 */
#define flexidag_openseg_prim_split_21___pvcn_939__dpitchm1_byte_offset 	268	/* 0x0000010c */
#define flexidag_openseg_prim_split_21___pvcn_939__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_21___pvcn_939__W 	5708
#define flexidag_openseg_prim_split_21___pvcn_939__H 	1
#define flexidag_openseg_prim_split_21___pvcn_939__D 	1
#define flexidag_openseg_prim_split_21___pvcn_939__P 	1
#define flexidag_openseg_prim_split_21___pvcn_939__data_num_bytes 	1
#define flexidag_openseg_prim_split_21___pvcn_939__denable 	1
#define flexidag_openseg_prim_split_21___pvcn_939__dpitch_num_bytes 	5760
#define flexidag_openseg_prim_split_21___pvcn_939__dram_format 	0
#define flexidag_openseg_prim_split_21___pvcn_939__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_21___pvcn_939__tile_width 	1
#define flexidag_openseg_prim_split_21___pvcn_939__tile_height 	1
#define flexidag_openseg_prim_split_21___pvcn_939__vmem_buffer_num_bytes 	5708
#define flexidag_openseg_prim_split_21___pvcn_939__dram_size_num_bytes 	5760

/* flexidag_openseg_prim_split_21 SMB_input __pvcn_940_ */
#define flexidag_openseg_prim_split_21___pvcn_940__cnngen_demangled_name 	"__pvcn_940_"
#define flexidag_openseg_prim_split_21___pvcn_940__is_constant 	1
#define flexidag_openseg_prim_split_21___pvcn_940__has_init_data 	1
#define flexidag_openseg_prim_split_21___pvcn_940__is_variable_scalar 	0
#define flexidag_openseg_prim_split_21___pvcn_940__is_bitvector 	0
#define flexidag_openseg_prim_split_21___pvcn_940__is_rlz 	0
#define flexidag_openseg_prim_split_21___pvcn_940__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_21___pvcn_940__byte_offset 	276	/* 0x00000114 */
#define flexidag_openseg_prim_split_21___pvcn_940__vbase_byte_offset 	280	/* 0x00000118 */
#define flexidag_openseg_prim_split_21___pvcn_940__dbase_byte_offset 	304	/* 0x00000130 */
#define flexidag_openseg_prim_split_21___pvcn_940__dpitchm1_byte_offset 	308	/* 0x00000134 */
#define flexidag_openseg_prim_split_21___pvcn_940__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_21___pvcn_940__W 	96
#define flexidag_openseg_prim_split_21___pvcn_940__H 	1
#define flexidag_openseg_prim_split_21___pvcn_940__D 	1
#define flexidag_openseg_prim_split_21___pvcn_940__P 	1
#define flexidag_openseg_prim_split_21___pvcn_940__data_num_bytes 	1
#define flexidag_openseg_prim_split_21___pvcn_940__denable 	1
#define flexidag_openseg_prim_split_21___pvcn_940__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_21___pvcn_940__dram_format 	0
#define flexidag_openseg_prim_split_21___pvcn_940__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_21___pvcn_940__tile_width 	1
#define flexidag_openseg_prim_split_21___pvcn_940__tile_height 	1
#define flexidag_openseg_prim_split_21___pvcn_940__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_21___pvcn_940__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_21 HMB_input PeleeNet__stage_3_dense_block_2__concat______muli___475 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_2__concat______muli___475"
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_is_main_input_output 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_is_constant 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_has_init_data 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_is_variable_scalar 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_ddi_byte_size 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_is_bitvector 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_is_rlz 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_byte_offset 	316	/* 0x0000013c */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_vbase_byte_offset 	320	/* 0x00000140 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_dbase_byte_offset 	344	/* 0x00000158 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_dpitchm1_byte_offset 	348	/* 0x0000015c */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_vwidth_minus_one_byte_offset 	332	/* 0x0000014c */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_vheight_minus_one_byte_offset 	334	/* 0x0000014e */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_drotate_bit_offset 	2726	/* 0x00000aa6 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_hflip_bit_offset 	2727	/* 0x00000aa7 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_vflip_bit_offset 	2728	/* 0x00000aa8 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_dflip_bit_offset 	2729	/* 0x00000aa9 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_pflip_bit_offset 	2730	/* 0x00000aaa */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_W 	80
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_H 	32
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_D 	352
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_P 	1
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_data_num_bytes 	1
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_denable 	1
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_dram_format 	3
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_tile_width 	4
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_tile_height 	1
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_vmem_buffer_num_bytes 	118272
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_dram_size_num_bytes 	901120
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_sign 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_datasize 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_expoffset 	5
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_expbits 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_drotate 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_hflip 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_vflip 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_dflip 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_pflip 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_2__concat______muli___475_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_21 VCB PeleeNet__stage_3_dense_block_3__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___476___7 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___476___7_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_3__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___476___7"
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___476___7_is_bitvector 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___476___7_is_rlz 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___476___7_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___476___7_byte_offset 	368	/* 0x00000170 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___476___7_vbase_byte_offset 	376	/* 0x00000178 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___476___7_vmem_buffer_num_bytes 	81920

/* flexidag_openseg_prim_split_21 VCB PeleeNet__stage_3_dense_block_3__conv_right_0__Relu */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_0__Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_3__conv_right_0__Relu"
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_0__Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_0__Relu_is_rlz 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_0__Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_0__Relu_byte_offset 	452	/* 0x000001c4 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_0__Relu_vbase_byte_offset 	460	/* 0x000001cc */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_0__Relu_vmem_buffer_num_bytes 	78848

/* flexidag_openseg_prim_split_21 VCB PeleeNet__stage_3_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	500	/* 0x000001f4 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	508	/* 0x000001fc */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	25344

/* flexidag_openseg_prim_split_21 HMB_output PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_main_input_output 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	548	/* 0x00000224 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	552	/* 0x00000228 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dbase_byte_offset 	576	/* 0x00000240 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_byte_offset 	580	/* 0x00000244 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_byte_offset 	564	/* 0x00000234 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_byte_offset 	566	/* 0x00000236 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate_bit_offset 	4582	/* 0x000011e6 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip_bit_offset 	4583	/* 0x000011e7 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip_bit_offset 	4584	/* 0x000011e8 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip_bit_offset 	4585	/* 0x000011e9 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip_bit_offset 	4586	/* 0x000011ea */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_W 	80
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_H 	32
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_D 	16
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_P 	1
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_data_num_bytes 	1
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_denable 	1
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_format 	3
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_width 	4
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_height 	1
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	20480
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_size_num_bytes 	40960
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_sign 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_datasize 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_expoffset 	5
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_expbits 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_21 VCB PeleeNet__stage_3_dense_block_3__conv_left_0__Relu */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_0__Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_3__conv_left_0__Relu"
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_0__Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_0__Relu_is_rlz 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_0__Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_0__Relu_byte_offset 	632	/* 0x00000278 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_0__Relu_vbase_byte_offset 	640	/* 0x00000280 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_0__Relu_vmem_buffer_num_bytes 	78848

/* flexidag_openseg_prim_split_21 HMB_output PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_main_input_output 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	680	/* 0x000002a8 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	684	/* 0x000002ac */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dbase_byte_offset 	708	/* 0x000002c4 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_byte_offset 	712	/* 0x000002c8 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_byte_offset 	696	/* 0x000002b8 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_byte_offset 	698	/* 0x000002ba */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate_bit_offset 	5638	/* 0x00001606 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip_bit_offset 	5639	/* 0x00001607 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip_bit_offset 	5640	/* 0x00001608 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip_bit_offset 	5641	/* 0x00001609 */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip_bit_offset 	5642	/* 0x0000160a */
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_W 	80
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_H 	32
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_D 	16
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_P 	1
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_data_num_bytes 	1
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_denable 	1
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_format 	3
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_width 	4
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_height 	1
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	20480
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_size_num_bytes 	40960
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_sign 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_datasize 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_expoffset 	5
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_expbits 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip 	0
#define flexidag_openseg_prim_split_21_PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_21 SMB_output __vas_created_terminate__v0 */
#define flexidag_openseg_prim_split_21___vas_created_terminate__v0_cnngen_demangled_name 	"__vas_created_terminate__v0"
#define flexidag_openseg_prim_split_21___vas_created_terminate__v0_is_main_input_output 	0
#define flexidag_openseg_prim_split_21___vas_created_terminate__v0_is_bitvector 	1
#define flexidag_openseg_prim_split_21___vas_created_terminate__v0_is_rlz 	0
#define flexidag_openseg_prim_split_21___vas_created_terminate__v0_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_21___vas_created_terminate__v0_byte_offset 	720	/* 0x000002d0 */
#define flexidag_openseg_prim_split_21___vas_created_terminate__v0_vbase_byte_offset 	724	/* 0x000002d4 */
#define flexidag_openseg_prim_split_21___vas_created_terminate__v0_W 	256
#define flexidag_openseg_prim_split_21___vas_created_terminate__v0_H 	3
#define flexidag_openseg_prim_split_21___vas_created_terminate__v0_D 	1
#define flexidag_openseg_prim_split_21___vas_created_terminate__v0_P 	1
#define flexidag_openseg_prim_split_21___vas_created_terminate__v0_data_num_bytes 	1
#define flexidag_openseg_prim_split_21___vas_created_terminate__v0_denable 	0
#define flexidag_openseg_prim_split_21___vas_created_terminate__v0_dram_format 	0
#define flexidag_openseg_prim_split_21___vas_created_terminate__v0_vp_interleave_mode 	1
#define flexidag_openseg_prim_split_21___vas_created_terminate__v0_tile_width 	1
#define flexidag_openseg_prim_split_21___vas_created_terminate__v0_tile_height 	1
#define flexidag_openseg_prim_split_21___vas_created_terminate__v0_vmem_buffer_num_bytes 	96


#endif /* flexidag_openseg_prim_split_21_H */
