////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2020 Ambarella International LP
////////////////////////////////////////////////////////////////////////////////
// This file and its contents ("Software") are protected by intellectual
// property rights including, without limitation, U.S. and/or foreign
// copyrights. This Software is also the confidential and proprietary
// information of Ambarella International LP and its licensors. You may not use,
// reproduce, disclose, distribute, modify, or otherwise prepare derivative
// works of this Software or any portion thereof except pursuant to a signed
// license agreement or nondisclosure agreement with Ambarella International LP
// or its authorized affiliates. In the absence of such an agreement, you agree
// to promptly notify and return this Software to Ambarella International LP.
//
// THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL AMBARELLA INTERNATIONAL LP OR ITS AFFILIATES BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR MALFUNCTION;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
// OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
// ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////
#ifndef flexidag_openseg_prim_split_11_H
#define flexidag_openseg_prim_split_11_H

#define vas_gen_header_version                  	7

/* dag name */
#define flexidag_openseg_prim_split_11_DAG_NAME 	"flexidag_openseg_prim_split_11"

/* VDG file info */
#define flexidag_openseg_prim_split_11_vdg_name 	"flexidag_openseg_split_11.vdg"

/* VDG DAG memory info */
#define flexidag_openseg_prim_split_11_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_11_byte_size 	804	/* 0x00000324 */
#define flexidag_openseg_prim_split_11_preferred_dram_xfer_size 	1

/* flexidag_openseg_prim_split_11 VMEM info */
#define flexidag_openseg_prim_split_11_use_ping_pong_vmem 	0
#define flexidag_openseg_prim_split_11_VMEM_start 	4096	/* 0x00001000 */
#define flexidag_openseg_prim_split_11_VMEM_end 	488788	/* 0x00077554 */
#define flexidag_openseg_prim_split_11_image_start 	472672	/* 0x00073660 */
#define flexidag_openseg_prim_split_11_image_size 	16920	/* 0x00004218 */
#define flexidag_openseg_prim_split_11_dagbin_start 	488788	/* 0x00077554 */

/* flexidag_openseg_prim_split_11 DAG info */
#define flexidag_openseg_prim_split_11_estimated_cycles 	338217
#define flexidag_openseg_prim_split_11_ddi_byte_size 	0	/* 0x00000000 */

/*******************************************************************************
 * DAG byte offset info for HMB/SMB/VCB and their fields
 * in DAG 'flexidag_openseg_prim_split_11' in source file 'pre_split10_flexidag_openseg_split_0.vas'
 ******************************************************************************/
/* flexidag_openseg_prim_split_11 SMB_input __pvcn_725_ */
#define flexidag_openseg_prim_split_11___pvcn_725__cnngen_demangled_name 	"__pvcn_725_"
#define flexidag_openseg_prim_split_11___pvcn_725__is_constant 	1
#define flexidag_openseg_prim_split_11___pvcn_725__has_init_data 	1
#define flexidag_openseg_prim_split_11___pvcn_725__is_variable_scalar 	0
#define flexidag_openseg_prim_split_11___pvcn_725__is_bitvector 	0
#define flexidag_openseg_prim_split_11___pvcn_725__is_rlz 	0
#define flexidag_openseg_prim_split_11___pvcn_725__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_11___pvcn_725__byte_offset 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_11___pvcn_725__vbase_byte_offset 	4	/* 0x00000004 */
#define flexidag_openseg_prim_split_11___pvcn_725__dbase_byte_offset 	28	/* 0x0000001c */
#define flexidag_openseg_prim_split_11___pvcn_725__dpitchm1_byte_offset 	32	/* 0x00000020 */
#define flexidag_openseg_prim_split_11___pvcn_725__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_11___pvcn_725__W 	7344
#define flexidag_openseg_prim_split_11___pvcn_725__H 	1
#define flexidag_openseg_prim_split_11___pvcn_725__D 	1
#define flexidag_openseg_prim_split_11___pvcn_725__P 	1
#define flexidag_openseg_prim_split_11___pvcn_725__data_num_bytes 	1
#define flexidag_openseg_prim_split_11___pvcn_725__denable 	1
#define flexidag_openseg_prim_split_11___pvcn_725__dpitch_num_bytes 	7360
#define flexidag_openseg_prim_split_11___pvcn_725__dram_format 	0
#define flexidag_openseg_prim_split_11___pvcn_725__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_11___pvcn_725__tile_width 	1
#define flexidag_openseg_prim_split_11___pvcn_725__tile_height 	1
#define flexidag_openseg_prim_split_11___pvcn_725__vmem_buffer_num_bytes 	7344
#define flexidag_openseg_prim_split_11___pvcn_725__dram_size_num_bytes 	7360

/* flexidag_openseg_prim_split_11 SMB_input __pvcn_726_ */
#define flexidag_openseg_prim_split_11___pvcn_726__cnngen_demangled_name 	"__pvcn_726_"
#define flexidag_openseg_prim_split_11___pvcn_726__is_constant 	1
#define flexidag_openseg_prim_split_11___pvcn_726__has_init_data 	1
#define flexidag_openseg_prim_split_11___pvcn_726__is_variable_scalar 	0
#define flexidag_openseg_prim_split_11___pvcn_726__is_bitvector 	0
#define flexidag_openseg_prim_split_11___pvcn_726__is_rlz 	0
#define flexidag_openseg_prim_split_11___pvcn_726__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_11___pvcn_726__byte_offset 	40	/* 0x00000028 */
#define flexidag_openseg_prim_split_11___pvcn_726__vbase_byte_offset 	44	/* 0x0000002c */
#define flexidag_openseg_prim_split_11___pvcn_726__dbase_byte_offset 	68	/* 0x00000044 */
#define flexidag_openseg_prim_split_11___pvcn_726__dpitchm1_byte_offset 	72	/* 0x00000048 */
#define flexidag_openseg_prim_split_11___pvcn_726__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_11___pvcn_726__W 	320
#define flexidag_openseg_prim_split_11___pvcn_726__H 	1
#define flexidag_openseg_prim_split_11___pvcn_726__D 	1
#define flexidag_openseg_prim_split_11___pvcn_726__P 	1
#define flexidag_openseg_prim_split_11___pvcn_726__data_num_bytes 	1
#define flexidag_openseg_prim_split_11___pvcn_726__denable 	1
#define flexidag_openseg_prim_split_11___pvcn_726__dpitch_num_bytes 	320
#define flexidag_openseg_prim_split_11___pvcn_726__dram_format 	0
#define flexidag_openseg_prim_split_11___pvcn_726__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_11___pvcn_726__tile_width 	1
#define flexidag_openseg_prim_split_11___pvcn_726__tile_height 	1
#define flexidag_openseg_prim_split_11___pvcn_726__vmem_buffer_num_bytes 	320
#define flexidag_openseg_prim_split_11___pvcn_726__dram_size_num_bytes 	320

/* flexidag_openseg_prim_split_11 SMB_input __pvcn_729_ */
#define flexidag_openseg_prim_split_11___pvcn_729__cnngen_demangled_name 	"__pvcn_729_"
#define flexidag_openseg_prim_split_11___pvcn_729__is_constant 	1
#define flexidag_openseg_prim_split_11___pvcn_729__has_init_data 	1
#define flexidag_openseg_prim_split_11___pvcn_729__is_variable_scalar 	0
#define flexidag_openseg_prim_split_11___pvcn_729__is_bitvector 	0
#define flexidag_openseg_prim_split_11___pvcn_729__is_rlz 	0
#define flexidag_openseg_prim_split_11___pvcn_729__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_11___pvcn_729__byte_offset 	80	/* 0x00000050 */
#define flexidag_openseg_prim_split_11___pvcn_729__vbase_byte_offset 	84	/* 0x00000054 */
#define flexidag_openseg_prim_split_11___pvcn_729__dbase_byte_offset 	108	/* 0x0000006c */
#define flexidag_openseg_prim_split_11___pvcn_729__dpitchm1_byte_offset 	112	/* 0x00000070 */
#define flexidag_openseg_prim_split_11___pvcn_729__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_11___pvcn_729__W 	3280
#define flexidag_openseg_prim_split_11___pvcn_729__H 	1
#define flexidag_openseg_prim_split_11___pvcn_729__D 	1
#define flexidag_openseg_prim_split_11___pvcn_729__P 	1
#define flexidag_openseg_prim_split_11___pvcn_729__data_num_bytes 	1
#define flexidag_openseg_prim_split_11___pvcn_729__denable 	1
#define flexidag_openseg_prim_split_11___pvcn_729__dpitch_num_bytes 	3328
#define flexidag_openseg_prim_split_11___pvcn_729__dram_format 	0
#define flexidag_openseg_prim_split_11___pvcn_729__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_11___pvcn_729__tile_width 	1
#define flexidag_openseg_prim_split_11___pvcn_729__tile_height 	1
#define flexidag_openseg_prim_split_11___pvcn_729__vmem_buffer_num_bytes 	3280
#define flexidag_openseg_prim_split_11___pvcn_729__dram_size_num_bytes 	3328

/* flexidag_openseg_prim_split_11 SMB_input __pvcn_730_ */
#define flexidag_openseg_prim_split_11___pvcn_730__cnngen_demangled_name 	"__pvcn_730_"
#define flexidag_openseg_prim_split_11___pvcn_730__is_constant 	1
#define flexidag_openseg_prim_split_11___pvcn_730__has_init_data 	1
#define flexidag_openseg_prim_split_11___pvcn_730__is_variable_scalar 	0
#define flexidag_openseg_prim_split_11___pvcn_730__is_bitvector 	0
#define flexidag_openseg_prim_split_11___pvcn_730__is_rlz 	0
#define flexidag_openseg_prim_split_11___pvcn_730__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_11___pvcn_730__byte_offset 	120	/* 0x00000078 */
#define flexidag_openseg_prim_split_11___pvcn_730__vbase_byte_offset 	124	/* 0x0000007c */
#define flexidag_openseg_prim_split_11___pvcn_730__dbase_byte_offset 	148	/* 0x00000094 */
#define flexidag_openseg_prim_split_11___pvcn_730__dpitchm1_byte_offset 	152	/* 0x00000098 */
#define flexidag_openseg_prim_split_11___pvcn_730__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_11___pvcn_730__W 	96
#define flexidag_openseg_prim_split_11___pvcn_730__H 	1
#define flexidag_openseg_prim_split_11___pvcn_730__D 	1
#define flexidag_openseg_prim_split_11___pvcn_730__P 	1
#define flexidag_openseg_prim_split_11___pvcn_730__data_num_bytes 	1
#define flexidag_openseg_prim_split_11___pvcn_730__denable 	1
#define flexidag_openseg_prim_split_11___pvcn_730__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_11___pvcn_730__dram_format 	0
#define flexidag_openseg_prim_split_11___pvcn_730__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_11___pvcn_730__tile_width 	1
#define flexidag_openseg_prim_split_11___pvcn_730__tile_height 	1
#define flexidag_openseg_prim_split_11___pvcn_730__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_11___pvcn_730__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_11 SMB_input __pvcn_732_ */
#define flexidag_openseg_prim_split_11___pvcn_732__cnngen_demangled_name 	"__pvcn_732_"
#define flexidag_openseg_prim_split_11___pvcn_732__is_constant 	1
#define flexidag_openseg_prim_split_11___pvcn_732__has_init_data 	1
#define flexidag_openseg_prim_split_11___pvcn_732__is_variable_scalar 	0
#define flexidag_openseg_prim_split_11___pvcn_732__is_bitvector 	0
#define flexidag_openseg_prim_split_11___pvcn_732__is_rlz 	0
#define flexidag_openseg_prim_split_11___pvcn_732__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_11___pvcn_732__byte_offset 	160	/* 0x000000a0 */
#define flexidag_openseg_prim_split_11___pvcn_732__vbase_byte_offset 	164	/* 0x000000a4 */
#define flexidag_openseg_prim_split_11___pvcn_732__dbase_byte_offset 	188	/* 0x000000bc */
#define flexidag_openseg_prim_split_11___pvcn_732__dpitchm1_byte_offset 	192	/* 0x000000c0 */
#define flexidag_openseg_prim_split_11___pvcn_732__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_11___pvcn_732__W 	1632
#define flexidag_openseg_prim_split_11___pvcn_732__H 	1
#define flexidag_openseg_prim_split_11___pvcn_732__D 	1
#define flexidag_openseg_prim_split_11___pvcn_732__P 	1
#define flexidag_openseg_prim_split_11___pvcn_732__data_num_bytes 	1
#define flexidag_openseg_prim_split_11___pvcn_732__denable 	1
#define flexidag_openseg_prim_split_11___pvcn_732__dpitch_num_bytes 	1664
#define flexidag_openseg_prim_split_11___pvcn_732__dram_format 	0
#define flexidag_openseg_prim_split_11___pvcn_732__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_11___pvcn_732__tile_width 	1
#define flexidag_openseg_prim_split_11___pvcn_732__tile_height 	1
#define flexidag_openseg_prim_split_11___pvcn_732__vmem_buffer_num_bytes 	1632
#define flexidag_openseg_prim_split_11___pvcn_732__dram_size_num_bytes 	1664

/* flexidag_openseg_prim_split_11 SMB_input __pvcn_733_ */
#define flexidag_openseg_prim_split_11___pvcn_733__cnngen_demangled_name 	"__pvcn_733_"
#define flexidag_openseg_prim_split_11___pvcn_733__is_constant 	1
#define flexidag_openseg_prim_split_11___pvcn_733__has_init_data 	1
#define flexidag_openseg_prim_split_11___pvcn_733__is_variable_scalar 	0
#define flexidag_openseg_prim_split_11___pvcn_733__is_bitvector 	0
#define flexidag_openseg_prim_split_11___pvcn_733__is_rlz 	0
#define flexidag_openseg_prim_split_11___pvcn_733__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_11___pvcn_733__byte_offset 	200	/* 0x000000c8 */
#define flexidag_openseg_prim_split_11___pvcn_733__vbase_byte_offset 	204	/* 0x000000cc */
#define flexidag_openseg_prim_split_11___pvcn_733__dbase_byte_offset 	228	/* 0x000000e4 */
#define flexidag_openseg_prim_split_11___pvcn_733__dpitchm1_byte_offset 	232	/* 0x000000e8 */
#define flexidag_openseg_prim_split_11___pvcn_733__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_11___pvcn_733__W 	96
#define flexidag_openseg_prim_split_11___pvcn_733__H 	1
#define flexidag_openseg_prim_split_11___pvcn_733__D 	1
#define flexidag_openseg_prim_split_11___pvcn_733__P 	1
#define flexidag_openseg_prim_split_11___pvcn_733__data_num_bytes 	1
#define flexidag_openseg_prim_split_11___pvcn_733__denable 	1
#define flexidag_openseg_prim_split_11___pvcn_733__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_11___pvcn_733__dram_format 	0
#define flexidag_openseg_prim_split_11___pvcn_733__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_11___pvcn_733__tile_width 	1
#define flexidag_openseg_prim_split_11___pvcn_733__tile_height 	1
#define flexidag_openseg_prim_split_11___pvcn_733__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_11___pvcn_733__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_11 SMB_input __pvcn_736_ */
#define flexidag_openseg_prim_split_11___pvcn_736__cnngen_demangled_name 	"__pvcn_736_"
#define flexidag_openseg_prim_split_11___pvcn_736__is_constant 	1
#define flexidag_openseg_prim_split_11___pvcn_736__has_init_data 	1
#define flexidag_openseg_prim_split_11___pvcn_736__is_variable_scalar 	0
#define flexidag_openseg_prim_split_11___pvcn_736__is_bitvector 	0
#define flexidag_openseg_prim_split_11___pvcn_736__is_rlz 	0
#define flexidag_openseg_prim_split_11___pvcn_736__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_11___pvcn_736__byte_offset 	240	/* 0x000000f0 */
#define flexidag_openseg_prim_split_11___pvcn_736__vbase_byte_offset 	244	/* 0x000000f4 */
#define flexidag_openseg_prim_split_11___pvcn_736__dbase_byte_offset 	268	/* 0x0000010c */
#define flexidag_openseg_prim_split_11___pvcn_736__dpitchm1_byte_offset 	272	/* 0x00000110 */
#define flexidag_openseg_prim_split_11___pvcn_736__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_11___pvcn_736__W 	3252
#define flexidag_openseg_prim_split_11___pvcn_736__H 	1
#define flexidag_openseg_prim_split_11___pvcn_736__D 	1
#define flexidag_openseg_prim_split_11___pvcn_736__P 	1
#define flexidag_openseg_prim_split_11___pvcn_736__data_num_bytes 	1
#define flexidag_openseg_prim_split_11___pvcn_736__denable 	1
#define flexidag_openseg_prim_split_11___pvcn_736__dpitch_num_bytes 	3264
#define flexidag_openseg_prim_split_11___pvcn_736__dram_format 	0
#define flexidag_openseg_prim_split_11___pvcn_736__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_11___pvcn_736__tile_width 	1
#define flexidag_openseg_prim_split_11___pvcn_736__tile_height 	1
#define flexidag_openseg_prim_split_11___pvcn_736__vmem_buffer_num_bytes 	3252
#define flexidag_openseg_prim_split_11___pvcn_736__dram_size_num_bytes 	3264

/* flexidag_openseg_prim_split_11 SMB_input __pvcn_737_ */
#define flexidag_openseg_prim_split_11___pvcn_737__cnngen_demangled_name 	"__pvcn_737_"
#define flexidag_openseg_prim_split_11___pvcn_737__is_constant 	1
#define flexidag_openseg_prim_split_11___pvcn_737__has_init_data 	1
#define flexidag_openseg_prim_split_11___pvcn_737__is_variable_scalar 	0
#define flexidag_openseg_prim_split_11___pvcn_737__is_bitvector 	0
#define flexidag_openseg_prim_split_11___pvcn_737__is_rlz 	0
#define flexidag_openseg_prim_split_11___pvcn_737__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_11___pvcn_737__byte_offset 	280	/* 0x00000118 */
#define flexidag_openseg_prim_split_11___pvcn_737__vbase_byte_offset 	284	/* 0x0000011c */
#define flexidag_openseg_prim_split_11___pvcn_737__dbase_byte_offset 	308	/* 0x00000134 */
#define flexidag_openseg_prim_split_11___pvcn_737__dpitchm1_byte_offset 	312	/* 0x00000138 */
#define flexidag_openseg_prim_split_11___pvcn_737__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_11___pvcn_737__W 	96
#define flexidag_openseg_prim_split_11___pvcn_737__H 	1
#define flexidag_openseg_prim_split_11___pvcn_737__D 	1
#define flexidag_openseg_prim_split_11___pvcn_737__P 	1
#define flexidag_openseg_prim_split_11___pvcn_737__data_num_bytes 	1
#define flexidag_openseg_prim_split_11___pvcn_737__denable 	1
#define flexidag_openseg_prim_split_11___pvcn_737__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_11___pvcn_737__dram_format 	0
#define flexidag_openseg_prim_split_11___pvcn_737__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_11___pvcn_737__tile_width 	1
#define flexidag_openseg_prim_split_11___pvcn_737__tile_height 	1
#define flexidag_openseg_prim_split_11___pvcn_737__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_11___pvcn_737__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_11 HMB_input PeleeNet__stage_2_dense_block_0__concat______muli___456 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_0__concat______muli___456"
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_is_main_input_output 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_is_constant 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_has_init_data 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_is_variable_scalar 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_ddi_byte_size 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_is_bitvector 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_is_rlz 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_byte_offset 	320	/* 0x00000140 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_vbase_byte_offset 	324	/* 0x00000144 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_dbase_byte_offset 	348	/* 0x0000015c */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_dpitchm1_byte_offset 	352	/* 0x00000160 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_vwidth_minus_one_byte_offset 	336	/* 0x00000150 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_vheight_minus_one_byte_offset 	338	/* 0x00000152 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_drotate_bit_offset 	2758	/* 0x00000ac6 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_hflip_bit_offset 	2759	/* 0x00000ac7 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_vflip_bit_offset 	2760	/* 0x00000ac8 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_dflip_bit_offset 	2761	/* 0x00000ac9 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_pflip_bit_offset 	2762	/* 0x00000aca */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_W 	160
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_H 	64
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_D 	160
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_P 	1
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_data_num_bytes 	1
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_denable 	1
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_dram_format 	3
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_tile_width 	4
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_tile_height 	1
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_vmem_buffer_num_bytes 	156160
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_dram_size_num_bytes 	1638400
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_sign 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_datasize 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_expoffset 	5
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_expbits 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_drotate 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_hflip 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_vflip 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_dflip 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_pflip 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_0__concat______muli___456_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_11 HMB_output PeleeNet__stage_2_dense_block_1__concat______muli___459 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_1__concat______muli___459"
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_is_main_input_output 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_is_bitvector 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_is_rlz 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_byte_offset 	360	/* 0x00000168 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_vbase_byte_offset 	364	/* 0x0000016c */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_dbase_byte_offset 	388	/* 0x00000184 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_dpitchm1_byte_offset 	392	/* 0x00000188 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_vwidth_minus_one_byte_offset 	376	/* 0x00000178 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_vheight_minus_one_byte_offset 	378	/* 0x0000017a */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_drotate_bit_offset 	3078	/* 0x00000c06 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_hflip_bit_offset 	3079	/* 0x00000c07 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_vflip_bit_offset 	3080	/* 0x00000c08 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_dflip_bit_offset 	3081	/* 0x00000c09 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_pflip_bit_offset 	3082	/* 0x00000c0a */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_W 	160
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_H 	64
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_D 	192
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_P 	1
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_data_num_bytes 	1
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_denable 	1
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_dram_format 	3
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_tile_width 	4
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_tile_height 	1
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_vmem_buffer_num_bytes 	122880
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_dram_size_num_bytes 	1966080
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_sign 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_datasize 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_expoffset 	5
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_expbits 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_drotate 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_hflip 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_vflip 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_dflip 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_pflip 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__concat______muli___459_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_11 VCB PeleeNet__stage_2_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___457___8 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___457___8_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___457___8"
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___457___8_is_bitvector 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___457___8_is_rlz 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___457___8_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___457___8_byte_offset 	432	/* 0x000001b0 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___457___8_vbase_byte_offset 	440	/* 0x000001b8 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___457___8_vmem_buffer_num_bytes 	81920

/* flexidag_openseg_prim_split_11 VCB PeleeNet__stage_2_dense_block_1__conv_right_0__Relu */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_right_0__Relu_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_1__conv_right_0__Relu"
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_right_0__Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_right_0__Relu_is_rlz 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_right_0__Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_right_0__Relu_byte_offset 	516	/* 0x00000204 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_right_0__Relu_vbase_byte_offset 	524	/* 0x0000020c */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_right_0__Relu_vmem_buffer_num_bytes 	53760

/* flexidag_openseg_prim_split_11 VCB PeleeNet__stage_2_dense_block_1__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_1__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	564	/* 0x00000234 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	572	/* 0x0000023c */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	26880

/* flexidag_openseg_prim_split_11 VCB PeleeNet__stage_2_dense_block_1__conv_left_0__Relu */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_left_0__Relu_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_1__conv_left_0__Relu"
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_left_0__Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_left_0__Relu_is_rlz 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_left_0__Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_left_0__Relu_byte_offset 	668	/* 0x0000029c */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_left_0__Relu_vbase_byte_offset 	676	/* 0x000002a4 */
#define flexidag_openseg_prim_split_11_PeleeNet__stage_2_dense_block_1__conv_left_0__Relu_vmem_buffer_num_bytes 	26880

/* flexidag_openseg_prim_split_11 SMB_output __vas_created_terminate__v0 */
#define flexidag_openseg_prim_split_11___vas_created_terminate__v0_cnngen_demangled_name 	"__vas_created_terminate__v0"
#define flexidag_openseg_prim_split_11___vas_created_terminate__v0_is_main_input_output 	0
#define flexidag_openseg_prim_split_11___vas_created_terminate__v0_is_bitvector 	1
#define flexidag_openseg_prim_split_11___vas_created_terminate__v0_is_rlz 	0
#define flexidag_openseg_prim_split_11___vas_created_terminate__v0_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_11___vas_created_terminate__v0_byte_offset 	728	/* 0x000002d8 */
#define flexidag_openseg_prim_split_11___vas_created_terminate__v0_vbase_byte_offset 	732	/* 0x000002dc */
#define flexidag_openseg_prim_split_11___vas_created_terminate__v0_W 	256
#define flexidag_openseg_prim_split_11___vas_created_terminate__v0_H 	3
#define flexidag_openseg_prim_split_11___vas_created_terminate__v0_D 	1
#define flexidag_openseg_prim_split_11___vas_created_terminate__v0_P 	1
#define flexidag_openseg_prim_split_11___vas_created_terminate__v0_data_num_bytes 	1
#define flexidag_openseg_prim_split_11___vas_created_terminate__v0_denable 	0
#define flexidag_openseg_prim_split_11___vas_created_terminate__v0_dram_format 	0
#define flexidag_openseg_prim_split_11___vas_created_terminate__v0_vp_interleave_mode 	1
#define flexidag_openseg_prim_split_11___vas_created_terminate__v0_tile_width 	1
#define flexidag_openseg_prim_split_11___vas_created_terminate__v0_tile_height 	1
#define flexidag_openseg_prim_split_11___vas_created_terminate__v0_vmem_buffer_num_bytes 	96


#endif /* flexidag_openseg_prim_split_11_H */
