////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2020 Ambarella International LP
////////////////////////////////////////////////////////////////////////////////
// This file and its contents ("Software") are protected by intellectual
// property rights including, without limitation, U.S. and/or foreign
// copyrights. This Software is also the confidential and proprietary
// information of Ambarella International LP and its licensors. You may not use,
// reproduce, disclose, distribute, modify, or otherwise prepare derivative
// works of this Software or any portion thereof except pursuant to a signed
// license agreement or nondisclosure agreement with Ambarella International LP
// or its authorized affiliates. In the absence of such an agreement, you agree
// to promptly notify and return this Software to Ambarella International LP.
//
// THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL AMBARELLA INTERNATIONAL LP OR ITS AFFILIATES BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR MALFUNCTION;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
// OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
// ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////
#ifndef flexidag_openseg_prim_split_13_H
#define flexidag_openseg_prim_split_13_H

#define vas_gen_header_version                  	7

/* dag name */
#define flexidag_openseg_prim_split_13_DAG_NAME 	"flexidag_openseg_prim_split_13"

/* VDG file info */
#define flexidag_openseg_prim_split_13_vdg_name 	"flexidag_openseg_split_13.vdg"

/* VDG DAG memory info */
#define flexidag_openseg_prim_split_13_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_13_byte_size 	732	/* 0x000002dc */
#define flexidag_openseg_prim_split_13_preferred_dram_xfer_size 	1

/* flexidag_openseg_prim_split_13 VMEM info */
#define flexidag_openseg_prim_split_13_use_ping_pong_vmem 	0
#define flexidag_openseg_prim_split_13_VMEM_start 	4096	/* 0x00001000 */
#define flexidag_openseg_prim_split_13_VMEM_end 	509272	/* 0x0007c558 */
#define flexidag_openseg_prim_split_13_image_start 	492128	/* 0x00078260 */
#define flexidag_openseg_prim_split_13_image_size 	17876	/* 0x000045d4 */
#define flexidag_openseg_prim_split_13_dagbin_start 	509272	/* 0x0007c558 */

/* flexidag_openseg_prim_split_13 DAG info */
#define flexidag_openseg_prim_split_13_estimated_cycles 	409913
#define flexidag_openseg_prim_split_13_ddi_byte_size 	0	/* 0x00000000 */

/*******************************************************************************
 * DAG byte offset info for HMB/SMB/VCB and their fields
 * in DAG 'flexidag_openseg_prim_split_13' in source file 'pre_split12_flexidag_openseg_split_0.vas'
 ******************************************************************************/
/* flexidag_openseg_prim_split_13 SMB_input __pvcn_763_ */
#define flexidag_openseg_prim_split_13___pvcn_763__cnngen_demangled_name 	"__pvcn_763_"
#define flexidag_openseg_prim_split_13___pvcn_763__is_constant 	1
#define flexidag_openseg_prim_split_13___pvcn_763__has_init_data 	1
#define flexidag_openseg_prim_split_13___pvcn_763__is_variable_scalar 	0
#define flexidag_openseg_prim_split_13___pvcn_763__is_bitvector 	0
#define flexidag_openseg_prim_split_13___pvcn_763__is_rlz 	0
#define flexidag_openseg_prim_split_13___pvcn_763__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_13___pvcn_763__byte_offset 	8	/* 0x00000008 */
#define flexidag_openseg_prim_split_13___pvcn_763__vbase_byte_offset 	12	/* 0x0000000c */
#define flexidag_openseg_prim_split_13___pvcn_763__dbase_byte_offset 	36	/* 0x00000024 */
#define flexidag_openseg_prim_split_13___pvcn_763__dpitchm1_byte_offset 	40	/* 0x00000028 */
#define flexidag_openseg_prim_split_13___pvcn_763__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_13___pvcn_763__W 	10116
#define flexidag_openseg_prim_split_13___pvcn_763__H 	1
#define flexidag_openseg_prim_split_13___pvcn_763__D 	1
#define flexidag_openseg_prim_split_13___pvcn_763__P 	1
#define flexidag_openseg_prim_split_13___pvcn_763__data_num_bytes 	1
#define flexidag_openseg_prim_split_13___pvcn_763__denable 	1
#define flexidag_openseg_prim_split_13___pvcn_763__dpitch_num_bytes 	10176
#define flexidag_openseg_prim_split_13___pvcn_763__dram_format 	0
#define flexidag_openseg_prim_split_13___pvcn_763__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_13___pvcn_763__tile_width 	1
#define flexidag_openseg_prim_split_13___pvcn_763__tile_height 	1
#define flexidag_openseg_prim_split_13___pvcn_763__vmem_buffer_num_bytes 	10116
#define flexidag_openseg_prim_split_13___pvcn_763__dram_size_num_bytes 	10176

/* flexidag_openseg_prim_split_13 SMB_input __pvcn_764_ */
#define flexidag_openseg_prim_split_13___pvcn_764__cnngen_demangled_name 	"__pvcn_764_"
#define flexidag_openseg_prim_split_13___pvcn_764__is_constant 	1
#define flexidag_openseg_prim_split_13___pvcn_764__has_init_data 	1
#define flexidag_openseg_prim_split_13___pvcn_764__is_variable_scalar 	0
#define flexidag_openseg_prim_split_13___pvcn_764__is_bitvector 	0
#define flexidag_openseg_prim_split_13___pvcn_764__is_rlz 	0
#define flexidag_openseg_prim_split_13___pvcn_764__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_13___pvcn_764__byte_offset 	48	/* 0x00000030 */
#define flexidag_openseg_prim_split_13___pvcn_764__vbase_byte_offset 	52	/* 0x00000034 */
#define flexidag_openseg_prim_split_13___pvcn_764__dbase_byte_offset 	76	/* 0x0000004c */
#define flexidag_openseg_prim_split_13___pvcn_764__dpitchm1_byte_offset 	80	/* 0x00000050 */
#define flexidag_openseg_prim_split_13___pvcn_764__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_13___pvcn_764__W 	320
#define flexidag_openseg_prim_split_13___pvcn_764__H 	1
#define flexidag_openseg_prim_split_13___pvcn_764__D 	1
#define flexidag_openseg_prim_split_13___pvcn_764__P 	1
#define flexidag_openseg_prim_split_13___pvcn_764__data_num_bytes 	1
#define flexidag_openseg_prim_split_13___pvcn_764__denable 	1
#define flexidag_openseg_prim_split_13___pvcn_764__dpitch_num_bytes 	320
#define flexidag_openseg_prim_split_13___pvcn_764__dram_format 	0
#define flexidag_openseg_prim_split_13___pvcn_764__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_13___pvcn_764__tile_width 	1
#define flexidag_openseg_prim_split_13___pvcn_764__tile_height 	1
#define flexidag_openseg_prim_split_13___pvcn_764__vmem_buffer_num_bytes 	320
#define flexidag_openseg_prim_split_13___pvcn_764__dram_size_num_bytes 	320

/* flexidag_openseg_prim_split_13 SMB_input __pvcn_767_ */
#define flexidag_openseg_prim_split_13___pvcn_767__cnngen_demangled_name 	"__pvcn_767_"
#define flexidag_openseg_prim_split_13___pvcn_767__is_constant 	1
#define flexidag_openseg_prim_split_13___pvcn_767__has_init_data 	1
#define flexidag_openseg_prim_split_13___pvcn_767__is_variable_scalar 	0
#define flexidag_openseg_prim_split_13___pvcn_767__is_bitvector 	0
#define flexidag_openseg_prim_split_13___pvcn_767__is_rlz 	0
#define flexidag_openseg_prim_split_13___pvcn_767__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_13___pvcn_767__byte_offset 	88	/* 0x00000058 */
#define flexidag_openseg_prim_split_13___pvcn_767__vbase_byte_offset 	92	/* 0x0000005c */
#define flexidag_openseg_prim_split_13___pvcn_767__dbase_byte_offset 	116	/* 0x00000074 */
#define flexidag_openseg_prim_split_13___pvcn_767__dpitchm1_byte_offset 	120	/* 0x00000078 */
#define flexidag_openseg_prim_split_13___pvcn_767__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_13___pvcn_767__W 	3244
#define flexidag_openseg_prim_split_13___pvcn_767__H 	1
#define flexidag_openseg_prim_split_13___pvcn_767__D 	1
#define flexidag_openseg_prim_split_13___pvcn_767__P 	1
#define flexidag_openseg_prim_split_13___pvcn_767__data_num_bytes 	1
#define flexidag_openseg_prim_split_13___pvcn_767__denable 	1
#define flexidag_openseg_prim_split_13___pvcn_767__dpitch_num_bytes 	3264
#define flexidag_openseg_prim_split_13___pvcn_767__dram_format 	0
#define flexidag_openseg_prim_split_13___pvcn_767__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_13___pvcn_767__tile_width 	1
#define flexidag_openseg_prim_split_13___pvcn_767__tile_height 	1
#define flexidag_openseg_prim_split_13___pvcn_767__vmem_buffer_num_bytes 	3244
#define flexidag_openseg_prim_split_13___pvcn_767__dram_size_num_bytes 	3264

/* flexidag_openseg_prim_split_13 SMB_input __pvcn_768_ */
#define flexidag_openseg_prim_split_13___pvcn_768__cnngen_demangled_name 	"__pvcn_768_"
#define flexidag_openseg_prim_split_13___pvcn_768__is_constant 	1
#define flexidag_openseg_prim_split_13___pvcn_768__has_init_data 	1
#define flexidag_openseg_prim_split_13___pvcn_768__is_variable_scalar 	0
#define flexidag_openseg_prim_split_13___pvcn_768__is_bitvector 	0
#define flexidag_openseg_prim_split_13___pvcn_768__is_rlz 	0
#define flexidag_openseg_prim_split_13___pvcn_768__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_13___pvcn_768__byte_offset 	128	/* 0x00000080 */
#define flexidag_openseg_prim_split_13___pvcn_768__vbase_byte_offset 	132	/* 0x00000084 */
#define flexidag_openseg_prim_split_13___pvcn_768__dbase_byte_offset 	156	/* 0x0000009c */
#define flexidag_openseg_prim_split_13___pvcn_768__dpitchm1_byte_offset 	160	/* 0x000000a0 */
#define flexidag_openseg_prim_split_13___pvcn_768__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_13___pvcn_768__W 	96
#define flexidag_openseg_prim_split_13___pvcn_768__H 	1
#define flexidag_openseg_prim_split_13___pvcn_768__D 	1
#define flexidag_openseg_prim_split_13___pvcn_768__P 	1
#define flexidag_openseg_prim_split_13___pvcn_768__data_num_bytes 	1
#define flexidag_openseg_prim_split_13___pvcn_768__denable 	1
#define flexidag_openseg_prim_split_13___pvcn_768__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_13___pvcn_768__dram_format 	0
#define flexidag_openseg_prim_split_13___pvcn_768__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_13___pvcn_768__tile_width 	1
#define flexidag_openseg_prim_split_13___pvcn_768__tile_height 	1
#define flexidag_openseg_prim_split_13___pvcn_768__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_13___pvcn_768__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_13 SMB_input __pvcn_774_ */
#define flexidag_openseg_prim_split_13___pvcn_774__cnngen_demangled_name 	"__pvcn_774_"
#define flexidag_openseg_prim_split_13___pvcn_774__is_constant 	1
#define flexidag_openseg_prim_split_13___pvcn_774__has_init_data 	1
#define flexidag_openseg_prim_split_13___pvcn_774__is_variable_scalar 	0
#define flexidag_openseg_prim_split_13___pvcn_774__is_bitvector 	0
#define flexidag_openseg_prim_split_13___pvcn_774__is_rlz 	0
#define flexidag_openseg_prim_split_13___pvcn_774__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_13___pvcn_774__byte_offset 	168	/* 0x000000a8 */
#define flexidag_openseg_prim_split_13___pvcn_774__vbase_byte_offset 	172	/* 0x000000ac */
#define flexidag_openseg_prim_split_13___pvcn_774__dbase_byte_offset 	196	/* 0x000000c4 */
#define flexidag_openseg_prim_split_13___pvcn_774__dpitchm1_byte_offset 	200	/* 0x000000c8 */
#define flexidag_openseg_prim_split_13___pvcn_774__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_13___pvcn_774__W 	3272
#define flexidag_openseg_prim_split_13___pvcn_774__H 	1
#define flexidag_openseg_prim_split_13___pvcn_774__D 	1
#define flexidag_openseg_prim_split_13___pvcn_774__P 	1
#define flexidag_openseg_prim_split_13___pvcn_774__data_num_bytes 	1
#define flexidag_openseg_prim_split_13___pvcn_774__denable 	1
#define flexidag_openseg_prim_split_13___pvcn_774__dpitch_num_bytes 	3328
#define flexidag_openseg_prim_split_13___pvcn_774__dram_format 	0
#define flexidag_openseg_prim_split_13___pvcn_774__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_13___pvcn_774__tile_width 	1
#define flexidag_openseg_prim_split_13___pvcn_774__tile_height 	1
#define flexidag_openseg_prim_split_13___pvcn_774__vmem_buffer_num_bytes 	3272
#define flexidag_openseg_prim_split_13___pvcn_774__dram_size_num_bytes 	3328

/* flexidag_openseg_prim_split_13 SMB_input __pvcn_775_ */
#define flexidag_openseg_prim_split_13___pvcn_775__cnngen_demangled_name 	"__pvcn_775_"
#define flexidag_openseg_prim_split_13___pvcn_775__is_constant 	1
#define flexidag_openseg_prim_split_13___pvcn_775__has_init_data 	1
#define flexidag_openseg_prim_split_13___pvcn_775__is_variable_scalar 	0
#define flexidag_openseg_prim_split_13___pvcn_775__is_bitvector 	0
#define flexidag_openseg_prim_split_13___pvcn_775__is_rlz 	0
#define flexidag_openseg_prim_split_13___pvcn_775__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_13___pvcn_775__byte_offset 	208	/* 0x000000d0 */
#define flexidag_openseg_prim_split_13___pvcn_775__vbase_byte_offset 	212	/* 0x000000d4 */
#define flexidag_openseg_prim_split_13___pvcn_775__dbase_byte_offset 	236	/* 0x000000ec */
#define flexidag_openseg_prim_split_13___pvcn_775__dpitchm1_byte_offset 	240	/* 0x000000f0 */
#define flexidag_openseg_prim_split_13___pvcn_775__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_13___pvcn_775__W 	96
#define flexidag_openseg_prim_split_13___pvcn_775__H 	1
#define flexidag_openseg_prim_split_13___pvcn_775__D 	1
#define flexidag_openseg_prim_split_13___pvcn_775__P 	1
#define flexidag_openseg_prim_split_13___pvcn_775__data_num_bytes 	1
#define flexidag_openseg_prim_split_13___pvcn_775__denable 	1
#define flexidag_openseg_prim_split_13___pvcn_775__dpitch_num_bytes 	128
#define flexidag_openseg_prim_split_13___pvcn_775__dram_format 	0
#define flexidag_openseg_prim_split_13___pvcn_775__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_13___pvcn_775__tile_width 	1
#define flexidag_openseg_prim_split_13___pvcn_775__tile_height 	1
#define flexidag_openseg_prim_split_13___pvcn_775__vmem_buffer_num_bytes 	96
#define flexidag_openseg_prim_split_13___pvcn_775__dram_size_num_bytes 	128

/* flexidag_openseg_prim_split_13 HMB_input PeleeNet__stage_2_dense_block_2__concat */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_2__concat"
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_is_main_input_output 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_is_constant 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_has_init_data 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_is_variable_scalar 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_ddi_byte_size 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_is_bitvector 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_is_rlz 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_byte_offset 	248	/* 0x000000f8 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_vbase_byte_offset 	252	/* 0x000000fc */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_dbase_byte_offset 	276	/* 0x00000114 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_dpitchm1_byte_offset 	280	/* 0x00000118 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_vwidth_minus_one_byte_offset 	264	/* 0x00000108 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_vheight_minus_one_byte_offset 	266	/* 0x0000010a */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_drotate_bit_offset 	2182	/* 0x00000886 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_hflip_bit_offset 	2183	/* 0x00000887 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_vflip_bit_offset 	2184	/* 0x00000888 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_dflip_bit_offset 	2185	/* 0x00000889 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_pflip_bit_offset 	2186	/* 0x0000088a */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_W 	160
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_H 	64
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_D 	224
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_P 	1
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_data_num_bytes 	1
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_denable 	1
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_dram_format 	3
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_tile_width 	4
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_tile_height 	1
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_vmem_buffer_num_bytes 	290304
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_dram_size_num_bytes 	2293760
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_sign 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_datasize 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_expoffset 	5
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_expbits 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_drotate 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_hflip 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_vflip 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_dflip 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_pflip 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_13 HMB_output PeleeNet__stage_2_dense_block_2__concat___muli___462 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_2__concat___muli___462"
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_is_main_input_output 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_is_bitvector 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_is_rlz 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_byte_offset 	300	/* 0x0000012c */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_vbase_byte_offset 	304	/* 0x00000130 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_dbase_byte_offset 	328	/* 0x00000148 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_dpitchm1_byte_offset 	332	/* 0x0000014c */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_vwidth_minus_one_byte_offset 	316	/* 0x0000013c */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_vheight_minus_one_byte_offset 	318	/* 0x0000013e */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_drotate_bit_offset 	2598	/* 0x00000a26 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_hflip_bit_offset 	2599	/* 0x00000a27 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_vflip_bit_offset 	2600	/* 0x00000a28 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_dflip_bit_offset 	2601	/* 0x00000a29 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_pflip_bit_offset 	2602	/* 0x00000a2a */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_W 	160
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_H 	64
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_D 	224
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_P 	1
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_data_num_bytes 	1
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_denable 	1
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_dram_format 	3
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_tile_width 	4
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_tile_height 	1
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_vmem_buffer_num_bytes 	28672
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_dram_size_num_bytes 	2293760
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_sign 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_datasize 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_expoffset 	4
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_expbits 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_drotate 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_hflip 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_vflip 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_dflip 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_pflip 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_2__concat___muli___462_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_13 VCB PeleeNet__stage_2_dense_block_3__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___463___4 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___463___4_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_3__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___463___4"
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___463___4_is_bitvector 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___463___4_is_rlz 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___463___4_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___463___4_byte_offset 	352	/* 0x00000160 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___463___4_vbase_byte_offset 	360	/* 0x00000168 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___463___4_vmem_buffer_num_bytes 	40960

/* flexidag_openseg_prim_split_13 VCB PeleeNet__stage_2_dense_block_3__conv_right_0__Relu */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_0__Relu_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_3__conv_right_0__Relu"
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_0__Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_0__Relu_is_rlz 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_0__Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_0__Relu_byte_offset 	436	/* 0x000001b4 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_0__Relu_vbase_byte_offset 	444	/* 0x000001bc */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_0__Relu_vmem_buffer_num_bytes 	53760

/* flexidag_openseg_prim_split_13 HMB_output PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_main_input_output 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	484	/* 0x000001e4 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	488	/* 0x000001e8 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dbase_byte_offset 	512	/* 0x00000200 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_byte_offset 	516	/* 0x00000204 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_byte_offset 	500	/* 0x000001f4 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_byte_offset 	502	/* 0x000001f6 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate_bit_offset 	4070	/* 0x00000fe6 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip_bit_offset 	4071	/* 0x00000fe7 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip_bit_offset 	4072	/* 0x00000fe8 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip_bit_offset 	4073	/* 0x00000fe9 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip_bit_offset 	4074	/* 0x00000fea */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_W 	160
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_H 	64
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_D 	16
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_P 	1
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_data_num_bytes 	1
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_denable 	1
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_format 	3
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_width 	4
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_height 	1
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	10240
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_size_num_bytes 	163840
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_sign 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_datasize 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_expoffset 	5
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_expbits 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_13 VCB PeleeNet__stage_2_dense_block_3__conv_left_0__Relu */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_0__Relu_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_3__conv_left_0__Relu"
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_0__Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_0__Relu_is_rlz 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_0__Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_0__Relu_byte_offset 	568	/* 0x00000238 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_0__Relu_vbase_byte_offset 	576	/* 0x00000240 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_0__Relu_vmem_buffer_num_bytes 	53760

/* flexidag_openseg_prim_split_13 HMB_output PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_cnngen_demangled_name 	"PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu"
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_main_input_output 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_rlz 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_byte_offset 	616	/* 0x00000268 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vbase_byte_offset 	620	/* 0x0000026c */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dbase_byte_offset 	644	/* 0x00000284 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_byte_offset 	648	/* 0x00000288 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_byte_offset 	632	/* 0x00000278 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_byte_offset 	634	/* 0x0000027a */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate_bit_offset 	5126	/* 0x00001406 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip_bit_offset 	5127	/* 0x00001407 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip_bit_offset 	5128	/* 0x00001408 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip_bit_offset 	5129	/* 0x00001409 */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip_bit_offset 	5130	/* 0x0000140a */
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_W 	160
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_H 	64
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_D 	16
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_P 	1
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_data_num_bytes 	1
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_denable 	1
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dpitch_num_bytes 	64
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_format 	3
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_width 	4
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_tile_height 	1
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vmem_buffer_num_bytes 	10240
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_size_num_bytes 	163840
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_sign 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_datasize 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_expoffset 	4
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_expbits 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_drotate 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_hflip 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_vflip 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dflip 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_pflip 	0
#define flexidag_openseg_prim_split_13_PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_trailing_extra_elements 	0

/* flexidag_openseg_prim_split_13 SMB_output __vas_created_terminate__v0 */
#define flexidag_openseg_prim_split_13___vas_created_terminate__v0_cnngen_demangled_name 	"__vas_created_terminate__v0"
#define flexidag_openseg_prim_split_13___vas_created_terminate__v0_is_main_input_output 	0
#define flexidag_openseg_prim_split_13___vas_created_terminate__v0_is_bitvector 	1
#define flexidag_openseg_prim_split_13___vas_created_terminate__v0_is_rlz 	0
#define flexidag_openseg_prim_split_13___vas_created_terminate__v0_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_13___vas_created_terminate__v0_byte_offset 	656	/* 0x00000290 */
#define flexidag_openseg_prim_split_13___vas_created_terminate__v0_vbase_byte_offset 	660	/* 0x00000294 */
#define flexidag_openseg_prim_split_13___vas_created_terminate__v0_W 	256
#define flexidag_openseg_prim_split_13___vas_created_terminate__v0_H 	3
#define flexidag_openseg_prim_split_13___vas_created_terminate__v0_D 	1
#define flexidag_openseg_prim_split_13___vas_created_terminate__v0_P 	1
#define flexidag_openseg_prim_split_13___vas_created_terminate__v0_data_num_bytes 	1
#define flexidag_openseg_prim_split_13___vas_created_terminate__v0_denable 	0
#define flexidag_openseg_prim_split_13___vas_created_terminate__v0_dram_format 	0
#define flexidag_openseg_prim_split_13___vas_created_terminate__v0_vp_interleave_mode 	1
#define flexidag_openseg_prim_split_13___vas_created_terminate__v0_tile_width 	1
#define flexidag_openseg_prim_split_13___vas_created_terminate__v0_tile_height 	1
#define flexidag_openseg_prim_split_13___vas_created_terminate__v0_vmem_buffer_num_bytes 	96


#endif /* flexidag_openseg_prim_split_13_H */
