BRIDGEPATH=$(TARGET_APP_SRC_PATH)/peripherals/$(AMBA_CHIP_ID)/bridge

libeng_perif_${AMBA_CHIP_ID}-objs += $(BRIDGEPATH)/AmbaSbrg_Max9295_9296_REMAP.o

libeng_perif_${AMBA_CHIP_ID}-objs += $(BRIDGEPATH)/AmbaSbrg_Max9295_96712_VCX.o

libeng_perif_${AMBA_CHIP_ID}-objs += $(BRIDGEPATH)/AmbaSbrg_Max9295_96712_CPHY.o
