obj-$(CONFIG_ARCH_AMBARELLA_CV) 	+= ambacv.o

ambacv-y := ambacv_dev.o        \
	    ambacv_visorc.o     \
	    ambacv_idsporc.o    \
	    schdrmsg_kernel.o   \
	    cavalry_ioctl.o     \
	    cavalry_log.o       \
	    cavalry_cma.o       \
	    cavalry_mem.o       \
	    cavalry_misc.o      \
	    cavalry_stats.o     \
	    cavalry_visorc.o    \
	    cache.o             \
	    util.o
