/*
 * Copyright (c) 2017-2020 Ambarella International LP
 *
 * This file and its contents ("Software") are protected by intellectual
 * property rights including, without limitation, U.S. and/or foreign
 * copyrights. This Software is also the confidential and proprietary
 * information of Ambarella International LP and its licensors. You may not use,
 * reproduce, disclose, distribute, modify, or otherwise prepare derivative
 * works of this Software or any portion thereof except pursuant to a signed
 * license agreement or nondisclosure agreement with Ambarella International LP
 * or its authorized affiliates. In the absence of such an agreement, you agree
 * to promptly notify and return this Software to Ambarella International LP.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
 * MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
 * EVENT SHALL AMBARELLA INTERNATIONAL LP OR ITS AFFILIATES BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR MALFUNCTION; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef _FLEXIDAG_OPENSEG_AG_H_
#define _FLEXIDAG_OPENSEG_AG_H_

// Enable printing
#define CVTASK_PRINT

// Enable/disable poking
#undef ADD_DRAM_PITCH_MODIFIABLE
#undef CONV_1__CONV2D___BIASADD___BATCHNORM_1__FUSEDBATCHNORM___MULI___10___BATCHNORM_1__FUSEDBATCHNORM___RELU_1_DRAM_PITCH_MODIFIABLE
#undef CONV_2__CONV2D___BIASADD___BATCHNORM_2__FUSEDBATCHNORM___MULI___13___BATCHNORM_2__FUSEDBATCHNORM___RELU_2_DRAM_PITCH_MODIFIABLE
#undef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_580000004__DRAM_PITCH_MODIFIABLE
#undef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_580000009__DRAM_PITCH_MODIFIABLE
#undef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_580000014__DRAM_PITCH_MODIFIABLE
#undef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_580000019__DRAM_PITCH_MODIFIABLE
#undef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_580000024__DRAM_PITCH_MODIFIABLE
#undef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_580000029__DRAM_PITCH_MODIFIABLE
#undef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_580000034__DRAM_PITCH_MODIFIABLE
#undef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_580000039__DRAM_PITCH_MODIFIABLE
#undef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_580000044__DRAM_PITCH_MODIFIABLE
#undef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_580000049__DRAM_PITCH_MODIFIABLE
#undef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_DRAM_PITCH_MODIFIABLE
#undef CONV__CONV2D___BIASADD___BATCHNORM__FUSEDBATCHNORM___MULI___7___BATCHNORM__FUSEDBATCHNORM___PELEENET__STEM_BLOCK__STEM_BLOCK_CONV0__CONV2D___BATCHNORM__FUSEDBATCHNORM___MULI___440___1_DRAM_PITCH_MODIFIABLE
#undef MUL_1______MULI___491___EAN_2_SRC0_NHWC___NHWC___TRANSPOSE___130_DRAM_PITCH_MODIFIABLE
#undef MUL_2_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_1_DENSE_BLOCK_0__CONCAT______MULI___447_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_1_DENSE_BLOCK_1__CONCAT______MULI___450_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_1_DENSE_BLOCK_2__CONCAT_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_1_TRANSITION_LAYER__TRANSITION_LAYER_AVGPOOL__AVGPOOL______MULI___453_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_2_DENSE_BLOCK_0__CONCAT______MULI___456_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_2_DENSE_BLOCK_1__CONCAT______MULI___459_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_2_DENSE_BLOCK_2__CONCAT___MULI___462_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_2_DENSE_BLOCK_2__CONCAT_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_2_DENSE_BLOCK_3__CONV_LEFT_1__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_2_DENSE_BLOCK_3__CONV_RIGHT_1__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_2_TRANSITION_LAYER__TRANSITION_LAYER_AVGPOOL__AVGPOOL______MULI___465___MEAN_SRC0_NHWC___NHWC___TRANSPOSE___66_1243__DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_2_TRANSITION_LAYER__TRANSITION_LAYER_AVGPOOL__AVGPOOL______MULI___465___MEAN_SRC0_NHWC___NHWC___TRANSPOSE___66_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_2_TRANSITION_LAYER__TRANSITION_LAYER_AVGPOOL__AVGPOOL___MULI___466_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_2_TRANSITION_LAYER__TRANSITION_LAYER_CONV0__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_0__CONCAT______MULI___469_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_0__CONV_LEFT_0__CONV2D___BATCHNORM__FUSEDBATCHNORM___RIGHT_0__CONV2D___BATCHNORM__FUSEDBATCHNORM___MULI___467___8_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_0__CONV_RIGHT_0__RELU_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_1__CONCAT______MULI___472_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_1__CONV_LEFT_0__CONV2D___BATCHNORM__FUSEDBATCHNORM___RIGHT_0__CONV2D___CROP___400_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_1__CONV_RIGHT_2__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_2__CONCAT______MULI___475_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_2__CONV_LEFT_0__CONV2D___BATCHNORM__FUSEDBATCHNORM___RIGHT_0__CONV2D___CROP___402_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_2__CONV_RIGHT_2__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_3__CONCAT______MULI___478_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_3__CONV_LEFT_1__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_3__CONV_RIGHT_2__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_4__CONCAT______MULI___481_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_4__CONV_LEFT_1__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_4__CONV_RIGHT_2__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_5__CONCAT______MULI___484_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_5__CONV_LEFT_1__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_5__CONV_RIGHT_2__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_6__CONCAT______MULI___487_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_6__CONV_LEFT_1__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_6__CONV_RIGHT_2__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_7__CONCAT_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_7__CONV_LEFT_1__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_DENSE_BLOCK_7__CONV_RIGHT_2__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_TRANSITION_LAYER__TRANSITION_LAYER_AVGPOOL__AVGPOOL______MULI___490___MEAN_1_SRC0_NHWC___NHWC___TRANSPOSE___123_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STAGE_3_TRANSITION_LAYER__TRANSITION_LAYER_CONV0__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STEM_BLOCK__CONCAT_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STEM_BLOCK__STEM_BLOCK_CONV0__RELU______MULI___443_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STEM_BLOCK__STEM_BLOCK_CONV0__RELU___MULI___442_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STEM_BLOCK__STEM_BLOCK_CONV0__RELU___PASSTHROUGH___414_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STEM_BLOCK__STEM_BLOCK_CONV1_L0__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
#undef PELEENET__STEM_BLOCK__STEM_BLOCK_MAXPOOL1_R0__MAXPOOL_DRAM_PITCH_MODIFIABLE
#define PLACEHOLDER_DRAM_PITCH_MODIFIABLE
#define PLACEHOLDER_UV_DRAM_PITCH_MODIFIABLE
#undef RELU_DRAM_PITCH_MODIFIABLE
#undef RESIZEBILINEAR_1_DRAM_PITCH_MODIFIABLE
#undef RESIZEBILINEAR_DRAM_PITCH_MODIFIABLE
#undef SIGMOID_1_DRAM_PITCH_MODIFIABLE
#undef __PVCN_1152__DRAM_PITCH_MODIFIABLE
#undef __PVCN_80000002__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000000__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000105__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000109__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000114__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000115__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000127__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000128__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000132__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000133__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000145__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000146__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000150__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000151__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000163__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000164__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000168__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000169__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000181__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000182__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000186__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000187__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000199__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000200__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000204__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000205__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000217__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000218__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000222__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000223__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000235__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000236__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000240__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000241__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000253__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000254__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000258__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_580000259__DRAM_PITCH_MODIFIABLE
#undef CONCAT_1_DRAM_PITCH_MODIFIABLE
#undef CONCAT_DRAM_PITCH_MODIFIABLE
#undef OUT_CLASS_DRAM_PITCH_MODIFIABLE

// for errcode_enum_t
#include <cvtask_interface.h>

/* Containers for memory buffers */
typedef struct flexidag_openseg_ag_DRAM_temporary_scratchpad         flexidag_openseg_ag_dram_t;
typedef struct flexidag_openseg_ag_CMEM_temporary_scratchpad         flexidag_openseg_ag_cmem_t;
typedef struct flexidag_openseg_ag_instance_private_storage          flexidag_openseg_ag_ips_t;
typedef struct flexidag_openseg_ag_instance_private_uncached_storage flexidag_openseg_ag_ipus_t;

/* Arguments to flexidag_openseg_ag_run/init() */
typedef struct flexidag_openseg_ag_required_fields {
    flexidag_openseg_ag_dram_t *DRAM_temporary_scratchpad;
    flexidag_openseg_ag_cmem_t *CMEM_temporary_scratchpad;
    flexidag_openseg_ag_ipus_t *instance_private_uncached_storage;
    uint32_t Placeholder_addr;
    uint32_t Placeholder_uv_addr;
    uint32_t out_class_addr;
} flexidag_openseg_ag_required_fields_t;

/* Arguments to flexidag_openseg_ag_run/reset() */
typedef struct flexidag_openseg_ag_optional_fields {
#ifdef ADD_DRAM_PITCH_MODIFIABLE
    uint32_t Add_dram_pitch_enable;
    uint32_t Add_dram_pitch_value;
#endif
#ifdef CONV_1__CONV2D___BIASADD___BATCHNORM_1__FUSEDBATCHNORM___MULI___10___BATCHNORM_1__FUSEDBATCHNORM___RELU_1_DRAM_PITCH_MODIFIABLE
    uint32_t Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_dram_pitch_enable;
    uint32_t Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_dram_pitch_value;
#endif
#ifdef CONV_2__CONV2D___BIASADD___BATCHNORM_2__FUSEDBATCHNORM___MULI___13___BATCHNORM_2__FUSEDBATCHNORM___RELU_2_DRAM_PITCH_MODIFIABLE
    uint32_t Conv_2__Conv2D___BiasAdd___BatchNorm_2__FusedBatchNorm___muli___13___BatchNorm_2__FusedBatchNorm___Relu_2_dram_pitch_enable;
    uint32_t Conv_2__Conv2D___BiasAdd___BatchNorm_2__FusedBatchNorm___muli___13___BatchNorm_2__FusedBatchNorm___Relu_2_dram_pitch_value;
#endif
#ifdef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_580000004__DRAM_PITCH_MODIFIABLE
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_580000004__dram_pitch_enable;
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_580000004__dram_pitch_value;
#endif
#ifdef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_580000009__DRAM_PITCH_MODIFIABLE
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_580000009__dram_pitch_enable;
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_580000009__dram_pitch_value;
#endif
#ifdef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_580000014__DRAM_PITCH_MODIFIABLE
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_580000014__dram_pitch_enable;
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_580000014__dram_pitch_value;
#endif
#ifdef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_580000019__DRAM_PITCH_MODIFIABLE
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_580000019__dram_pitch_enable;
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_580000019__dram_pitch_value;
#endif
#ifdef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_580000024__DRAM_PITCH_MODIFIABLE
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_580000024__dram_pitch_enable;
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_580000024__dram_pitch_value;
#endif
#ifdef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_580000029__DRAM_PITCH_MODIFIABLE
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_580000029__dram_pitch_enable;
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_580000029__dram_pitch_value;
#endif
#ifdef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_580000034__DRAM_PITCH_MODIFIABLE
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_580000034__dram_pitch_enable;
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_580000034__dram_pitch_value;
#endif
#ifdef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_580000039__DRAM_PITCH_MODIFIABLE
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_580000039__dram_pitch_enable;
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_580000039__dram_pitch_value;
#endif
#ifdef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_580000044__DRAM_PITCH_MODIFIABLE
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_580000044__dram_pitch_enable;
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_580000044__dram_pitch_value;
#endif
#ifdef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_580000049__DRAM_PITCH_MODIFIABLE
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_580000049__dram_pitch_enable;
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_580000049__dram_pitch_value;
#endif
#ifdef CONV_5__CONV2D___BIASADD___BATCHNORM_5__FUSEDBATCHNORM___MULI___136___BATCHNORM_5__FUSEDBATCHNORM___RELU_3___MULI___492___MEAN_3_SRC0_NHWC___NHWC___TRANSPOSE___138_DRAM_PITCH_MODIFIABLE
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_dram_pitch_enable;
    uint32_t Conv_5__Conv2D___BiasAdd___BatchNorm_5__FusedBatchNorm___muli___136___BatchNorm_5__FusedBatchNorm___Relu_3___muli___492___Mean_3_src0_nhwc___nhwc___transpose___138_dram_pitch_value;
#endif
#ifdef CONV__CONV2D___BIASADD___BATCHNORM__FUSEDBATCHNORM___MULI___7___BATCHNORM__FUSEDBATCHNORM___PELEENET__STEM_BLOCK__STEM_BLOCK_CONV0__CONV2D___BATCHNORM__FUSEDBATCHNORM___MULI___440___1_DRAM_PITCH_MODIFIABLE
    uint32_t Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm___muli___440___1_dram_pitch_enable;
    uint32_t Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm___muli___440___1_dram_pitch_value;
#endif
#ifdef MUL_1______MULI___491___EAN_2_SRC0_NHWC___NHWC___TRANSPOSE___130_DRAM_PITCH_MODIFIABLE
    uint32_t Mul_1______muli___491___ean_2_src0_nhwc___nhwc___transpose___130_dram_pitch_enable;
    uint32_t Mul_1______muli___491___ean_2_src0_nhwc___nhwc___transpose___130_dram_pitch_value;
#endif
#ifdef MUL_2_DRAM_PITCH_MODIFIABLE
    uint32_t Mul_2_dram_pitch_enable;
    uint32_t Mul_2_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_1_DENSE_BLOCK_0__CONCAT______MULI___447_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_1_dense_block_0__concat______muli___447_dram_pitch_enable;
    uint32_t PeleeNet__stage_1_dense_block_0__concat______muli___447_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_1_DENSE_BLOCK_1__CONCAT______MULI___450_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_1_dense_block_1__concat______muli___450_dram_pitch_enable;
    uint32_t PeleeNet__stage_1_dense_block_1__concat______muli___450_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_1_DENSE_BLOCK_2__CONCAT_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_1_dense_block_2__concat_dram_pitch_enable;
    uint32_t PeleeNet__stage_1_dense_block_2__concat_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_1_TRANSITION_LAYER__TRANSITION_LAYER_AVGPOOL__AVGPOOL______MULI___453_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_dram_pitch_enable;
    uint32_t PeleeNet__stage_1_transition_layer__transition_layer_avgpool__AvgPool______muli___453_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_2_DENSE_BLOCK_0__CONCAT______MULI___456_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_2_dense_block_0__concat______muli___456_dram_pitch_enable;
    uint32_t PeleeNet__stage_2_dense_block_0__concat______muli___456_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_2_DENSE_BLOCK_1__CONCAT______MULI___459_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_2_dense_block_1__concat______muli___459_dram_pitch_enable;
    uint32_t PeleeNet__stage_2_dense_block_1__concat______muli___459_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_2_DENSE_BLOCK_2__CONCAT___MULI___462_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_2_dense_block_2__concat___muli___462_dram_pitch_enable;
    uint32_t PeleeNet__stage_2_dense_block_2__concat___muli___462_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_2_DENSE_BLOCK_2__CONCAT_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_2_dense_block_2__concat_dram_pitch_enable;
    uint32_t PeleeNet__stage_2_dense_block_2__concat_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_2_DENSE_BLOCK_3__CONV_LEFT_1__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_enable;
    uint32_t PeleeNet__stage_2_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_2_DENSE_BLOCK_3__CONV_RIGHT_1__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_enable;
    uint32_t PeleeNet__stage_2_dense_block_3__conv_right_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_2_TRANSITION_LAYER__TRANSITION_LAYER_AVGPOOL__AVGPOOL______MULI___465___MEAN_SRC0_NHWC___NHWC___TRANSPOSE___66_1243__DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__dram_pitch_enable;
    uint32_t PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_1243__dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_2_TRANSITION_LAYER__TRANSITION_LAYER_AVGPOOL__AVGPOOL______MULI___465___MEAN_SRC0_NHWC___NHWC___TRANSPOSE___66_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_dram_pitch_enable;
    uint32_t PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool______muli___465___Mean_src0_nhwc___nhwc___transpose___66_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_2_TRANSITION_LAYER__TRANSITION_LAYER_AVGPOOL__AVGPOOL___MULI___466_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_dram_pitch_enable;
    uint32_t PeleeNet__stage_2_transition_layer__transition_layer_avgpool__AvgPool___muli___466_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_2_TRANSITION_LAYER__TRANSITION_LAYER_CONV0__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_enable;
    uint32_t PeleeNet__stage_2_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_0__CONCAT______MULI___469_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_0__concat______muli___469_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_0__concat______muli___469_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_0__CONV_LEFT_0__CONV2D___BATCHNORM__FUSEDBATCHNORM___RIGHT_0__CONV2D___BATCHNORM__FUSEDBATCHNORM___MULI___467___8_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_0__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___BatchNorm__FusedBatchNorm___muli___467___8_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_0__CONV_RIGHT_0__RELU_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_0__conv_right_0__Relu_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_1__CONCAT______MULI___472_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_1__concat______muli___472_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_1__concat______muli___472_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_1__CONV_LEFT_0__CONV2D___BATCHNORM__FUSEDBATCHNORM___RIGHT_0__CONV2D___CROP___400_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_1__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___400_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_1__CONV_RIGHT_2__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_1__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_2__CONCAT______MULI___475_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_2__concat______muli___475_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_2__concat______muli___475_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_2__CONV_LEFT_0__CONV2D___BATCHNORM__FUSEDBATCHNORM___RIGHT_0__CONV2D___CROP___402_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_2__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___402_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_2__conv_left_0__Conv2D___BatchNorm__FusedBatchNorm___right_0__Conv2D___crop___402_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_2__CONV_RIGHT_2__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_2__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_2__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_3__CONCAT______MULI___478_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_3__concat______muli___478_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_3__concat______muli___478_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_3__CONV_LEFT_1__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_3__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_3__CONV_RIGHT_2__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_3__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_4__CONCAT______MULI___481_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_4__concat______muli___481_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_4__concat______muli___481_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_4__CONV_LEFT_1__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_4__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_4__CONV_RIGHT_2__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_4__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_5__CONCAT______MULI___484_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_5__concat______muli___484_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_5__concat______muli___484_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_5__CONV_LEFT_1__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_5__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_5__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_5__CONV_RIGHT_2__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_5__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_5__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_6__CONCAT______MULI___487_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_6__concat______muli___487_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_6__concat______muli___487_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_6__CONV_LEFT_1__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_6__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_6__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_6__CONV_RIGHT_2__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_6__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_6__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_7__CONCAT_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_7__concat_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_7__concat_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_7__CONV_LEFT_1__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_7__conv_left_1__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_DENSE_BLOCK_7__CONV_RIGHT_2__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_dense_block_7__conv_right_2__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_TRANSITION_LAYER__TRANSITION_LAYER_AVGPOOL__AVGPOOL______MULI___490___MEAN_1_SRC0_NHWC___NHWC___TRANSPOSE___123_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_transition_layer__transition_layer_avgpool__AvgPool______muli___490___Mean_1_src0_nhwc___nhwc___transpose___123_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_transition_layer__transition_layer_avgpool__AvgPool______muli___490___Mean_1_src0_nhwc___nhwc___transpose___123_dram_pitch_value;
#endif
#ifdef PELEENET__STAGE_3_TRANSITION_LAYER__TRANSITION_LAYER_CONV0__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stage_3_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_enable;
    uint32_t PeleeNet__stage_3_transition_layer__transition_layer_conv0__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_value;
#endif
#ifdef PELEENET__STEM_BLOCK__CONCAT_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stem_block__concat_dram_pitch_enable;
    uint32_t PeleeNet__stem_block__concat_dram_pitch_value;
#endif
#ifdef PELEENET__STEM_BLOCK__STEM_BLOCK_CONV0__RELU______MULI___443_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stem_block__stem_block_conv0__Relu______muli___443_dram_pitch_enable;
    uint32_t PeleeNet__stem_block__stem_block_conv0__Relu______muli___443_dram_pitch_value;
#endif
#ifdef PELEENET__STEM_BLOCK__STEM_BLOCK_CONV0__RELU___MULI___442_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stem_block__stem_block_conv0__Relu___muli___442_dram_pitch_enable;
    uint32_t PeleeNet__stem_block__stem_block_conv0__Relu___muli___442_dram_pitch_value;
#endif
#ifdef PELEENET__STEM_BLOCK__STEM_BLOCK_CONV0__RELU___PASSTHROUGH___414_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stem_block__stem_block_conv0__Relu___passthrough___414_dram_pitch_enable;
    uint32_t PeleeNet__stem_block__stem_block_conv0__Relu___passthrough___414_dram_pitch_value;
#endif
#ifdef PELEENET__STEM_BLOCK__STEM_BLOCK_CONV1_L0__CONV2D___BATCHNORM__FUSEDBATCHNORM___RELU_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stem_block__stem_block_conv1_l0__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_enable;
    uint32_t PeleeNet__stem_block__stem_block_conv1_l0__Conv2D___BatchNorm__FusedBatchNorm___Relu_dram_pitch_value;
#endif
#ifdef PELEENET__STEM_BLOCK__STEM_BLOCK_MAXPOOL1_R0__MAXPOOL_DRAM_PITCH_MODIFIABLE
    uint32_t PeleeNet__stem_block__stem_block_maxpool1_r0__MaxPool_dram_pitch_enable;
    uint32_t PeleeNet__stem_block__stem_block_maxpool1_r0__MaxPool_dram_pitch_value;
#endif
#ifdef PLACEHOLDER_DRAM_PITCH_MODIFIABLE
    uint32_t Placeholder_dram_pitch_enable;
    uint32_t Placeholder_dram_pitch_value;
#endif
#ifdef PLACEHOLDER_UV_DRAM_PITCH_MODIFIABLE
    uint32_t Placeholder_uv_dram_pitch_enable;
    uint32_t Placeholder_uv_dram_pitch_value;
#endif
#ifdef RELU_DRAM_PITCH_MODIFIABLE
    uint32_t Relu_dram_pitch_enable;
    uint32_t Relu_dram_pitch_value;
#endif
#ifdef RESIZEBILINEAR_1_DRAM_PITCH_MODIFIABLE
    uint32_t ResizeBilinear_1_dram_pitch_enable;
    uint32_t ResizeBilinear_1_dram_pitch_value;
#endif
#ifdef RESIZEBILINEAR_DRAM_PITCH_MODIFIABLE
    uint32_t ResizeBilinear_dram_pitch_enable;
    uint32_t ResizeBilinear_dram_pitch_value;
#endif
#ifdef SIGMOID_1_DRAM_PITCH_MODIFIABLE
    uint32_t Sigmoid_1_dram_pitch_enable;
    uint32_t Sigmoid_1_dram_pitch_value;
#endif
#ifdef __PVCN_1152__DRAM_PITCH_MODIFIABLE
    uint32_t __pvcn_1152__dram_pitch_enable;
    uint32_t __pvcn_1152__dram_pitch_value;
#endif
#ifdef __PVCN_80000002__DRAM_PITCH_MODIFIABLE
    uint32_t __pvcn_80000002__dram_pitch_enable;
    uint32_t __pvcn_80000002__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000000__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000000__dram_pitch_enable;
    uint32_t concat_1_580000000__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000105__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000105__dram_pitch_enable;
    uint32_t concat_1_580000105__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000109__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000109__dram_pitch_enable;
    uint32_t concat_1_580000109__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000114__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000114__dram_pitch_enable;
    uint32_t concat_1_580000114__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000115__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000115__dram_pitch_enable;
    uint32_t concat_1_580000115__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000127__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000127__dram_pitch_enable;
    uint32_t concat_1_580000127__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000128__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000128__dram_pitch_enable;
    uint32_t concat_1_580000128__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000132__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000132__dram_pitch_enable;
    uint32_t concat_1_580000132__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000133__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000133__dram_pitch_enable;
    uint32_t concat_1_580000133__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000145__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000145__dram_pitch_enable;
    uint32_t concat_1_580000145__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000146__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000146__dram_pitch_enable;
    uint32_t concat_1_580000146__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000150__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000150__dram_pitch_enable;
    uint32_t concat_1_580000150__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000151__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000151__dram_pitch_enable;
    uint32_t concat_1_580000151__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000163__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000163__dram_pitch_enable;
    uint32_t concat_1_580000163__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000164__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000164__dram_pitch_enable;
    uint32_t concat_1_580000164__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000168__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000168__dram_pitch_enable;
    uint32_t concat_1_580000168__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000169__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000169__dram_pitch_enable;
    uint32_t concat_1_580000169__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000181__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000181__dram_pitch_enable;
    uint32_t concat_1_580000181__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000182__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000182__dram_pitch_enable;
    uint32_t concat_1_580000182__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000186__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000186__dram_pitch_enable;
    uint32_t concat_1_580000186__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000187__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000187__dram_pitch_enable;
    uint32_t concat_1_580000187__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000199__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000199__dram_pitch_enable;
    uint32_t concat_1_580000199__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000200__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000200__dram_pitch_enable;
    uint32_t concat_1_580000200__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000204__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000204__dram_pitch_enable;
    uint32_t concat_1_580000204__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000205__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000205__dram_pitch_enable;
    uint32_t concat_1_580000205__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000217__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000217__dram_pitch_enable;
    uint32_t concat_1_580000217__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000218__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000218__dram_pitch_enable;
    uint32_t concat_1_580000218__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000222__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000222__dram_pitch_enable;
    uint32_t concat_1_580000222__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000223__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000223__dram_pitch_enable;
    uint32_t concat_1_580000223__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000235__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000235__dram_pitch_enable;
    uint32_t concat_1_580000235__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000236__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000236__dram_pitch_enable;
    uint32_t concat_1_580000236__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000240__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000240__dram_pitch_enable;
    uint32_t concat_1_580000240__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000241__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000241__dram_pitch_enable;
    uint32_t concat_1_580000241__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000253__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000253__dram_pitch_enable;
    uint32_t concat_1_580000253__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000254__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000254__dram_pitch_enable;
    uint32_t concat_1_580000254__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000258__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000258__dram_pitch_enable;
    uint32_t concat_1_580000258__dram_pitch_value;
#endif
#ifdef CONCAT_1_580000259__DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_580000259__dram_pitch_enable;
    uint32_t concat_1_580000259__dram_pitch_value;
#endif
#ifdef CONCAT_1_DRAM_PITCH_MODIFIABLE
    uint32_t concat_1_dram_pitch_enable;
    uint32_t concat_1_dram_pitch_value;
#endif
#ifdef CONCAT_DRAM_PITCH_MODIFIABLE
    uint32_t concat_dram_pitch_enable;
    uint32_t concat_dram_pitch_value;
#endif
#ifdef OUT_CLASS_DRAM_PITCH_MODIFIABLE
    uint32_t out_class_dram_pitch_enable;
    uint32_t out_class_dram_pitch_value;
#endif
} flexidag_openseg_ag_optional_fields_t;

/* Core functions */
// Reads CVTable
errcode_enum_t flexidag_openseg_ag_init (
    flexidag_openseg_ag_ips_t             *ctxt
);
// run() is NOT re-entrant with respect to run() calls for other DAGs
errcode_enum_t flexidag_openseg_ag_run (
    flexidag_openseg_ag_ips_t             *ctxt,
    flexidag_openseg_ag_required_fields_t *r_args,
    flexidag_openseg_ag_optional_fields_t *o_args
);
// Reset all fields to their respective default values
errcode_enum_t flexidag_openseg_ag_reset (
    flexidag_openseg_ag_optional_fields_t *o_args
);

/* Concretize struct definitions */
#include "flexidag_openseg_ag_private.h"
#endif

