////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2020 Ambarella, Inc.
////////////////////////////////////////////////////////////////////////////////
// This file and its contents ("Software") are protected
// by intellectual property rights including, without limitation, U.S.
// and/or foreign copyrights.  This Software is also the confidential
// and proprietary information of Ambarella, Inc. and its licensors.
// You may not use, reproduce, disclose, distribute, modify, or
// otherwise prepare derivative works of this Software or any portion
// thereof except pursuant to a signed license agreement or
// nondisclosure agreement with Ambarella, Inc. or its authorized
// affiliates.  In the absence of such an agreement, you agree to
// promptly notify and return this Software to Ambarella, Inc.
//
// THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
// WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL AMBARELLA, INC. OR ITS
// AFFILIATES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; COMPUTER FAILURE OR MALFUNCTION; OR BUSINESS INTERRUPTION)
// HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
// OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////
#ifndef flexidag_openseg_prim_split_6_H
#define flexidag_openseg_prim_split_6_H

#define vas_gen_header_version                  	7

/* dag name */
#define flexidag_openseg_prim_split_6_DAG_NAME  	"flexidag_openseg_prim_split_6"

/* VDG file info */
#define flexidag_openseg_prim_split_6_vdg_name  	"flexidag_openseg_split_6.vdg"

/* VDG DAG memory info */
#define flexidag_openseg_prim_split_6_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_6_byte_size 	684	/* 0x000002ac */
#define flexidag_openseg_prim_split_6_preferred_dram_xfer_size 	1

/* flexidag_openseg_prim_split_6 VMEM info */
#define flexidag_openseg_prim_split_6_use_ping_pong_vmem 	0
#define flexidag_openseg_prim_split_6_VMEM_start 	4096	/* 0x00001000 */
#define flexidag_openseg_prim_split_6_VMEM_end  	2074568	/* 0x001fa7c8 */
#define flexidag_openseg_prim_split_6_image_start 	2011756	/* 0x001eb26c */
#define flexidag_openseg_prim_split_6_image_size 	63496	/* 0x0000f808 */
#define flexidag_openseg_prim_split_6_dagbin_start 	2074568	/* 0x001fa7c8 */

/* flexidag_openseg_prim_split_6 DAG info */
#define flexidag_openseg_prim_split_6_estimated_cycles 	54517808

/*******************************************************************************
 * DAG byte offset info for HMB/SMB/VCB and their fields
 * in DAG 'flexidag_openseg_prim_split_6' in source file 'flexidag_openseg_split_6.vas'
 ******************************************************************************/
/* flexidag_openseg_prim_split_6 HMB_input Mul_2 */
#define flexidag_openseg_prim_split_6_Mul_2_cnngen_demangled_name 	"Mul_2"
#define flexidag_openseg_prim_split_6_Mul_2_is_main_input_output 	0
#define flexidag_openseg_prim_split_6_Mul_2_is_constant 	0
#define flexidag_openseg_prim_split_6_Mul_2_has_init_data 	0
#define flexidag_openseg_prim_split_6_Mul_2_is_variable_scalar 	0
#define flexidag_openseg_prim_split_6_Mul_2_ddi_byte_size 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_6_Mul_2_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_6_Mul_2_is_bitvector 	0
#define flexidag_openseg_prim_split_6_Mul_2_is_rlz 	0
#define flexidag_openseg_prim_split_6_Mul_2_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_6_Mul_2_is_twelve_bit_packed 	0
#define flexidag_openseg_prim_split_6_Mul_2_byte_offset 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_6_Mul_2_vbase_byte_offset 	4	/* 0x00000004 */
#define flexidag_openseg_prim_split_6_Mul_2_dbase_byte_offset 	28	/* 0x0000001c */
#define flexidag_openseg_prim_split_6_Mul_2_dpitchm1_byte_offset 	32	/* 0x00000020 */
#define flexidag_openseg_prim_split_6_Mul_2_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6_Mul_2_vwidth_minus_one_byte_offset 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6_Mul_2_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6_Mul_2_vheight_minus_one_byte_offset 	18	/* 0x00000012 */
#define flexidag_openseg_prim_split_6_Mul_2_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6_Mul_2_drotate_bit_offset 	198	/* 0x000000c6 */
#define flexidag_openseg_prim_split_6_Mul_2_hflip_bit_offset 	199	/* 0x000000c7 */
#define flexidag_openseg_prim_split_6_Mul_2_vflip_bit_offset 	200	/* 0x000000c8 */
#define flexidag_openseg_prim_split_6_Mul_2_dflip_bit_offset 	201	/* 0x000000c9 */
#define flexidag_openseg_prim_split_6_Mul_2_pflip_bit_offset 	202	/* 0x000000ca */
#define flexidag_openseg_prim_split_6_Mul_2_W   	40
#define flexidag_openseg_prim_split_6_Mul_2_H   	16
#define flexidag_openseg_prim_split_6_Mul_2_D   	512
#define flexidag_openseg_prim_split_6_Mul_2_P   	1
#define flexidag_openseg_prim_split_6_Mul_2_data_num_bytes 	2
#define flexidag_openseg_prim_split_6_Mul_2_denable 	1
#define flexidag_openseg_prim_split_6_Mul_2_dpitch_num_bytes 	32
#define flexidag_openseg_prim_split_6_Mul_2_dram_format 	3
#define flexidag_openseg_prim_split_6_Mul_2_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_6_Mul_2_tile_width 	4
#define flexidag_openseg_prim_split_6_Mul_2_tile_height 	1
#define flexidag_openseg_prim_split_6_Mul_2_vmem_buffer_num_bytes 	122892
#define flexidag_openseg_prim_split_6_Mul_2_dram_size_num_bytes 	655360
#define flexidag_openseg_prim_split_6_Mul_2_sign 	0
#define flexidag_openseg_prim_split_6_Mul_2_datasize 	1
#define flexidag_openseg_prim_split_6_Mul_2_expoffset 	13
#define flexidag_openseg_prim_split_6_Mul_2_expbits 	0
#define flexidag_openseg_prim_split_6_Mul_2_drotate 	0
#define flexidag_openseg_prim_split_6_Mul_2_hflip 	0
#define flexidag_openseg_prim_split_6_Mul_2_vflip 	0
#define flexidag_openseg_prim_split_6_Mul_2_dflip 	0
#define flexidag_openseg_prim_split_6_Mul_2_pflip 	0

/* flexidag_openseg_prim_split_6 HMB_input ResizeBilinear */
#define flexidag_openseg_prim_split_6_ResizeBilinear_cnngen_demangled_name 	"ResizeBilinear"
#define flexidag_openseg_prim_split_6_ResizeBilinear_is_main_input_output 	0
#define flexidag_openseg_prim_split_6_ResizeBilinear_is_constant 	0
#define flexidag_openseg_prim_split_6_ResizeBilinear_has_init_data 	0
#define flexidag_openseg_prim_split_6_ResizeBilinear_is_variable_scalar 	0
#define flexidag_openseg_prim_split_6_ResizeBilinear_ddi_byte_size 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_6_ResizeBilinear_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_6_ResizeBilinear_is_bitvector 	0
#define flexidag_openseg_prim_split_6_ResizeBilinear_is_rlz 	0
#define flexidag_openseg_prim_split_6_ResizeBilinear_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_6_ResizeBilinear_is_twelve_bit_packed 	0
#define flexidag_openseg_prim_split_6_ResizeBilinear_byte_offset 	36	/* 0x00000024 */
#define flexidag_openseg_prim_split_6_ResizeBilinear_vbase_byte_offset 	40	/* 0x00000028 */
#define flexidag_openseg_prim_split_6_ResizeBilinear_dbase_byte_offset 	64	/* 0x00000040 */
#define flexidag_openseg_prim_split_6_ResizeBilinear_dpitchm1_byte_offset 	68	/* 0x00000044 */
#define flexidag_openseg_prim_split_6_ResizeBilinear_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6_ResizeBilinear_vwidth_minus_one_byte_offset 	52	/* 0x00000034 */
#define flexidag_openseg_prim_split_6_ResizeBilinear_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6_ResizeBilinear_vheight_minus_one_byte_offset 	54	/* 0x00000036 */
#define flexidag_openseg_prim_split_6_ResizeBilinear_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6_ResizeBilinear_drotate_bit_offset 	486	/* 0x000001e6 */
#define flexidag_openseg_prim_split_6_ResizeBilinear_hflip_bit_offset 	487	/* 0x000001e7 */
#define flexidag_openseg_prim_split_6_ResizeBilinear_vflip_bit_offset 	488	/* 0x000001e8 */
#define flexidag_openseg_prim_split_6_ResizeBilinear_dflip_bit_offset 	489	/* 0x000001e9 */
#define flexidag_openseg_prim_split_6_ResizeBilinear_pflip_bit_offset 	490	/* 0x000001ea */
#define flexidag_openseg_prim_split_6_ResizeBilinear_W 	160
#define flexidag_openseg_prim_split_6_ResizeBilinear_H 	64
#define flexidag_openseg_prim_split_6_ResizeBilinear_D 	256
#define flexidag_openseg_prim_split_6_ResizeBilinear_P 	1
#define flexidag_openseg_prim_split_6_ResizeBilinear_data_num_bytes 	2
#define flexidag_openseg_prim_split_6_ResizeBilinear_denable 	1
#define flexidag_openseg_prim_split_6_ResizeBilinear_dpitch_num_bytes 	32
#define flexidag_openseg_prim_split_6_ResizeBilinear_dram_format 	3
#define flexidag_openseg_prim_split_6_ResizeBilinear_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_6_ResizeBilinear_tile_width 	4
#define flexidag_openseg_prim_split_6_ResizeBilinear_tile_height 	2
#define flexidag_openseg_prim_split_6_ResizeBilinear_vmem_buffer_num_bytes 	331776
#define flexidag_openseg_prim_split_6_ResizeBilinear_dram_size_num_bytes 	5242880
#define flexidag_openseg_prim_split_6_ResizeBilinear_sign 	0
#define flexidag_openseg_prim_split_6_ResizeBilinear_datasize 	1
#define flexidag_openseg_prim_split_6_ResizeBilinear_expoffset 	13
#define flexidag_openseg_prim_split_6_ResizeBilinear_expbits 	0
#define flexidag_openseg_prim_split_6_ResizeBilinear_drotate 	0
#define flexidag_openseg_prim_split_6_ResizeBilinear_hflip 	0
#define flexidag_openseg_prim_split_6_ResizeBilinear_vflip 	0
#define flexidag_openseg_prim_split_6_ResizeBilinear_dflip 	0
#define flexidag_openseg_prim_split_6_ResizeBilinear_pflip 	0

/* flexidag_openseg_prim_split_6 HMB_input Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm */
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_cnngen_demangled_name 	"Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm"
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_is_main_input_output 	0
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_is_constant 	0
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_has_init_data 	0
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_is_variable_scalar 	0
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_ddi_byte_size 	0	/* 0x00000000 */
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_ddi_byte_offset 	4294967295	/* 0xffffffff */
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_is_bitvector 	0
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_is_rlz 	0
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_is_twelve_bit_packed 	0
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_byte_offset 	76	/* 0x0000004c */
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_vbase_byte_offset 	80	/* 0x00000050 */
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_dbase_byte_offset 	104	/* 0x00000068 */
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_dpitchm1_byte_offset 	108	/* 0x0000006c */
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_vwidth_minus_one_byte_offset 	92	/* 0x0000005c */
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_vheight_minus_one_byte_offset 	94	/* 0x0000005e */
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_drotate_bit_offset 	806	/* 0x00000326 */
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_hflip_bit_offset 	807	/* 0x00000327 */
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_vflip_bit_offset 	808	/* 0x00000328 */
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_dflip_bit_offset 	809	/* 0x00000329 */
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_pflip_bit_offset 	810	/* 0x0000032a */
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_W 	640
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_H 	256
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_D 	96
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_P 	1
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_data_num_bytes 	1
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_denable 	1
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_dpitch_num_bytes 	32
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_dram_format 	3
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_tile_width 	4
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_tile_height 	1
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_vmem_buffer_num_bytes 	50688
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_dram_size_num_bytes 	15728640
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_sign 	1
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_datasize 	0
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_expoffset 	5
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_expbits 	0
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_drotate 	0
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_hflip 	0
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_vflip 	0
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_dflip 	0
#define flexidag_openseg_prim_split_6_Conv__Conv2D___BiasAdd___BatchNorm__FusedBatchNorm___muli___7___BatchNorm__FusedBatchNorm___PeleeNet__stem_block__stem_block_conv0__Conv2D___BatchNorm__FusedBatchNorm_pflip 	0

/* flexidag_openseg_prim_split_6 SMB_input __pvcn_1385_ */
#define flexidag_openseg_prim_split_6___pvcn_1385__cnngen_demangled_name 	"__pvcn_1385_"
#define flexidag_openseg_prim_split_6___pvcn_1385__is_constant 	1
#define flexidag_openseg_prim_split_6___pvcn_1385__has_init_data 	1
#define flexidag_openseg_prim_split_6___pvcn_1385__is_variable_scalar 	0
#define flexidag_openseg_prim_split_6___pvcn_1385__is_bitvector 	0
#define flexidag_openseg_prim_split_6___pvcn_1385__is_rlz 	0
#define flexidag_openseg_prim_split_6___pvcn_1385__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_6___pvcn_1385__is_twelve_bit_packed 	0
#define flexidag_openseg_prim_split_6___pvcn_1385__byte_offset 	116	/* 0x00000074 */
#define flexidag_openseg_prim_split_6___pvcn_1385__vbase_byte_offset 	120	/* 0x00000078 */
#define flexidag_openseg_prim_split_6___pvcn_1385__dbase_byte_offset 	144	/* 0x00000090 */
#define flexidag_openseg_prim_split_6___pvcn_1385__dpitchm1_byte_offset 	148	/* 0x00000094 */
#define flexidag_openseg_prim_split_6___pvcn_1385__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6___pvcn_1385__W 	4
#define flexidag_openseg_prim_split_6___pvcn_1385__H 	1
#define flexidag_openseg_prim_split_6___pvcn_1385__D 	1
#define flexidag_openseg_prim_split_6___pvcn_1385__P 	1
#define flexidag_openseg_prim_split_6___pvcn_1385__data_num_bytes 	4
#define flexidag_openseg_prim_split_6___pvcn_1385__denable 	1
#define flexidag_openseg_prim_split_6___pvcn_1385__dpitch_num_bytes 	32
#define flexidag_openseg_prim_split_6___pvcn_1385__dram_format 	0
#define flexidag_openseg_prim_split_6___pvcn_1385__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_6___pvcn_1385__tile_width 	1
#define flexidag_openseg_prim_split_6___pvcn_1385__tile_height 	1
#define flexidag_openseg_prim_split_6___pvcn_1385__vmem_buffer_num_bytes 	16
#define flexidag_openseg_prim_split_6___pvcn_1385__dram_size_num_bytes 	32

/* flexidag_openseg_prim_split_6 SMB_input __pvcn_160008_ */
#define flexidag_openseg_prim_split_6___pvcn_160008__cnngen_demangled_name 	"__pvcn_160008_"
#define flexidag_openseg_prim_split_6___pvcn_160008__is_constant 	1
#define flexidag_openseg_prim_split_6___pvcn_160008__has_init_data 	1
#define flexidag_openseg_prim_split_6___pvcn_160008__is_variable_scalar 	0
#define flexidag_openseg_prim_split_6___pvcn_160008__is_bitvector 	0
#define flexidag_openseg_prim_split_6___pvcn_160008__is_rlz 	0
#define flexidag_openseg_prim_split_6___pvcn_160008__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_6___pvcn_160008__is_twelve_bit_packed 	0
#define flexidag_openseg_prim_split_6___pvcn_160008__byte_offset 	152	/* 0x00000098 */
#define flexidag_openseg_prim_split_6___pvcn_160008__vbase_byte_offset 	156	/* 0x0000009c */
#define flexidag_openseg_prim_split_6___pvcn_160008__dbase_byte_offset 	180	/* 0x000000b4 */
#define flexidag_openseg_prim_split_6___pvcn_160008__dpitchm1_byte_offset 	184	/* 0x000000b8 */
#define flexidag_openseg_prim_split_6___pvcn_160008__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6___pvcn_160008__W 	30796
#define flexidag_openseg_prim_split_6___pvcn_160008__H 	1
#define flexidag_openseg_prim_split_6___pvcn_160008__D 	1
#define flexidag_openseg_prim_split_6___pvcn_160008__P 	1
#define flexidag_openseg_prim_split_6___pvcn_160008__data_num_bytes 	1
#define flexidag_openseg_prim_split_6___pvcn_160008__denable 	1
#define flexidag_openseg_prim_split_6___pvcn_160008__dpitch_num_bytes 	30816
#define flexidag_openseg_prim_split_6___pvcn_160008__dram_format 	0
#define flexidag_openseg_prim_split_6___pvcn_160008__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_6___pvcn_160008__tile_width 	1
#define flexidag_openseg_prim_split_6___pvcn_160008__tile_height 	1
#define flexidag_openseg_prim_split_6___pvcn_160008__vmem_buffer_num_bytes 	30796
#define flexidag_openseg_prim_split_6___pvcn_160008__dram_size_num_bytes 	30816

/* flexidag_openseg_prim_split_6 SMB_input __pvcn_160011_ */
#define flexidag_openseg_prim_split_6___pvcn_160011__cnngen_demangled_name 	"__pvcn_160011_"
#define flexidag_openseg_prim_split_6___pvcn_160011__is_constant 	1
#define flexidag_openseg_prim_split_6___pvcn_160011__has_init_data 	1
#define flexidag_openseg_prim_split_6___pvcn_160011__is_variable_scalar 	0
#define flexidag_openseg_prim_split_6___pvcn_160011__is_bitvector 	0
#define flexidag_openseg_prim_split_6___pvcn_160011__is_rlz 	0
#define flexidag_openseg_prim_split_6___pvcn_160011__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_6___pvcn_160011__is_twelve_bit_packed 	0
#define flexidag_openseg_prim_split_6___pvcn_160011__byte_offset 	192	/* 0x000000c0 */
#define flexidag_openseg_prim_split_6___pvcn_160011__vbase_byte_offset 	196	/* 0x000000c4 */
#define flexidag_openseg_prim_split_6___pvcn_160011__dbase_byte_offset 	220	/* 0x000000dc */
#define flexidag_openseg_prim_split_6___pvcn_160011__dpitchm1_byte_offset 	224	/* 0x000000e0 */
#define flexidag_openseg_prim_split_6___pvcn_160011__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6___pvcn_160011__W 	30880
#define flexidag_openseg_prim_split_6___pvcn_160011__H 	1
#define flexidag_openseg_prim_split_6___pvcn_160011__D 	1
#define flexidag_openseg_prim_split_6___pvcn_160011__P 	1
#define flexidag_openseg_prim_split_6___pvcn_160011__data_num_bytes 	1
#define flexidag_openseg_prim_split_6___pvcn_160011__denable 	1
#define flexidag_openseg_prim_split_6___pvcn_160011__dpitch_num_bytes 	30880
#define flexidag_openseg_prim_split_6___pvcn_160011__dram_format 	0
#define flexidag_openseg_prim_split_6___pvcn_160011__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_6___pvcn_160011__tile_width 	1
#define flexidag_openseg_prim_split_6___pvcn_160011__tile_height 	1
#define flexidag_openseg_prim_split_6___pvcn_160011__vmem_buffer_num_bytes 	30880
#define flexidag_openseg_prim_split_6___pvcn_160011__dram_size_num_bytes 	30880

/* flexidag_openseg_prim_split_6 SMB_input __pvcn_160009_ */
#define flexidag_openseg_prim_split_6___pvcn_160009__cnngen_demangled_name 	"__pvcn_160009_"
#define flexidag_openseg_prim_split_6___pvcn_160009__is_constant 	1
#define flexidag_openseg_prim_split_6___pvcn_160009__has_init_data 	1
#define flexidag_openseg_prim_split_6___pvcn_160009__is_variable_scalar 	0
#define flexidag_openseg_prim_split_6___pvcn_160009__is_bitvector 	0
#define flexidag_openseg_prim_split_6___pvcn_160009__is_rlz 	0
#define flexidag_openseg_prim_split_6___pvcn_160009__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_6___pvcn_160009__is_twelve_bit_packed 	0
#define flexidag_openseg_prim_split_6___pvcn_160009__byte_offset 	232	/* 0x000000e8 */
#define flexidag_openseg_prim_split_6___pvcn_160009__vbase_byte_offset 	236	/* 0x000000ec */
#define flexidag_openseg_prim_split_6___pvcn_160009__dbase_byte_offset 	260	/* 0x00000104 */
#define flexidag_openseg_prim_split_6___pvcn_160009__dpitchm1_byte_offset 	264	/* 0x00000108 */
#define flexidag_openseg_prim_split_6___pvcn_160009__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6___pvcn_160009__W 	544
#define flexidag_openseg_prim_split_6___pvcn_160009__H 	1
#define flexidag_openseg_prim_split_6___pvcn_160009__D 	1
#define flexidag_openseg_prim_split_6___pvcn_160009__P 	1
#define flexidag_openseg_prim_split_6___pvcn_160009__data_num_bytes 	1
#define flexidag_openseg_prim_split_6___pvcn_160009__denable 	1
#define flexidag_openseg_prim_split_6___pvcn_160009__dpitch_num_bytes 	544
#define flexidag_openseg_prim_split_6___pvcn_160009__dram_format 	0
#define flexidag_openseg_prim_split_6___pvcn_160009__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_6___pvcn_160009__tile_width 	1
#define flexidag_openseg_prim_split_6___pvcn_160009__tile_height 	1
#define flexidag_openseg_prim_split_6___pvcn_160009__vmem_buffer_num_bytes 	544
#define flexidag_openseg_prim_split_6___pvcn_160009__dram_size_num_bytes 	544

/* flexidag_openseg_prim_split_6 SMB_input __pvcn_160012_ */
#define flexidag_openseg_prim_split_6___pvcn_160012__cnngen_demangled_name 	"__pvcn_160012_"
#define flexidag_openseg_prim_split_6___pvcn_160012__is_constant 	1
#define flexidag_openseg_prim_split_6___pvcn_160012__has_init_data 	1
#define flexidag_openseg_prim_split_6___pvcn_160012__is_variable_scalar 	0
#define flexidag_openseg_prim_split_6___pvcn_160012__is_bitvector 	0
#define flexidag_openseg_prim_split_6___pvcn_160012__is_rlz 	0
#define flexidag_openseg_prim_split_6___pvcn_160012__is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_6___pvcn_160012__is_twelve_bit_packed 	0
#define flexidag_openseg_prim_split_6___pvcn_160012__byte_offset 	272	/* 0x00000110 */
#define flexidag_openseg_prim_split_6___pvcn_160012__vbase_byte_offset 	276	/* 0x00000114 */
#define flexidag_openseg_prim_split_6___pvcn_160012__dbase_byte_offset 	300	/* 0x0000012c */
#define flexidag_openseg_prim_split_6___pvcn_160012__dpitchm1_byte_offset 	304	/* 0x00000130 */
#define flexidag_openseg_prim_split_6___pvcn_160012__dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6___pvcn_160012__W 	576
#define flexidag_openseg_prim_split_6___pvcn_160012__H 	1
#define flexidag_openseg_prim_split_6___pvcn_160012__D 	1
#define flexidag_openseg_prim_split_6___pvcn_160012__P 	1
#define flexidag_openseg_prim_split_6___pvcn_160012__data_num_bytes 	1
#define flexidag_openseg_prim_split_6___pvcn_160012__denable 	1
#define flexidag_openseg_prim_split_6___pvcn_160012__dpitch_num_bytes 	576
#define flexidag_openseg_prim_split_6___pvcn_160012__dram_format 	0
#define flexidag_openseg_prim_split_6___pvcn_160012__vp_interleave_mode 	0
#define flexidag_openseg_prim_split_6___pvcn_160012__tile_width 	1
#define flexidag_openseg_prim_split_6___pvcn_160012__tile_height 	1
#define flexidag_openseg_prim_split_6___pvcn_160012__vmem_buffer_num_bytes 	576
#define flexidag_openseg_prim_split_6___pvcn_160012__dram_size_num_bytes 	576

/* flexidag_openseg_prim_split_6 VCB ResizeBilinear_1 */
#define flexidag_openseg_prim_split_6_ResizeBilinear_1_cnngen_demangled_name 	"ResizeBilinear_1"
#define flexidag_openseg_prim_split_6_ResizeBilinear_1_is_bitvector 	0
#define flexidag_openseg_prim_split_6_ResizeBilinear_1_is_rlz 	0
#define flexidag_openseg_prim_split_6_ResizeBilinear_1_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_6_ResizeBilinear_1_is_twelve_bit_packed 	0
#define flexidag_openseg_prim_split_6_ResizeBilinear_1_byte_offset 	324	/* 0x00000144 */
#define flexidag_openseg_prim_split_6_ResizeBilinear_1_vbase_byte_offset 	332	/* 0x0000014c */
#define flexidag_openseg_prim_split_6_ResizeBilinear_1_vmem_buffer_num_bytes 	663552

/* flexidag_openseg_prim_split_6 HMB_output concat */
#define flexidag_openseg_prim_split_6_concat_cnngen_demangled_name 	"concat"
#define flexidag_openseg_prim_split_6_concat_is_main_input_output 	0
#define flexidag_openseg_prim_split_6_concat_is_bitvector 	0
#define flexidag_openseg_prim_split_6_concat_is_rlz 	0
#define flexidag_openseg_prim_split_6_concat_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_6_concat_is_twelve_bit_packed 	0
#define flexidag_openseg_prim_split_6_concat_byte_offset 	360	/* 0x00000168 */
#define flexidag_openseg_prim_split_6_concat_vbase_byte_offset 	364	/* 0x0000016c */
#define flexidag_openseg_prim_split_6_concat_dbase_byte_offset 	388	/* 0x00000184 */
#define flexidag_openseg_prim_split_6_concat_dpitchm1_byte_offset 	392	/* 0x00000188 */
#define flexidag_openseg_prim_split_6_concat_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6_concat_vwidth_minus_one_byte_offset 	376	/* 0x00000178 */
#define flexidag_openseg_prim_split_6_concat_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6_concat_vheight_minus_one_byte_offset 	378	/* 0x0000017a */
#define flexidag_openseg_prim_split_6_concat_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6_concat_drotate_bit_offset 	3078	/* 0x00000c06 */
#define flexidag_openseg_prim_split_6_concat_hflip_bit_offset 	3079	/* 0x00000c07 */
#define flexidag_openseg_prim_split_6_concat_vflip_bit_offset 	3080	/* 0x00000c08 */
#define flexidag_openseg_prim_split_6_concat_dflip_bit_offset 	3081	/* 0x00000c09 */
#define flexidag_openseg_prim_split_6_concat_pflip_bit_offset 	3082	/* 0x00000c0a */
#define flexidag_openseg_prim_split_6_concat_W  	160
#define flexidag_openseg_prim_split_6_concat_H  	64
#define flexidag_openseg_prim_split_6_concat_D  	768
#define flexidag_openseg_prim_split_6_concat_P  	1
#define flexidag_openseg_prim_split_6_concat_data_num_bytes 	2
#define flexidag_openseg_prim_split_6_concat_denable 	1
#define flexidag_openseg_prim_split_6_concat_dpitch_num_bytes 	32
#define flexidag_openseg_prim_split_6_concat_dram_format 	3
#define flexidag_openseg_prim_split_6_concat_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_6_concat_tile_width 	4
#define flexidag_openseg_prim_split_6_concat_tile_height 	1
#define flexidag_openseg_prim_split_6_concat_vmem_buffer_num_bytes 	503808
#define flexidag_openseg_prim_split_6_concat_dram_size_num_bytes 	15728640
#define flexidag_openseg_prim_split_6_concat_sign 	0
#define flexidag_openseg_prim_split_6_concat_datasize 	1
#define flexidag_openseg_prim_split_6_concat_expoffset 	13
#define flexidag_openseg_prim_split_6_concat_expbits 	0
#define flexidag_openseg_prim_split_6_concat_drotate 	0
#define flexidag_openseg_prim_split_6_concat_hflip 	0
#define flexidag_openseg_prim_split_6_concat_vflip 	0
#define flexidag_openseg_prim_split_6_concat_dflip 	0
#define flexidag_openseg_prim_split_6_concat_pflip 	0

/* flexidag_openseg_prim_split_6 VCB Relu */
#define flexidag_openseg_prim_split_6_Relu_cnngen_demangled_name 	"Relu"
#define flexidag_openseg_prim_split_6_Relu_is_bitvector 	0
#define flexidag_openseg_prim_split_6_Relu_is_rlz 	0
#define flexidag_openseg_prim_split_6_Relu_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_6_Relu_is_twelve_bit_packed 	0
#define flexidag_openseg_prim_split_6_Relu_byte_offset 	468	/* 0x000001d4 */
#define flexidag_openseg_prim_split_6_Relu_vbase_byte_offset 	476	/* 0x000001dc */
#define flexidag_openseg_prim_split_6_Relu_vmem_buffer_num_bytes 	166912

/* flexidag_openseg_prim_split_6 HMB_output Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1 */
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_cnngen_demangled_name 	"Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1"
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_is_main_input_output 	0
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_is_bitvector 	0
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_is_rlz 	0
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_is_twelve_bit_packed 	0
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_byte_offset 	504	/* 0x000001f8 */
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_vbase_byte_offset 	508	/* 0x000001fc */
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_dbase_byte_offset 	532	/* 0x00000214 */
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_dpitchm1_byte_offset 	536	/* 0x00000218 */
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_dpitchm1_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_vwidth_minus_one_byte_offset 	520	/* 0x00000208 */
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_vwidth_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_vheight_minus_one_byte_offset 	522	/* 0x0000020a */
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_vheight_minus_one_bsize 	16	/* 0x00000010 */
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_drotate_bit_offset 	4230	/* 0x00001086 */
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_hflip_bit_offset 	4231	/* 0x00001087 */
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_vflip_bit_offset 	4232	/* 0x00001088 */
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_dflip_bit_offset 	4233	/* 0x00001089 */
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_pflip_bit_offset 	4234	/* 0x0000108a */
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_W 	320
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_H 	128
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_D 	128
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_P 	1
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_data_num_bytes 	1
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_denable 	1
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_dpitch_num_bytes 	32
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_dram_format 	3
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_vp_interleave_mode 	2
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_tile_width 	4
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_tile_height 	1
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_vmem_buffer_num_bytes 	167936
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_dram_size_num_bytes 	5242880
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_sign 	0
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_datasize 	0
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_expoffset 	5
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_expbits 	0
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_drotate 	0
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_hflip 	0
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_vflip 	0
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_dflip 	0
#define flexidag_openseg_prim_split_6_Conv_1__Conv2D___BiasAdd___BatchNorm_1__FusedBatchNorm___muli___10___BatchNorm_1__FusedBatchNorm___Relu_1_pflip 	0

/* flexidag_openseg_prim_split_6 SMB_output split_6__vas_created_terminate__v0 */
#define flexidag_openseg_prim_split_6_split_6__vas_created_terminate__v0_cnngen_demangled_name 	"split_6__vas_created_terminate__v0"
#define flexidag_openseg_prim_split_6_split_6__vas_created_terminate__v0_is_main_input_output 	0
#define flexidag_openseg_prim_split_6_split_6__vas_created_terminate__v0_is_bitvector 	1
#define flexidag_openseg_prim_split_6_split_6__vas_created_terminate__v0_is_rlz 	0
#define flexidag_openseg_prim_split_6_split_6__vas_created_terminate__v0_is_ten_bit_packed 	0
#define flexidag_openseg_prim_split_6_split_6__vas_created_terminate__v0_is_twelve_bit_packed 	0
#define flexidag_openseg_prim_split_6_split_6__vas_created_terminate__v0_byte_offset 	608	/* 0x00000260 */
#define flexidag_openseg_prim_split_6_split_6__vas_created_terminate__v0_vbase_byte_offset 	612	/* 0x00000264 */
#define flexidag_openseg_prim_split_6_split_6__vas_created_terminate__v0_W 	256
#define flexidag_openseg_prim_split_6_split_6__vas_created_terminate__v0_H 	3
#define flexidag_openseg_prim_split_6_split_6__vas_created_terminate__v0_D 	1
#define flexidag_openseg_prim_split_6_split_6__vas_created_terminate__v0_P 	1
#define flexidag_openseg_prim_split_6_split_6__vas_created_terminate__v0_data_num_bytes 	1
#define flexidag_openseg_prim_split_6_split_6__vas_created_terminate__v0_denable 	0
#define flexidag_openseg_prim_split_6_split_6__vas_created_terminate__v0_dram_format 	0
#define flexidag_openseg_prim_split_6_split_6__vas_created_terminate__v0_vp_interleave_mode 	1
#define flexidag_openseg_prim_split_6_split_6__vas_created_terminate__v0_tile_width 	1
#define flexidag_openseg_prim_split_6_split_6__vas_created_terminate__v0_tile_height 	1
#define flexidag_openseg_prim_split_6_split_6__vas_created_terminate__v0_vmem_buffer_num_bytes 	96


#endif /* flexidag_openseg_prim_split_6_H */
