ifeq ($(PROJECT),cv1)
CVCHIP := CHIP_CV1
else ifeq ($(PROJECT),cv1i)
CVCHIP := CHIP_CV1
CVARCH := ARCH_CV1
else ifeq ($(PROJECT),cv2)
CVCHIP := CHIP_CV2
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv2i)
CVCHIP := CHIP_CV2
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv22)
CVCHIP := CHIP_CV22
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv22i)
CVCHIP := CHIP_CV22
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv2s)
CVCHIP := CHIP_CV22
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv2e)
CVCHIP := CHIP_CV25
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv25)
CVCHIP := CHIP_CV25
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv25i)
CVCHIP := CHIP_CV25
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv2l)
CVCHIP := CHIP_CV28
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv28)
CVCHIP := CHIP_CV28
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv28i)
CVCHIP := CHIP_CV28
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv5)
CVCHIP := CHIP_CV5
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv5i)
CVCHIP := CHIP_CV5
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv5s)
CVCHIP := CHIP_CV5
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv52)
CVCHIP := CHIP_CV52
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv52s)
CVCHIP := CHIP_CV52
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv2a)
CVCHIP := CHIP_CV2A
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv2ai)
CVCHIP := CHIP_CV2A
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv2fs)
CVCHIP := CHIP_CV2FS
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv22a)
CVCHIP := CHIP_CV22A
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv22ai)
CVCHIP := CHIP_CV22A
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv22fs)
CVCHIP := CHIP_CV22FS
CVARCH := ARCH_CV2
else ifeq ($(PROJECT),cv6)
CVCHIP := CHIP_CV6
CVARCH := ARCH_CV3
else ifeq ($(PROJECT),cv6i)
CVCHIP := CHIP_CV6
CVARCH := ARCH_CV3
else ifeq ($(PROJECT),cv6a)
CVCHIP := CHIP_CV6A
CVARCH := ARCH_CV3
else ifeq ($(PROJECT),cv6ai)
CVCHIP := CHIP_CV6A
CVARCH := ARCH_CV3
else ifeq ($(PROJECT),cv7)
CVCHIP := CHIP_CV7
CVARCH := ARCH_CV3
else ifeq ($(PROJECT),cv7i)
CVCHIP := CHIP_CV7
CVARCH := ARCH_CV3
else
$(error project must be set to cv1[i], cv2[i], cv22[i]/cv2s, cv2e, cv25[i], cv2l, cv28[i], cv5[/i/s], cv52[s], cv2a[i], cv22a[i], cv2fs, cv22fs, cv6[a][i], or cv7[i])
endif

