# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2004-2011, Ambarella, Inc.
#

obj-$(CONFIG_AMBARELLA_PIO) += ambarella_pio.o
obj-$(CONFIG_AMBARELLA_RCT_PROFILE) += ambarella_rct_profile.o
obj-$(CONFIG_ARCH_AMBARELLA) += soc.o iav_helper.o syncproc.o io.o ddrc.o dramc.o
obj-$(CONFIG_AMBARELLA_SUPPORT_GDMA) += gdma.o
obj-$(CONFIG_AMBARELLA_LPDDR5_ADJUST) += lpddr5_adjust.o
obj-$(CONFIG_AMBARELLA_DRAMC_STATS) += dramc_stats.o
