ccflags-y += -I$(srctree)/svc/apps/iout/$(TARGET_APP_SRC_PATH)/peripherals/$(AMBA_CHIP_ID)/yuvinput/inc

YUVINPUTPATH=$(TARGET_APP_SRC_PATH)/peripherals/$(AMBA_CHIP_ID)/yuvinput
libeng_perif_${AMBA_CHIP_ID}-objs += $(YUVINPUTPATH)/AmbaYuv_MAX9295_96712_AmbaVout.o \
                                  $(YUVINPUTPATH)/AmbaYuv_MAX9295_96712_AmbaVoutTable.o
