#!/bin/sh
#
# sshd        Starts sshd.
#

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

umask 077

start() {
	# Create any missing keys
	#/usr/bin/ssh-keygen -A
	mkdir -p /tmp/ssh
	ssh-keygen -t rsa -P "" -f /tmp/ssh/ssh_host_rsa_key > /dev/null
	ssh-keygen -t ecdsa -P "" -f /tmp/ssh/ssh_host_ecdsa_key > /dev/null
	ssh-keygen -t ed25519 -P "" -f /tmp/ssh/ssh_host_ed25519_key > /dev/null

	printf "Starting sshd: "
	/usr/sbin/sshd
	touch /var/lock/sshd
	echo "OK"
}
stop() {
	printf "Stopping sshd: "
	killall sshd
	rm -f /var/lock/sshd
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

