#############################################################
#
# amba_netcontrol
#
#############################################################

pkg			= AMBA_NETCONTROL

$(pkg)_VERSION		= 1.0
$(pkg)_SITE_METHOD	= local
$(pkg)_SITE		= $(AMBARELLA_PKG_DIR)/amba_netcontrol
$(pkg)_SOURCE		= amba_netcontrol-$($(pkg)_VERSION).tar.gz
$(pkg)_DEPENDENCIES	= amba_netcontrol_util
$(pkg)_INSTALL_STAGING	= NO
$(pkg)_INSTALL_IMAGES	= NO
$(pkg)_INSTALL_TARGET	= YES
$(pkg)_LICENSE		= Ambarella
$(pkg)_LICENSE_FILES	= License_Ambarella.txt

ifeq ($(BR2_arm),y)
ARMBADFLAGS = -DUSE_ARM
endif

ifeq ($(BR2_PACKAGE_AMBA_NETCONTROL_WIFI),y)
ifeq ($(BR2_PACKAGE_AMBA_NETCONTROL_WIFI_CMD),y)
AMBA_NETCONTROL_WIFI_CMD_CPPFLAG		= -DWIFICMD $(WIFICMDFLAGS)
endif
ifeq ($(BR2_PACKAGE_AMBA_NETCONTROL_WIFI_DATA),y)
AMBA_NETCONTROL_WIFI_DATA_CPPFLAG		= -DWIFIDATA $(WIFIDATAFLAGS)
endif
endif

ifeq ($(BR2_PACKAGE_AMBA_NETCONTROL_BT),y)
ifeq ($(BR2_PACKAGE_BLUEZ_UTILS),y)
$(pkg)_DEPENDENCIES	+= bluez_utils
endif
ifeq ($(BR2_PACKAGE_BLUEZ5_UTILS),y)
$(pkg)_DEPENDENCIES	+= bluez5_utils
endif

ifeq ($(BR2_PACKAGE_AMBA_NETCONTROL_BT_CMD),y)
AMBA_NETCONTROL_BT_CMD_CPPFLAG		= -DBTCMD $(BTCMDFLAGS)
endif
ifeq ($(BR2_PACKAGE_AMBA_NETCONTROL_BT_DATA),y)
AMBA_NETCONTROL_BT_DATA_CPPFLAG		= -DBTDATA $(BTDATAFLAGS)
endif

AMBA_NETCONTROL_BT_LIBS		= -lbluetooth $(LIBS)
endif

define AMBA_NETCONTROL_INSTALL_TARGET_CMDS
  $(TARGET_CONFIGURE_OPTS) $(TARGET_MAKE_ENV) \
  WIFICMDFLAGS=$(AMBA_NETCONTROL_WIFI_CMD_CPPFLAG) \
  WIFIDATAFLAGS=$(AMBA_NETCONTROL_WIFI_DATA_CPPFLAG) \
  BTCMDFLAGS=$(AMBA_NETCONTROL_BT_CMD_CPPFLAG) \
  BTDATAFLAGS=$(AMBA_NETCONTROL_BT_DATA_CPPFLAG) \
  LIBS=$(AMBA_NETCONTROL_BT_LIBS) ARMBADFLAGS="$(ARMBADFLAGS)"\
  $(MAKE) -C $(@D) -f br.mk DESTDIR=$(TARGET_DIR) install
endef

define AMBA_NETCONTROL_BUILD_CMDS
  $(TARGET_CONFIGURE_OPTS) $(TARGET_MAKE_ENV) \
  WIFICMDFLAGS=$(AMBA_NETCONTROL_WIFI_CMD_CPPFLAG) \
  WIFIDATAFLAGS=$(AMBA_NETCONTROL_WIFI_DATA_CPPFLAG) \
  BTCMDFLAGS=$(AMBA_NETCONTROL_BT_CMD_CPPFLAG) \
  BTDATAFLAGS=$(AMBA_NETCONTROL_BT_DATA_CPPFLAG) \
  LIBS=$(AMBA_NETCONTROL_BT_LIBS) ARMBADFLAGS="$(ARMBADFLAGS)"\
  $(MAKE) -C $(@D) -f br.mk
endef

define AMBA_NETCONTROL_CLEAN_CMDS
  $(TARGET_CONFIGURE_OPTS) $(TARGET_MAKE_ENV) \
  WIFICMDFLAGS=$(AMBA_NETCONTROL_WIFI_CMD_CPPFLAG) \
  WIFIDATAFLAGS=$(AMBA_NETCONTROL_WIFI_DATA_CPPFLAG) \
  BTCMDFLAGS=$(AMBA_NETCONTROL_BT_CMD_CPPFLAG) \
  BTDATAFLAGS=$(AMBA_NETCONTROL_BT_DATA_CPPFLAG) \
  LIBS=$(AMBA_NETCONTROL_BT_LIBS) ARMBADFLAGS="$(ARMBADFLAGS)"\
  $(MAKE) -C $(@D) -f br.mk clean
endef

define AMBA_NETCONTROL_POST_LEGAL_INFO_HOOKS_CMD
	@$(foreach F,$($(PKG)_LICENSE_FILES),$(call legal-license-file,$$($(PKG)_RAWNAME),$(F),$$($(PKG)_DIR)/$(F))$$(sep))
endef
AMBA_NETCONTROL_POST_LEGAL_INFO_HOOKS += AMBA_NETCONTROL_POST_LEGAL_INFO_HOOKS_CMD

$(eval $(generic-package))
